---
title: "As aplicações da Teoria de Galois"
number-sections: true
lang: pt-BR
---

## Extensões e torres radicais
:::{#def-ext-rad}
Seja $\E:\F$ uma extensão de corpos. Dizemos que $\E$ é uma *extensão radical* de $\F$ se $\E=\F(\alpha)$ com $\alpha\in\E$ tal que $\alpha^k\in \F$. Assumindo que $k\in\N$ é menor tal que $\beta=\alpha^k\in\F$, escrevemos também que $\E=\F(\sqrt[k]\beta)$. Assuma que 
$$
\K_0\subseteq \K_1\subseteq \K_2\subseteq \cdots\subseteq \K_s
$$ 
é uma torre de extensões. Dizemos que ela é uma *torre radical* se cada extensão $\K_{i+1}:\K_{i}$ é extensão radical.
:::

:::{#exm-ext-rad}
As extensões $\Q(\sqrt[3]2):\Q$ e $\Q(\xi):\Q$, onde $\xi=\exp(2\pi i/3)$ são extensões radicais. A torre 
$$
\Q\subset \Q(\xi)\subset\Q(\xi,\sqrt[3]2)
$$
é uma torre radical.
:::

:::{#def-res-rad}
Seja $f(x)\in\F[x]$. Dizemos que $f(x)$ é resolúvel por radicais se existe uma torre radical 
$$
\F=\K_0\subseteq \K_1\subseteq \K_2\subseteq \cdots\subseteq \K_s
$$
tal que $\K_s$ contém um corpo de decomposição de $f(x)$. Ou seja 
$$
f(x)=\alpha(x-\alpha_1)\cdots(x-\alpha_m)\quad\mbox{com}\quad \alpha,\alpha_i\in \K_s.
$$
:::

:::{#exm-quadratic-radical}
Seja $f(x)=ax^2+bx+c\in\Q[x]$ com $a\neq 0$. Temos que $f(x)$ é resolúvel por radicais. De fato, se $\Delta=b^2-4ac$ é o discriminante de $f(x)$, então temos que $\Q(\sqrt \Delta)$ é corpo de decomposição de $f(x)$.
:::

:::{#exm-nadic-radical}
Seja $a\in \Z$. O polinômio $f(x)=x^n-a$ é resolúvel por radicais. De fato, seja $\xi=\exp(2\pi i/n)$ e 
$$
\Q\subseteq \Q(\xi_n)\subseteq \Q(\xi_n,\sqrt[n]a)
$$
é uma torre radical e o último termo é corpo de decomposição de $f(x)$. 
:::

## Extensões ciclotômicas 

:::{#exr-cyclic-aut}
Demonstre que $\aut{\Z_n}\cong\Z_n^*$. Deduza que se  $G$ é um grupo cíclico de ordem $k$, então $\aut G$ é abeliano de ordem $\varphi(k)$. 
:::

:::{#lem-root-cyclic}
Assuma que $\E$ é um corpo de caraterística zero e seja $\K$ corpo de decomposição do polinômio $f(x)=x^k-1\in\E[x]$.  Então temos que 
$\K:\E$ é uma extensão finita de Galois e $\gal{\K}{\E}$ é abeliano cuja ordem divide $\varphi(k)$. 
:::
:::{.proof}
Seja 
$$
R_k=\{\xi\in\K\mid \xi^k=1\}\subseteq \K
$$
o conjunto de todas as raízes de $f(x)$. Note que $R_k$ é fechado para multiplicação, então ele é um grupo. Por @thm-field-cyclic, $R_k$ é um grupo cíclico. Seja $\xi$ um gerador de $R_k$ tal que 
$$
R_k=\{\xi^0,\xi^1,\ldots,\xi^{k-1}\}
$$
O corpo $\E$ é corpo de decomposição do polinômio $x^k-1\in\E[x]$ e $\K:\E$ é uma extensão de Galois finita.  Além disso, $\K=\E(\xi)$ e 
se $\sigma\in\gal{\E(\xi)}{\E}$, então $\sigma$ está determinado por $\sigma(\xi)$. Além disso, 
$$
\sigma(\xi^i\xi^j)=\sigma(\xi^i)\sigma(\xi^j)
$$
e $\sigma$ induz um elemento de $\aut {R_k}$. Obtemos um homomorfismo $\psi:\gal{\K}{\E}\to \aut{R_k}$. Note que $\ker\psi$ contém os elementos $\sigma\in\gal{\K}{\E}$ tal que $\sigma(\xi)=\xi$. Como $\K=\E(\xi)$ está gerado por $\xi$ (sobre $\E$), temos que $\psi$ é 
injetiva. Portanto $\gal{\K}{\E}$ pode ser visto como um subgrupo de $\aut{R_k}$ que é abeliano de ordem $\varphi(k)$ por @exr-cyclic-aut. 
:::

:::{#lem-root-cyclic2}
Assuma que $\E$ é um corpo de caraterística zero que contem um corpo de decomposição de $x^k-1$ e seja $\K=\E(\sqrt[k]\alpha)$ com algum $\alpha\in \E$. Então 
temos que $\K:\E$ é uma extensão finita de Galois com grupo de Galois cíclico.
:::
:::{.proof}
Temos que $\K=\E(\beta)$ tal que $\beta^k=\alpha\in\E$. Temos que $\beta$ é raiz de $f(x)=x^k-\alpha$ e as raízes de $f(x)$ são 
$\beta, \xi_k\beta,\ldots,\xi_k^{k-1}\beta$ onde $\xi_k\in\E$ é uma $k$-ésima raiz primitiva da unidade. Como $\xi_k\in\E$, temos que $\K$ é um corpo de decomposição de $f(x)$ sobre $\E$. Em particular $\K:\E$ é de Galois. Seja $\sigma\in\gal\K\E$. Então $\sigma(\beta)$ é raiz de $f(x)$ e assim $\sigma(\beta)=\xi_k^i\beta$ com algum $i\in\{0,\ldots,k-1\}$.  Considere o grupo 
$$
R_k=\{\xi_k^0,\ldots,\xi_k^{k-1}\}\subseteq \E
$$
como na demonstração do @lem-root-cyclic e 
Defina, 
$$
\psi:\gal\K\E\to R_k,\quad \psi(\sigma)=\xi_k^i.
$$ 
Note que $\psi$ é um homomorfismo injetivo e $\gal\E\K$ pode ser visto como um subgrupo de $R_k$. Como $R_k$ é cíclico $\gal\E\K$ é cíclico (@lem-subgroup-cyclic).
:::

## Resolubulidade de polinômios por radicais 

:::{#thm-galois}
Assuma que $\F$ é um corpo de caraterística zero e que $f(x)\in\F[x]$ é resolúvel por radicais e seja $\K$ um corpo de decomposição de $f(x)$. Então temos que $\gal\F\K$ é um grupo solúvel
:::
:::{.proof}
Assuma que $f(x)$ é resolúvel por radicais. Seja 
$$
\K_0=\F\subset \K_1\subset \K_2\subset\cdots\subset \K_s
$$
uma torre radical tal que $\K_s$ contém um corpo de decomposição $\K$ de $f(x)$. Assuma que $\K_{i}=\K_{i-1}(\sqrt[k_i]{a_i})$ para todo $i\in\{1,\ldots,s\}$. Vamos refazer a torre radical para uma nova torre 
$$
\E_0=\F\subset \E_1\subset \E_2\subset\cdots\subset \E_r  
$$
tal que

1. $\E_r$ contém $\K$;
2. a extensão $\E_r:\F$ é finita de de Galois;
3. cada passo $\E_{i+1}:\E_i$ é uma extensão radical;
4. cada passo $\E_{i+1}:\E_i$ é finito de Galois com $\gal{\E_{i+1}}{\E_i}$ abeliano.

Para isso, assuma que $\K_{i}=\K_{i-1}(b_i)$ onde $b_i^{k_i}=a_i$ e ponha $k=k_1\cdots k_s$. Seja $\E$ o corpo de decomposição do polinômio
$$
h(x)=(x^k-1)m^{\F}_{b_1}(x)\cdots m^{\F}_{b_s}(x).
$$
A extensão $\F:\E$ é de Galois finita. Seja $G$ o grupo de Galois $\gal\F\E$. Note que $G$ é um grupo finito e assuma que 
$G=\{1,g_2,\ldots,g_m\}$. Seja $\xi$ uma raiz $k$-ésima primitiva da unidade e considere a seguinte sequência de elementos de $\E$:
$$
\xi,b_1,\ldots,b_s,g_2(b_1),\ldots,g_2(b_s),\ldots,g_m(b_1),\ldots,g_m(b_s).
$$  
Seja 
$$
\E_0=\F\subseteq \E_1\subseteq \E_2\subseteq \cdots\subseteq \E_r
$$
a torre obtida por estender cada $\E_i$ pelo seguinte elemento na sequência. Em particular, $\E_1=\F(\xi)$. Afirmamos que esta torre satisfaz as afirmações 1.-4. 

1. Note que $\K_s=\F(b_1,\ldots,b_s)\subseteq \E_r$, então esta afirmação está certa. 
2. Afirmamos que $\E=\E_r$. Note que $\E$ é gerado (sobre $\F$) pelas raízes de $h(x)$ que são as raízes dos fatores individuais de $h(x)$.
As raízes de $(x^k-1)$ são as potências de $\xi$. Note que $b_i$  é uma raíz de $m^{\F}_{b_i}(x)$. Se $g\in G$, então $g(b_i)$ também é raiz de $m^{\F}_{b_i}(x)$. 
Isso mostra que $\E_r\subseteq \E$. Além disso, o @lem-lifting-isom implica que se $\gamma\in\E$ é raiz de $m_{\beta_i}^{\F}(x)$, então existe $g\in\gal\E\F$ tal que $g(\beta_i)=\gamma$. Ou seja, as raízes de $m^{\F}_{b_i}(x)$ são precisamente os elementos $b_i,g_2(b_i),\ldots,g_m(b_i)$. Em outras palavras, os elementos na sequência são precisamente as raízes de $h(x)$ e $\E_r$ está gerado por extes elementos. Em particular $\E\subseteq \E_r$ e $\E_r=\E$. 
3. Note que $\E_1=\E_0(\xi)$ e $\E_{i+1}=\E_i(g(b_j))$ com algum $g\in G$ e $b_j\in \E$.  Como 
$$
b_j^{k_j}\in \K_{j-1}=\F(b_1,\ldots,b_{j-1}),
$$ 
temos que
$$
g(b_j)^{k_j}=g(b_j^{k_j})\in g(\K_{j-1})=\F(g(b_1),\ldots,g(b_{j-1}))\subseteq \E_i. 
$$
4. O passo $\E_1:\E_0=\F(\xi):\F$ é finito de Galois com grupo de Galois abeliano por @lem-root-cyclic. Os demais passos são finitos de Galois por @lem-root-cyclic2.

Provaremos  agora que $\gal\F\K$ solúvel. Seja $G=\gal\F\E$ como em cima. A torre de extensões 
$$
\F=\E_0\subseteq \E_1\subseteq \E_2\subseteq \cdots\subseteq \E_r=\E
$$
corresponde a uma cadeia de subgrupos 
$$
G=G_0\geq G_1\geq G_2\geq \cdots\geq G_r=1
$$
onde $G_i=\gal{\E}{\E_i}$. Afirmamos que $G$ é solúvel. De fato, como cada extensão $\E_{i+1}:\E_i$ é Galois, temos que $G_{i+1}\unlhd G_i$ e 
$$
G_i/G_{i+1}=\gal\E{\E_{i}}/\gal\E{\E_{i+1}}\cong\gal{\E_{i+1}}{\E_i}.
$$
Mas $\gal{\E_{i+1}}{\E_i}$ é abeliano por afirmação 4. Portanto, temos que $G$ é grupo solúvel por @def-solvable2. Ora, $\K\subseteq \E$ e 
$$
\gal\K\F\cong\gal\E\F/\gal\E\K
$$
e obtemos que $\gal{\K}\F$ é um grupo solúvel.
:::

## O Teorema de Abel-Ruffini

:::{#thm-abel-ruffini}
Se $n\geq 5$, então existe $f(x)\in\Q[x]$ de grau $n$ tal que $f(x)$ não é resolúvel por radicais. 
:::
:::{.proof}
É suficiente provar que existe um polinômio de grau $n$ (para todo $n\geq 5$) tal que $\gal\E\Q$ não é solúvel onde $\E$ é o corpo de decomposição de $f(x)$. 

Seja $f(x)\in\Q[x]$ um polinômio irredutível de grau $5$ com precisamente três raízes reais e seja $G$ o grupo de Galois do seu corpo de decomposição sobre $\Q$. Temos por @thm-transitive que $G$ age transitivamente nos seus $5$ raízes distintas, então $5\mid |G|$ (@cor-orbit-stab). Portanto, $G$ possui um elemento $a$ de ordem $5$ (@cor-cauchy). Além disso, as duas raízes não reais são conjugadas complexas e assim a conjugação complexa é um elemento $b$ de $G$ e $b$ induz uma transposição destas duas raízes. Ora, $G$ contem um elemento de ordem $5$, que deve ser um ciclo de comprimento $5$, e uma transposição. Mas estes elementos geram $S_5$, e $G=S_5$. Como $S_5$ não é solúvel, temos que $f(x)$ não é resolúvel por radicais. 

Para o caso geral de $n\geq 5$, toma um polinômio divisível por $f(x)$. 
:::

:::{#exm-abel-ruffini}
O polinômio $x^5-20x+5$ satisfaz as propriedades exigidas na demonstração do @thm-abel-ruffini.
:::

## Demais aplicações da Teoria de galois

{{< video https://youtu.be/O1sPvUr0YC0?si=muIGR-8t5_fmp95d width="560" height="315" >}} 