---
title: "Classes de conjugação"
number-sections: true
lang: pt-BR
---

## Classes de conjugação




Considere a ação de $G$ em $\Omega=G$ por conjugação já estudada no @exm-cent; ou seja, $(x,g)\mapsto x^g=g^{-1}xg$. Se $x\in \Omega$ então a órbita $x^G=\{x^g \mid g\in G\}$ é chamada de *classe de conjugação* de $x$ em $G$. O estabilizador de $x\in \Omega$ nesta ação é o subgrupo
\begin{eqnarray*}
G_x&=&C_G(x)=\{g\in G\mid g^{-1}xg= x\}\\&=&\{g\in G\mid xg= gx\}.
\end{eqnarray*}
Este subgrupo chama-se o *centralizador* de $x$ em $G$. Temos pelo Teorema Órbita-Estabilizador que $|x^G|=|G:C_G(x)|$. Em particular, se $G$ é finito, obtemos o seguinte resultado.

:::{#prp-class-cent}
Se $G$ é um grupo finito e $x\in G$, então
$$
|x^G|=\frac{|G|}{|C_G(x)|}.
$$
:::

## Classes de conjugação em $S_n$

:::{#def-partition}
Se $n\in\N$, então uma *partição* de $n$ é uma sequẽncia $\lambda=(k_1,\ldots,k_m)$ tal que  $k_1\geq k_2\geq\cdots\geq k_m$ e $k_1+\cdots+k_m=n$. Neste caso escrevemos que 
$\lambda\vdash n$. 
:::

:::{#exm-p5}
Por exemplo, as partições de $5$ são 
$$
(1,1,1,1,1),\ (2,1,1,1),\ (2,2,1),\ (3,1,1),\ (3,2),\ (4,1),\ (5) 
$$
:::

[Partições](https://en.wikipedia.org/wiki/Integer_partition) são importantes em várias áreas da matemática e estatística. O número de partições de um inteiro $n$ aparece como a sequência [A000041](https://oeis.org/A000041) na [Online Encyclopedia of Integer Sequences](https://oeis.org/).

:::{#exm-perm-part}
Cada permutação $\sigma\in S_n$ determina uma partição de $n$. De fato, assuma que $\sigma$ é produto de ciclos de comprimento $\lambda_1,\ldots,\lambda_m$, em ordem não crescente, contando também os ciclos de comprimento $1$. Então $\lambda=(\lambda_1,\ldots,\lambda_m)\vdash n$. Por exemplo, a partição determinada pela permutação $(1,2)(3,4)(5,6,7)\in S_8$ é $(3,2,2,1)$. 
:::

:::{#exr-class-cent}
Se $(i_1,\ldots,i_k)\in S_n$ é um ciclo e $\sigma\in S_n$, então 
$$ 
    (i_1,\ldots,i_k)^\sigma=(i_1\sigma,\ldots,i_k\sigma). 
$$
Demonstre que $\sigma_1,\sigma_2\in S_n$ são conjugados em $S_n$ se e somente eles determinam a mesma partição de $n$. 
:::

:::{#exm-classes-s5}
Considere o grupo $S_5$. Pelo @exm-p5, este grupo tem 7 classes de conjugação com os seguintes representantes: $1$, $(1,2)$, $(1,2)(3,4)$, $(1,2,3)$, $(1,2,3)(4,5)$, $(1,2,3,4)$, e $(1,2,3,4,5)$. Note que cada classe corresponde a uma partição no @exm-p5. A seguinte tabela contém as cardinalidades destas classes, as cardinalidades do centralizador do representante, e geradores do centralizador.


| $x$                | $|x^{S_5}|$        | $|C_{S_5}(x)|$           | $C_{S_5}(x)$                           | 
| ------------------ | ------------------ | ------------------------ | -------------------------------------- |
| $1$                | $1$                | $120$                    | $S_5$                                  |
| $(1,2)$            | $10$               | $12$                     | $\left<(1,2),(3,4),(3,4,5)\right>$     | 
| $(1,2)(3,4)$       | $15$               | $8$                      | $\left<(1,2),(1,3,2,4)\right>$         |   
| $(1,2,3)$          | $20$               | $6$                      | $\left<(1,2,3),(4,5)\right>$           |
| $(1,2,3)(4,5)$     | $20$               | $6$                      | $\left<(1,2,3),(4,5)\right>$           |
| $(1,2,3,4)$        | $30$               | $4$                      | $\left<(1,2,3,4)\right>$               |
| $(1,2,3,4,5)$      | $24$               | $5$                      | $\left<(1,2,3,4,5)\right>$
:::

:::{#exr-s6}
Determine as tabelas das classes de comjugação para os grupos $S_3$, $S_4$, e $S_6$. 
:::

## O centro de um grupo

O centro $Z(G)$ de um grupo $G$ foi definido na @def-center como
\begin{eqnarray*}
Z(G)&=&\{g\in G\mid gh=hg\mbox{ para todo }h\in G\}\\&=&\{g\in G\mid g^h=g\mbox{ para todo }h\in G\}.
\end{eqnarray*}


Para $g\in G$, observe que $\{g\}$ é uma classe de conjugação se e somente se $g\in Z(G)$. (Pode-se deduzir da tabela em cima que $Z(S_5)=\{1\}$.) Se $G$ é um grupo finito e $C_1,\ldots,C_m$ são as classes de $G$ com cardinalidade maior ou igual a dois, então podemos escrever o grupo $G$ como uma união disjunta
$$
G=Z(G)\cup C_1\cup\cdots\cup C_m
$$
e isso implica que
$$
|G|=|Z(G)|+ |C_1|+\cdots+|C_m|.
$${#eq-class}
A equação @eq-class é chamada de equação das classes de $G$.

Considerando a equação das classes para grupos cuja ordem é uma potência de um primo, obtemos o seguinte resultado importante.

:::{#thm-center-pgp}
Seja $p$ um primo e seja $G$ um grupo tal que $|G|=p^k$ com algum $k\geq 1$. Então o centro $Z(G)$ é não trivial (ou seja, $|Z(G)|>1$).
:::

:::{.proof}
Considere a equação @eq-class para o grupo $G$. Como as classes $C_i$ são $G$-órbitas para uma ação de $G$ (nomeadamente, a conjugação de $G$ em $G$), temos que $|C_i|$ é um divisor de $|G|=p^k$; ou seja $|C_i|=p^{k_i}$ com algum $k_i\geq 1$. O lado esquerdo da equação das classes é uma potência de $p$, e os termos $|C_i|$ no lado direito também são potências de $p$. Isso quer dizer que $p\mid |Z(G)|$ e em particular que $|Z(G)|>1$.
:::

Note que um grupo finito $G$ tal que $|G|=p^k$ onde $p$ é primo é chamado de $p$-grupo finito. Por exemplo, $D_4$ é um 2-grupo finito. O teorema anterior diz que o centro de um $p$-grupo finito é não trivial.


:::{#exr-grp-p2}
Sejam $p$ um primo e $G$ um grupo tal que $|G|=p^2$. Mostre que $G$ é abeliano e que exatamente uma das seguintes afirmações é válida:

* $G$ é cíclico e $G\cong \Z_{p^2}$;
* $G=\left<a,b\right>$ onde $|a|=|b|=p$ e $ab=ba$. Neste caso $G\cong \Z_p\times \Z_p$. 
:::

## Primeiro encontro com grupos solúveis

:::{#def-solvable2}
Um grupo $G$ chama-se solúvel se $G$ possui uma cadeia de subgrupos
$$
G_0=1<G_1<\cdots<G_{k}<G_{k+1}=G
$$
tal que $G_i$ é normal em $G_{i+1}$ (para todo $i$) e cada quociente $G_{i+1}/G_{i}$ é abeliano.
:::

:::{#exm-solvable}
Os seguintes grupos são solúveis.

* Grupos abelianos.
* Grupos diedrais.
* $S_4$.
:::

Grupos solúveis são chamados assim, pois eles correspondem a equações polinomiais que são resolúveis por radicais. As equações polinomiais de grau 2, 3, 4 são resolúveis por radicais porque os grupos $S_2$, $S_3$, e $S_4$ são solúveis. Nós vamos ver na aula seguinte que $S_5$ não é um grupo solúvel e isso implica (de modo não trivial) que as equações polinomiais de grau 5 não são resolúveis por radicais.

:::{#cor-solvable}
Um $p$-grupo finito $G$ é solúvel.
:::

:::{.proof}
Seja $G$ um $p$-grupo. Ponha $Z_0=1$. Pelo @thm-center-pgp, temos que $Z_1=Z(G)\neq 1$. Se $Z(G)=G$, então $G$ é abeliano e é solúvel. Assuma que $Z(G)\neq G$ e considere o quociente $G/Z(G)$ (que é não trivial). Este grupo é um $p$-grupo também e $Z(G/Z(G))\neq 1$. Pelo @thm-corresp, temos que existe um subgrupo normal $Z_2\unlhd G$ tal que $Z(G)< Z_2$ e $Z(G/Z(G))=Z_2/Z_(G)$. Continuando deste jeito, assuma que foi determinado uma cadeia de subgrupos normais $Z_0<Z_1<Z_2<\cdots<Z_k$ tal que 
$$
Z(G/Z_{i-1})=Z_i/Z_{i-1}\quad\mbox{para todo}i\in\{1,\ldots,k\}
$$
Se $Z_k=G$, então não temos nada mais para fazer. Se $Z_k<G$, então defina $Z_{k+1}$ usando o @thm-corresp tal que $Z(G/Z_k)=Z_{k+1}/Z_k$. Como $G/Z_k$ é um $p$-grupo finito, temos por @thm-center-pgp que $Z_k<Z_{k+1}$.  
Como $G$ é finito, obtemos uma cadeia de subgrupos 
$$
Z_0=1<Z_1<\cdots<Z_m=G
$$
com a propriedade que $Z(G/Z_{i-1})=Z_{i}/Z_{i-1}$ para todo $i\in\{1,\ldots,m\}$. Como o centro de qualquer grupo é abeliano, obtemos que todo quociente $Z_i/Z_{i-1}$ é abeliano e $G$ é solúvel. 
:::

A cadeia construída na demonstração do @cor-solvable chama se *cadeia central superior* de $G$. O argumento na demonstração na verdade demonstra que um $p$-grupo finito $G$ é nilpotente (veja @sec-nilpotent) que é uma propriedade mais forte que ser solúvel.

Existem vários teoremas notáveis sobre grupos solúveis. Talvez o mais famoso é o [Teorema de Feit-Thompson](https://en.wikipedia.org/wiki/Feit%E2%80%93Thompson_theorem) (tambem conhecido como o Teorema da Ordem Ímpar) que é o seguinte.

:::{#thm-feit-thompson}
(Feit-Thompson, 1963)
Se $G$ é um grupo finito de ordem ímpar, então $G$ é solúvel.
:::

Este é um teorema profundo, a sua demonstração original  ocupa mais que 200 páginas na revista Pacific Journal of Mathematics.   [John Thompson](https://en.wikipedia.org/wiki/John_G._Thompson) recebeu Medalha de Fields em 1970 por sua contribuição à teoria dos grupos finitos. 