---
number-sections: true
lang: pt-BR

format: 
    pdf:
        number-sections: true
        include-in-header:
            text: |
                \setcounter{section}{2}
---

# Lista de Exercícios

## Grupos e Corpos, 2024/I {.unnumbered}

::: {.content-hidden}
$$
{{< include ../macros.tex >}}
$$
:::

:::{#exr-}
Demonstre os Teoremas 55.2 e 55.3 nas apostilas.
:::


:::{#exr-}
Verifique se $HK$ é um subgroupo de $G$ nos seguintes casos.

1. $G=S_4$, $H=\left<(1,2)\right>$, $K=\left<(2,3)\right>$; 
2. $G=S_4$, $H=\left<(1,2)\right>$, $K=\left<(3,4)\right>$;
3. $G=S_4$, $H=\left<(1,2)\right>$, $K=\left<(1,2,3,4)\right>$;
4. $G=S_4$, $H=\left<(1,3)(2,4)\right>$, $K=\left<(1,2,3,4)\right>$;
5. $G=S_4$, $H=\left<(1,2)(3,4),(1,3)(2,4)\right>$, $K=\left<(1,2,3,4)\right>$.
6. $G=S_4$, $H=\sym{\{1,2,3\}}$, $K=\sym{\{2,3,4\}}$. 
:::

:::{#exr-}
Sejam $\F$ um corpo e $U\leq \GL n\F$ o subgrupo das matrizes unitriangulares superiores (ou seja, triangulares com entradas $1$ na diagonal) e seja $D\leq \GL n\F$ o subgrupo das matrizes diagonais. Demonstre que $DU=UD$ e que $DU$ é um subgrupo de $\GL n\F$. 
:::

:::{#exr-}
Seja $\F$ um corpo e defina
$$
U=\left\{\begin{pmatrix} 1 & \alpha \\ 0 & 1\end{pmatrix}\mid \alpha\in\F \right\} \quad\mbox{e}\quad L=\left\{\begin{pmatrix} 1 & 0 \\ \alpha & 1\end{pmatrix}\mid \alpha\in\F  \right\}. 
$$
Decida se $UL$ é um subgrupo de $\GL 2\F$. 
:::

:::{#exr-}
O grupo $Q_8$ é o grupo dos quaternions 
$$
Q_8=\{1,-1,i,-i,j,-j,k,-k\}
$$
com a multiplicação definida com as seguintes regras:

a. $1$ é elemento neutro;
b. $-1$ se comporta como $-1$;
c. $ij=k$, $jk=i$, $ki=j$;
d. $ji=-k$, $kj=-i$, $ik=-j$. 

Tabela completa de multiplicação pode ser acessa na página groupprops.subwiki.org/wiki/Quaternion_group.

1. Determine a ordem de todo elemento de $Q_8$.
2. Determine todos os subgrupos de $Q_8$.
3. Mostre que todo subgrupo de $Q_8$ é normal mesmo que $Q_8$ não é abeliano.
4. Deduza dos pontos anteriores que $Q_8\not \cong D_8$. 
:::

:::{#exr-}
Verifique baseado no seu trabalho no exercício anterior que $Q_8\neq HK$ com $H,K\leq Q_8$ com $|H|=2$ e $|K|=4$. 
:::


:::{#exr-}
Determine o centro dos grupos $S_3$, $S_4$, $S_n$, $D_8$, $D_n$, $Q_8$, $\GL n\F$, $\SL n\F$. 
:::




