
---
title: "Automorfismos de corpos e o grupo de Galois"
number-sections: true
lang: pt-BR
---

## Automorfismos de corpos


Começamos por um exemplo motivador.

:::{#exm-sqroot-3}
Seja $\alpha=\sqrt[3]2$ e considere o corpo $\Q(\alpha)$. Pelo Critério de Einsenstein (@thm-eisenstein), o polinômio $x^3-2\in\Q[x]$ é irredutível, $\alpha$ é  raiz deste polinômio, e assim @lem-pol-min implica que $m_\alpha(x)=x^3-2$. Obtemos por @lem-Fa que 
$$
\Q(\alpha)\cong\Q[x]/(x^3-2).
$$
Em particular, $\Q(\alpha):\Q$ é uma extensão de grau $3$. 

Observe que o corpo $\Q(\alpha)$ não é corpo de decomposição de $m_\alpha(x)=x^3-2$! De fato, as raízes complexas de $x^3-2$ são 
$$
\alpha=\sqrt[3]2,\quad \alpha_1=\sqrt[3]2\xi_1,\quad \alpha_2=\sqrt[3]2\xi_2
$$
onde 
$$
\xi_1=\exp(2\pi i/3)\quad\mbox{e}\quad \xi_2=\exp(4\pi i/3)=\xi_1^2
$$
são as terceiras raízes não triviais da unidade. Por definição, o corpo de decomposição de $x^3-2$ é 
$$
\E=\Q\left(\sqrt[3]2,\sqrt[3]2\xi_1,\sqrt[3]2\xi_2\right)=\Q\left(\sqrt[3]2,\sqrt[3]2\xi_1,\sqrt[3]2\xi_1^2\right).
$$
Notando que $\xi_1=\alpha_1/\alpha\in\E$, obtemos que 
$$
\E=\Q\left(\sqrt[3]2,\xi_1\right)=\Q\left(\sqrt[3]2\right)(\xi_1).
$$
O polinômio minimal de $\xi_1$ sobre $\Q\left(\sqrt[3]2\right)$ é $x^2+x+1$, e assim 
$$
\E=\Q(\sqrt[3]2)[x]/(x^2+x+1).
$$
Temos que a extensão $\E:\Q$ é de grau $6$.
:::

:::{#def-field-aut}
Seja $\E$ um corpo. Lembre que um mapa $\varphi:\E\to\E$ bijetivo é dito automorfismo de $\E$ se $\varphi(x+y)=\varphi(x)+\varphi(y)$ e $\varphi(xy)=\varphi(x)\varphi(y)$ vale para todo $x,y\in\E$. O conjunto de automorfismos de $\E$ é um grupo com a operação de composição e este grupo é denotado por $\aut \E$. Se $\varphi\in\aut\E$, então definimos
$$
\fix\varphi=\{x\in \E\mid \varphi(x)=x\}.
$$
:::

:::{#exr-field-aut}
$\fix\varphi$ é um corpo, portanto $\E:\fix\varphi$ é uma extensão de corpos.
:::

:::{#exr-field-aut}
A conjugação complexa $\varphi: x+iy\mapsto x-iy$ é um automorfismo de  $\C$ e  $\fix\varphi = \R$.
:::

:::{#exm-field-aut}
Seja $p$ um primo e seja $f(x)\in\F_p[x]$ um polinômio irredutível de grau $d$. Defina $\E=\F_p[x]/(f(x))$ e note que $\E$ é um corpo de $q=p^d$ elementos. 
Pelo @exr-charp, o mapa $\varphi:\E\to\E$ definido como $\alpha\mapsto \alpha^p$ é um automorfismo. 
<!--É bem conhecido que $(\alpha+\beta)^p=\alpha^p+\beta^p$ e $(\alpha\beta)^p=\alpha^p\beta^p$, então precisamos verificar apenas que $\varphi$ é uma bijeção. Como $\E$ é um corpo finito, é suficiente verificar que $\varphi$ é injetivo. Isso é verdade, pois se $\alpha,\beta\in\E$ tais que $\varphi(\alpha)=\varphi(\beta)$, então
$$
0=\alpha^p-\beta^p=(\alpha-\beta)^p
$$
que implica que $\alpha-\beta=0$; ou seja $\alpha=\beta$. Temos então que $\varphi\in\aut\E$. 
-->
Além disso, $\fix\varphi$ é o conjunto de soluções da equação $x^p=x$ e esta equação tem precisamente $p$ soluções, nomeadamente, os elementos de $\F_p$. Logo $\fix\varphi=\F_p$. O automorfismo $\varphi$ é conhecido como o automorfismo de <a href="https://pt.wikipedia.org/wiki/Ferdinand_Georg_Frobenius">Frobenius</a>.
:::

## O grupo de Galois

:::{#def-galois-group}
Seja $\E:\F$ uma extensão de corpos. Defina
$$
\gal \E\F=\{\alpha\in\aut\E\mid \F\subseteq\fix\alpha\}.
$$
Em outras palavras, $\gal\E\F$ é o conjunto de automorfismos $\varphi$ de $\E$ tais que $\varphi(x)=x$ para todo $x\in\F$. É fácil verificar que $\gal\E\F$ é um subgrupo de $\aut\E$. Este subgrupo é chamado de grupo de <a href="https://pt.wikipedia.org/wiki/%C3%89variste_Galois">Galois</a> da extensão $\E:\F$ ou de grupo de Galois de $\E$ sobre $\F$.
:::

:::{#exr-gal-group}
Se $\varphi\in\gal\E\F$, então $\varphi$ é uma transformação $\F$-linear de $\E$.
:::

:::{#lem-aut-pol}
Seja $\E:\F$ uma extensão, $f(x)\in\F[x]$, $\alpha\in\E$ tal que $f(\alpha)=0$, e $\varphi\in\gal\E\F$. Então $f(\varphi(\alpha))=0$.
:::

:::{.proof}
Exercício. Revise a demonstração do fato bem conhecido que se um número complexo é raiz de um polinômio com coeficientes reais, então o conjugado complexo deste número será também raiz do mesmo polinômio (@lem-comp-conj-root).
:::

:::{#exm-gal}
Determinemos $\gal\C\R$. Seja $\varphi\in\gal\C\R$. Como $\varphi$ é uma transformação $\R$-linear, as imagens $\varphi(1)$ e $\varphi(i)$ determinam $\varphi$. Como $1\in\R$, temos que $\varphi(1)=1$. Note que $i$ é raiz do polinômio $x^2+1$, então $\varphi(i)$ será raiz do mesmo polinômio que implica que $\varphi(i)=\pm i$. Escolhendo $\varphi(i)=i$, obtemos que $\varphi=\mbox{id}_\C$, enquanto escolhendo $\varphi(i)=-i$, obtemos a conjugação complexa. Obtivemos então que $\gal\C\R$ é um grupo de ordem 2.
:::

:::{#exm-gal2}
Seja $\xi=\exp(2\pi i/3)$ (terceira raiz da unidade) e considere a extensão $\E=\Q(\xi)$ de $\Q$. Note que $\xi$ é raiz do polinômio $x^3-1=(x-1)(x^2+x+1)$ e que o polinômio $x^2+x+1$ é irredutível sobre $\Q$. Em particular, $m_\xi(x)=x^2+x+1$ e $\E$ é um espaço vetorial de dimensão $2$ sobre $\Q$. Além disso,
$$
\E=\left<1,\xi\right>_\Q=\{\alpha+\beta\xi\mid \alpha,\beta\in\Q\}
$$
e para determinar os automorfismos $\varphi\in\gal\E\Q$, é suficiente saber $\varphi(1)$ e $\varphi(\xi)$. Como no exemplo, anterior, $\varphi(1)=1$ e $\varphi(\xi)$ é raiz de $x^2+x+1$; consequentemente $\varphi(\xi)=\xi$ ou $\varphi(\xi)=\xi^2=\bar\xi$ (conjugado complexo). O primeiro caso dá o automorfismo identidade, enquanto o segundo dá o automorfismo
$$
\alpha+\beta\xi\mapsto \alpha+\beta\bar\xi \quad\mbox{onde}\quad\alpha,\beta\in\Q.
$$
(Na verdade, precisa verificar que isso é um automorfismo, mas isso é uma conta simples que o leitor pode fazer.) Então $|\gal\E\Q|=2$.
:::

:::{#exm-gal3}
Afirmamos que $\gal{\Q(\sqrt[3]2)}\Q$ é trivial. De fato, se $g\in\gal{\Q(\sqrt[3]2)}\Q$, então $g$ está determinado por $g(\sqrt[3]2)$. 
Por outro lado, $m_{\sqrt[3]2}(x)=x^3-2$ (@exm-sqroot-3), e @lem-aut-pol implica que $g(\sqrt[3]2)$ é raiz do polinômio $x^3-2$. Determinamos no @exm-sqroot-3 que as demais raízes deste polinômio não são reais, mas $\Q(\sqrt[3]2)\subseteq\R$. Portanto, $g(\sqrt[3]2)=\sqrt[3]2$ e $g=\mbox{id}_{\Q(\sqrt[3]2)}$. 
Logo $\gal{\Q(\sqrt[3]2)}\Q=1$. 
:::

:::{#exr-}
Seja $\E$ um corpo e sejam $\varphi_1,\ldots,\varphi_k\in\aut\E$. Assuma que $\alpha_1,\ldots,\alpha_k\in\E$ tais que $\alpha_1\varphi_1+\cdots+\alpha_k\varphi_k=0$. Mostre que $\alpha_1=\cdots=\alpha_k=0$. Em outras palavras, $\varphi_1,\ldots,\varphi_k$ são linearmente independentes no $\E$-espaço 
$$
\mbox{Func}(\E,\E)=\{f:\E\to\E \mbox{ é uma função}\}.
$$
:::

:::{#lem-gal-ff}
Seja $\E:\F$ uma extensão finita. Então $|\gal\E\F|\leq \dim_\F\E$.
:::

:::{.proof}
Os elementos de $\gal\E\F$ são elementos do $\E$-espaço $\mbox{Hom}_\F(\E,\E)$. Dada uma base $B$ de $\E$ sobre $\F$, $\mbox{Hom}_\F(\E,\E)$ é isomorfo como 
$\F$-espaço com 
$$
\mbox{Func}(B,\E)=\{f:B\to E\mid f\mbox{ é função}\}.
$$
Note que $\dim_\F\mbox{Func}(B,\E)=|X|=\dim_\F\E$. Portanto, $n+1$ elementos distintos $\varphi_1,\ldots,\varphi_{n+1}\in\gal\E\F$ 
são linearmente dependentes em $\mbox{Func}(B,\E)$ e eles são também linearmente dependentes em $\mbox{Hom}_\F(\E,\E)$. 
<!--são elementos distintos de $\gal\E\F$. Vamos obter uma contradição. Seja $e_1,\ldots,e_n$ uma base de $\E$ sobre $\F$. Considere o sistema de equações lineares sobre $\E$:
\begin{eqnarray*}
\varphi_1(e_1)x_1+\cdots+\varphi_{n+1}(e_1)x_{n+1}&=&0\\
&\vdots&\\
\varphi_1(e_n)x_1+\cdots+\varphi_{n+1}(e_n)x_{n+1}&=&0.
\end{eqnarray*}
Como temos $n$ equações para $n+1$ incógnitas, existe uma solução não trivial $(\alpha_1,\ldots,\alpha_{n+1})\in\E^{n+1}$ e obtemos usando esta solução que
$$
0=\alpha_1\varphi_1(e_i)+\cdots+\alpha_{n+1}\varphi_{n+1}(e_i)=(\alpha_1\varphi_1+\cdots+\alpha_{n+1}\varphi_{n+1})(e_i)
$$
para todo $i\in\{1,\ldots,n\}$.
Isso implica que $\alpha_1\varphi_1+\cdots,\alpha_{n+1}\varphi_{n+1}=0$, mas isso é impossível pelo exercício anterior.-->
:::

## Extensões normais

:::{#def-normal-extension}
Uma extensão $\E:\F$ algébrica é dita *normal* se para todo polinômio $f(x)\in\F[x]$, se $f(x)$ possui raiz em $\E$, então $f(x)$ decompõe-se em produto de polinômios do primeiro grau (ou seja, $\E$ contem um corpo de decomposição para $f(x)$).
:::

:::{#exm-normal-cuberoot-3}
Por exemplo, @exm-sqroot-3, a extensão $\Q(\sqrt[3]2):\Q$ não é normal.
:::

:::{#lem-normal-splitting}
Assuma que $\E:\F$ é uma extensão finita. Então ela é normal se e somente se $\E$ é o corpo de decomposição de algum polinômio $f(x)\in\F[x]$. 
:::
:::{.proof}
Assuma primeiro que $\E:\F$ é finita e é normal. Então $\E=\F(\alpha_1,\ldots,\alpha_k)$ com $\alpha_i\in\E$. Note que $m_{\alpha_i}(x)$ possui raiz em $\E$ (nomeadamente, $\alpha_i$) e ele decompõe-se em produto de polinômios do primeiro grau. Portanto, 
$$
f(x)=m_{\alpha_1}(x)\cdots m_{\alpha_k}(x)
$$
também decompõe-se em produto de polinômios do primeiro grau em $\E$. Por outro lado, $\E$ é gerado pelas raízes de $f(x)$, então $\E$ é corpo de decomposição de $f(x)$ sobre $\F$. 

Assuma agora que $\E$ é corpo de decomposição de algum polinômio $f(x)$. Seja $m(x)\in\F[x]$ um polinômio irredutível tal que 
$m(x)$ possui raiz $\alpha$ em $\E$. Seja $\K$ o corpo de decomposição de $m(x)$ sobre $\E$ e assuma que $\beta\in\K$ é uma outra raiz de $m(x)$. Basta provar que $\beta\in\E$. Considere as cadeias
$$
\E(\alpha):\F(\alpha):\F\quad\mbox{e}\quad \E(\beta):\F(\beta):\F.
$$
As extensões $\F(\alpha):\F$ e $\F(\beta):\F$ são isomorfas, pois $m_\alpha(x)=m_\beta(x)=m(x)\in\F[x]$. Além disso, 
$\E(\alpha)$ é corpo de decomposição de $f(x)$ sobre $\F(\alpha)$ e $\E(\beta)$ é corpo de decomposição de $f(x)$ sobre $\F(\beta)$. Portanto, 
as extensões $\E(\alpha):\F(\alpha)$ e $\E(\beta):\F(\beta)$ são também isomorfas. Em particular, 
$$
\dim_{\F}\E(\alpha)=\dim_\F \E(\beta).
$$
Por outro lado, $\alpha\in\E$ e $\E(\alpha)=\E$ e obtemos que 
$$
\dim_{\F}\E=\dim_\F \E(\beta).
$$
que (considerando que as dimensões são finitas) implica que $\E(\beta)=\E$; ou seja, $\beta\in\E$ com foi o objetivo deste argumento.
:::

## Extensões separáveis

:::{#def-sep-ext}
Seja $\F$ um corpo. Um polinômio $f(x)\in\F[x]$ chama-se *separável* se $f(x)$ não possui raízes múltiplas em nenhuma extensão de $\F$. 
Seja $\E:\F$ uma extensão algébrica. 
 Um elemento $\alpha\in\E$ é dita *separável*, se $m_\alpha(x)$ é um polinômio separável. 
 A extensão $\E:\F$ é *separável* se todo elemento $\alpha\in\E$ é separável.
:::

:::{#exr-sep-ext}
Seja $\E:\F$ uma extensão algébrica. Mostre que ela é separável se 

1. a caraterística de $\F$ (e de $\E$) é zero;
2. $\E$ é finito.
:::


:::{#thm-transitive}
Seja $\F$ um corpo. Assuma que $\E$ é um corpo de decomposição de um polinômio irredutível e separável $f(x)\in\F[x]$ com $\mbox{grau}\,f(x)=k$. Então $G=\gal\E\F$ permuta as raízes de $f(x)$ transitivamente e $G$ pode ser visto como um subgrupo transitivo de $S_k$. Em particular $k$ divide $|G|$.
:::

:::{.proof}
Sejam $\alpha,\beta\in\E$ duas raízes de $f(x)$. Note que $m_\alpha(x)=m_\beta(x)=f(x)$, e  $\F(\alpha)\cong\F(\beta)$. O @cor-simple implica que existe um isomorfismo $\psi:\F(\alpha)\to\F(\beta)$ tal que $\psi|_\F=\mbox{id}_\F$ e $\psi(\alpha)=\beta$. Agora observe que $f(x)$ pode ser visto como um polinômio sobre $\F(\alpha)$ e também sobre $\F(\beta)$ e $\E$ é corpo de decomposição de $f(x)$ sobre estes corpos. Pelo @thm-decompfield-unique, existe isomorfismo (na verdade um automorfismo) $\varphi:\E\to\E$ tal que $\varphi|_{\F(\alpha)}=\psi$. Ora, observe que $\varphi\in\gal\E\F$ tal que $\varphi(\alpha)=\beta$. Isso implica que $\gal\E\F$ permuta transitivamente as raízes de $f(x)$.

Para mostrar que $\gal\E\F$ pode ser considerado como um subgrupo de $S_k$, observe que $f(x)$ não possui raízes múltiplas em $\E$ (pois $f(x)$ é separável)$ e isso significa que $f(x)$ tem precisamente $k$ raízes, nomeadamente $\alpha_1,\ldots,\alpha_k$ mutualmente distintas. Se um elemento $\sigma$ de $\gal\E\F$ está no núcleo da ação em $\{ \alpha_1,\ldots,\alpha_k\}$, então $\sigma$ fixa todas as raízes. Mas como $\E$ é gerado por estas raízes (sendo corpo de decomposição), $\sigma=\mbox{id}_\E$. Então $\gal\E\F$ pode ser visto como um subgrupo do grupo simétrico do conjunto  $\{ \alpha_1,\ldots,\alpha_k\}$ e este grupo simétrico é claramente isomorfo a $S_k$. Finalmente, o fato que $k\mid |\gal\E\F|$ segue do @cor-orbit-stab.
:::



:::{#lem-simple-ext}
Seja $\E:\F$ uma extensão finita e separável. Então existe um elemento $\gamma\in\E$ tal que $\E=\F(\gamma)$. Ou seja, $\E:\F$ é uma extensão simples.
:::

:::{.proof}
Primeiro, se $\F$ é um corpo finito, então $\E$ (extensão finita de $\F$) é também finito e $\E=\F(\alpha)$ onde $\alpha\in\E$ é um gerador de $\E^*=\E\setminus\{0\}$ (@thm-field-cyclic). Ou seja, $\E$ é extensão simples e podemos assumir no resto do argumento que $\F$ é corpo infinito. 

É suficiente provar que para todo $\alpha,\beta\in\E$, existe $\gamma\in\E$ tal que $\F(\alpha,\beta)=\F(\gamma)$. Afirmamos que existe algum $c\in\F$ tal que $\F(\alpha,\beta)=\F(\alpha+c\beta)$. Seja $c\in\F$ tal que $\F(\alpha,\beta)\neq\F(\alpha+c\beta)$ e ponha $\K=\F(\alpha+c\beta)$. Por suposição, $\K\subset \F(\alpha,\beta)$ e $\alpha,\beta\not\in\K$. Seja $\E$ um corpo de decomposição de 
$m_\beta(x)$ sobre $\K$. Como $\E:\F$ é separável e o grau de $m_\beta(x)$ é maior que dois, existe $\beta'\in\E\setminus\{\beta\}$ tais que $m_\beta(\beta')=0$. Pelo @thm-transitive, existe $\sigma$ um automorfismo em $\gal{\E}{\K}$ tal que $\sigma(\beta)=\beta'$ e $\sigma(\alpha+c\beta)=\alpha+c\beta$. Portanto 
$$
\alpha+c\beta=\sigma(\alpha+c\beta)=\sigma(\alpha)+c\sigma(\beta)=\sigma(\alpha)+c\beta'.
$$ 
e
$$
c = \frac{\alpha-\sigma(\alpha)}{\beta'-\beta}.
$$
Como $\sigma\in \gal{\E}{\K}$, temos por @lem-gal-ff, temos um número finito de possibilidades para a expressão no lado direito da equação anterior. Isso quer dizer que temos apenas um número finito de possibilidades para $c\in\F$ tal que $\F(\alpha+c\beta)\neq \F(\alpha,\beta)$. Como $\F$ é infinito, existe $c\in\F$ tal que $\F(\alpha+c\beta)\neq \F(\alpha,\beta)$.
:::

## Extensões de Galois

:::{#def-ext-gal}
Uma extensão $\E:\F$ é dita *extensão de Galois* se ela é algébrica, normal e separável.
:::

:::{#thm-gg-fix-normal}
Seja $\E:\F$ uma extensão de Galois finita. Temos que 
$$
\fix{\gal\E\F}=\{\alpha\in\E\mid g(\alpha)=\alpha\mbox{ para todo }g\in\gal\E\F\}=\F.
$$
:::
:::{.proof}
Claramente $\F\subseteq \fix{\gal\E\F}$ então precisa provar a outra inclusão. Assuma que $\K=\fix{\gal\E\F}$ e seja $\alpha\in \E\setminus\F$. 
Vamos provar que $\alpha\not\in\K$. Seja $m_\alpha(x)$ o polinômio mínimo de $\alpha$ sobre $\F$ e note que o grau de $m_\alpha(x)$ é maior ou igual a $2$. Como a extensão 
$\E:\F$ é  normal e separável, $m_\alpha(x)$ é produto de fatores do primeiro grau em $\E$ e existe $\beta\in\E$ diferente de $\alpha$ tal que 
$m_\alpha(\beta)=0$. Ora, existe um isomorfismo $\psi:\F(\alpha)\to \F(\beta)$ tal que $\psi|_\F=\mbox{id}_\F$. O corpo $\E$, sendo uma extensão normal, é corpo de decomposição de algum polinômio $f(x)\in\F[x]$. Logo $\E$ é corpo de decomposição de $f(x)$ sobre os corpos isomorfos $\F(\alpha)$ e $\F(\beta)$. Por @thm-decompfield-unique, existe um isomorphismo $\varphi:\E\to \E$ tal que $\varphi|_{\F(\alpha)}=\psi$ e em particular $\varphi|_{\F}=\mbox{id}_\F$. Portanto $\varphi\in\gal\E\F$ tal que $\varphi(\alpha)=\beta\neq \alpha$. Isso implica que $\alpha\not\in\fix{\gal\E\F}$. 
:::

:::{#thm-gg-order}
Seja $\E:\F$ uma extensão de Galois finita. Então $|\gal\E\F|=\dim_\F\E$. 
:::
:::{.proof}
Seja $h=|\gal\E\F|$. Pelo  resultado anterior, $h\leq\dim_\F\E$, então basta provar a outra desigualdade. Pelo @lem-simple-ext, temos que $\E=\F(\alpha)$ com algum $\alpha\in\E$. Afirmamos que $\mbox{grau}\,m_\alpha(x)\leq h$ e isso vai implicar que $\dim_\F\E\leq h$. Note que é suficiente achar um polinômio $g(x)\in\F[x]$ de grau $h$ tal que $\alpha$ é raiz de $g(x)$. Assuma que $\{\sigma_1,\ldots,\sigma_h\}=\gal\E\F$ com $\sigma_1=1$ e considere o polinômio
$$
g(x)=(x-\sigma_1(\alpha))\cdots(x-\sigma_h(\alpha))=x^h+\beta_{h-1}x^{h-1}+\cdots+\beta_1h+\beta_0.
$$
Note que os coeficientes $\beta_i$ deste polinômio são elementos de $\fix{\gal\E\F}$. Portanto, @thm-gg-fix-normal implica que $\beta_i\in\F$, 
ou seja $g(x)\in\F[x]$. Além disso, $g(\alpha)=g(\sigma_1(\alpha))=0$ e a demonstração está pronta.
:::