---
title: "Produtos de grupos"
number-sections: true
lang: pt-BR
---

## Produto de subgrupos

:::{#def-group-prod}
Sejam $H,K\leq G$. Definimos o produto $HK\subseteq G$ como 
$$
HK=\{hk\mid h\in H,\ k\in K\}
$$
:::

:::{#exm-group-prod}
Assuma que $H=\left<(1,2)\right>$, $K=\left<(2,3)\right>$ são subgrupos de $S_3$. Então 
$$
HK=\{1,(1,2),(2,3),(1,3,2)\}
$$
Em particular $HK$ não é subgrupo de $S_3$. Além disso, 
$$
KH=\{1,(1,2),(2,3),(1,2,3)\}
$$
que também não é subgrupo de $G$ e observamos ainda que $HK\neq KH$. 

Agora, se $N=\left<(1,2,3)\right>$, então
$$
HN=S_3.
$$
:::

:::{#lem-prod-subg}
Sejam $H,K\leq G$. As segiuntes afirmações são verdadeiras.

1. $HK\leq G$ se e somente se $HK=KH$.
2. Se $H$ e $K$ são finitos, então $|HK|=|H||K|/|H\cap K|$.
3. Se $K$ é normal, então $HK=KH$ e $HK\leq G$.
:::

:::{.proof}
1. Assuma que $HK\leq G$. Isso implica que
$$
HKHK=HK
$$
e que 
$$
KH= H^{-1}HKK^{-1}=HK.
$$
Reciprocamente, se $HK=KH$, então 
$$
HKHK=HHKK=HK
$$
e $HK$ é fechado para multplicação. Similarmente,
$$
(HK)^{-1}=K^{-1}H^{-1}=KH=HK
$$
e $HK$ é fechado para inversos. Logo $HK\leq G$.

2. Defina $\varphi:H\times K\to HK$ por $\varphi(h,k)=hk$. Temos que $\varphi$ é sobrejetiva e vamos calcular a pré-imagem $\varphi^{-1}(\{hk\})$ de um elemento $hk\in HK$. Se $x\in H\cap K$, então $\varphi(hx,x^{-1}k)=hxx^{-1}k=hk=\varphi(h,k)$. Logo 
$$
\{(hx,x^{-1}k)\mid x\in H\cap K\}\subseteq \varphi^{-1}(\{hk\}).
$$
Ora, se $h_1\in H$ e $k_1\in K$ então
$$
\varphi(h,k)=\varphi(h_1,k_1)\bicond hk=h_1k_1\bicond h^{-1}h_1=kk_1^{-1}\in H\cap K.
$$
Escrevendo $x=h^{-1}h_1=kk_1^{-1}$, temos que 
$$
h_1=hx\quad \mbox{e}\quad k_1=x^{-1}k
$$
e assim $(h_1,k_1)\in\{(hx,x^{-1}k)\mid x\in H\cap K\}$. Temos então que 
$$
|\varphi^{-1}(\{hk\})|=|H\cap K|
$$ 
e obtemos por um fácil argumento de contagem que 
$$
|HK|=|\mbox{Im}(\varphi)|=|H||K|/|H\cap K|.
$$

3. Se $K$ é normal, então 
$$
hk=k^{h^{-1}}h\in KH
$$ 
e $HK\subseteq KH$ e argumento similar implica que $KH\subseteq HK$. Logo $HK=KH$ e item 1.\ implica que $HK\leq G$. 
:::

## O produto direto

:::{#def-dirprod}
Sejam $G$ e $H$ grupos. Defininimos o *produto direto* $G\times H$ como o grupo
$$ 
    G\times H=\{(g,h)\mid g\in G,\ h\in H\}
$$
com a operação definida na segiunte forma:
$$
(g_1,h_1)(g_2,h_2)=(g_1hg_2,h_1h_2).
$$ 
:::

:::{#lem-dirprod}
O conjunto $G\times H$ é um grupo com o produto definido na linha anterior. Além disso, pondo
$$
\bar G=\{(g,1)\mid g\in G\}\quad\mbox{e}\quad \bar H=\{(1,h)\mid h\in H\} 
$$ 
temos que 

- $\bar G,\bar H\unlhd G\times H$.
- $\bar G\bar H=G\times H$;
- $\bar G\cap\bar H=1$.
:::

:::{.proof}
Fácil, o leitor pode fazer.
:::

O produto direto acima definido é frequentamente chamado de produto direto externo. Simnilarmente a espaços vetoriais, existe uma versão interna do produto direto. 

:::{#lem-dirprod-inner}
Suponha que $G$ é um grupo e $N,M\unlhd G$ are subgrupos normais tais que 

- $NM=G$ e 
- $N\cap M=1$.

Então $G\cong N\times M$. 
:::

:::{.proof}
Primeiro mostremos que todo elemento $g\in G$ pode ser escrito unicamente como $g=nm$ com $n\in N$ e $m\in M$. Primeiro, como $NM=G$, a decomposição de $g$ existe. Ora, assuma que $g=n_1m_1=n_2m_2$ com $n_1,n_2\in N$ e $m_1,m_2\in M$. Isso implica que 
$$
n_2^{-1}n_1=m_2m_1^{-1}\in N\cap M.
$$
Como $N\cap M=1$, temos que $n_2^{-1}n_1=m_2m_1^{-1}=1$; ou seja, 
$n_1=n_2$ e $m_1=m_2$ e a unicidade está verificada.

Próximo, observe, para $n\in N$ e $m\in M$, que 
$$
[n,m]=n^{-1}m^{-1}nm=(m^{-1})^nm=n^{-1}n^m\in M\cap N=1.
$$
Portanto $[n,m]=1$ e em particular $N$ comuta com $M$. Isso implica que se $n\in N$ e $m\in M$, então $nm=mn$.

Agora defina $\psi:G\to N\times M$ como $\psi(g)=(n,m)$ onde $g=nm$ com $n\in N$ e $m\in M$. 
O mapa $\psi$ está bem definida pela unicidade da decomposição $g=mn$. 
Além disso, $\psi$ é um homomorfismo, pois se $g_1=n_1m_1,\ g_2=n_2m_2\in G$, então 
\begin{align*}
\psi(g_1g_2)&=\psi(n_1m_1n_2m_2)\psi(n_1n_2m_1m_2)\\&=(n_1n_2,m_1m_2)=
(n_1,m_1)(n_2,m_2)\\&=\psi(g_1)\psi(g_2).
\end{align*}
Se $g\in\ker\psi$, então $g=1\cdot 1=1$, logo $\psi$ é injetiva. Finalmente, se $n\in N$ e $m\in M$, então $\psi(nm)=(n,m)$ e $\psi$ é sobrejetiva. Portanto, $\psi$ é um isomorfismo e $G\cong N\times M$.
:::

:::{#def-dirprod-inner}
Definição. Se $G$, $N$ e $M$ são como no resultado anterior, escrevemos que $G=N\times M$ e dizemos que $G$ é *produto direto (interno) de $N$ e $M$*. 
:::

## Produto semidireto

:::{#def-semidir}
Definition. Para definir o *produto semidireto (interno)*, seja $G$ um grupo $H\leq G$ e $N\unlhd G$ tais que 

- $NH=G$ e
- $N\cap H=1$. 

Neste caso dizemos que $G$ é produto semidireto de $N$ e $H$ e escrevemos que $G=N\rtimes H$.
:::

Seja $G=N\rtimes H$ como na definição anterior. Assuma que $g_1,g_2\in G$ tal que $g_1=n_1h_1$ e $g_2=n_2h_2$ onde $n_1,n_2\in N$ e $h_1h_2\in H$. Note que estas expressões para $g_1$ e $g_2$ são únicas e isso pode ser verificado facilmente usando o argumento na demonstração anterior. Se $h\in H$, a normalidade de $N$ implica que o mapa 
$$
\psi_h:n\mapsto n^h=h^{-1}nh
$$ 
é um automorfismo de $N$ e a aplicação $h\mapsto \psi_h$ é um homomorfismo $\psi:H\to \operatorname{Aut}(N)$. Usando esta observação, obtemos que 
$$
g_1g_2=n_1h_1n_2h_2=(n_1n_2^{h_1^{-1}})(h_1h_2)=n_1(n_2(h_1^{-1}\psi))h_1h_2.
$$

Esta conta nos dá uma ideia como definir produto semidireto externo.

:::{#def-semidir-exter}
Sejam $N$ e $H$ grupos e assuma que está dado um homomorfismo $\psi:H\to \operatorname{Aut}(N)$. Defina o produto semidireto (relativo ao homomorfismo $\psi$) $N\rtimes_\psi H$ de $N$ e $H$ como o grupo sobre o conjunto $N\times H$ com a operação 
$$
(n_1,h_1)(n_2,h_2)=(n_1(n_2(h_1^{-1}\psi)),h_1h_2).
$$
:::

:::{#lem-semidir-exter}
O produto semidireto $N\rtimes_\psi H$ é um grupo com a multiplicação definida.
:::

:::{.proof}
Deixamos a demonstração para o leitor. Aqui só comentamos que o elemento neutro de $N\rtimes_\psi H$ é $(1,1)$ e que $(n,h)^{-1}=
((n^{-1})^h,h^{-1})$. 
:::