---
title: "O Lema de Iwasawa e a simplicadade de $PSL(n,q)$"
number-sections: true
lang: pt-BR
---

<div class="lemma">>(Iwasawa) 
Assuma que um grupo $G$ age primitivamente no conjunto $\Omega$ e um estabilizador $G_\alpha$ possui um subgrupo normal abeliano $A$ tal que $\left<A^g\mid g\in G\right>=G$. Suponha ainda que $G$ é perfeito (ou seja, $G'=G$). Denotando por $K$ o núcleo da ação de $G$ em $\Omega$, tem-se que $G/K$ é simples.
</div>

<div class="proof">Trocando $G$ por $G/K$, podemos assumir sem perder generalidade que $K=1$; ou seja $G$ é um subgrupo de $S(\Omega)$. Seja $N\neq 1$ um subgrupo normal de $G$. Como $G_\alpha$ é maximal, $G_\alpha N=G$ e todo elemento $x\in G$ pode ser escrito como $x=gn$ onde $g\in G_\alpha$ e $n\in N$. Em particular, $A^x=A^{(gn)}=A^n$. Logo $AN=G$ e $G/N=A/(A\cap N)$ é abeliano. Como $G'=G$, obtemos que $(G/N)'=G/N$, que implica que $N=G$.  Ou seja $G$ é simples.
</div>

<div class="theorem">Seja $n\geq 2$ e $\F$ um corpo (finito ou infinito) tal que $(n,|\F|)\neq (2,2), (2,3)$. Então o grupo $PSL(n,\F)$ é simples.
</div>


<div class="proof">Nós vamos mostrar que as condições do Lema de Iwasawa estão válidas.

Ação: Considere o grupo $G=SL(n,\F)$ com sua ação em $\Omega=\{\left<v\right>\mid v\in\F^n\setminus\{0\}\}$. Mostramos anteriormente na aula que $SL(n,\F)$ é 2-transitivo em $\Omega$ e portanto primitivo. O núcleo da ação é
$$
K=\{\lambda I\mid \lambda^n=1\}
$$
onde $I$ é a matriz identidade.  Então $SL(n,\F)/K\cong PSL(n,\F)$.

O estabilizador. Seja $\alpha=\left<(1,0,\ldots,0)\right>$. O estabilizador de $\alpha$ é composto por matrizes na forma
$$
\begin{pmatrix} a & 0\\ v & A\end{pmatrix}
$$
onde $a\in\F^*$, $v\in \F^{n-1}$, $0$ é o vetor nulo em $\F^{n-1}$ e $A$ é uma matriz $(n-1)\times (n-1)$ tal que $\det A=a^{-1}$.

Afirmação. As seguintes afirmações são verdadeiras:
\begin{align*}
\begin{pmatrix} 1 & 0\\ v & I\end{pmatrix}\begin{pmatrix} a & 0\\ 0 & A\end{pmatrix}=&\begin{pmatrix} a & 0\\ a v & A\end{pmatrix}\\
\begin{pmatrix} 1 & 0\\ v_1 & I\end{pmatrix}\begin{pmatrix} 1 & 0\\ v_2 & I\end{pmatrix}=&
\begin{pmatrix} 1 & 0\\ v_1+v_2 & I\end{pmatrix}\\
\begin{pmatrix} a_1 & 0\\ 0 & A_1\end{pmatrix}\begin{pmatrix} a_2 & 0\\ 0 & A_2\end{pmatrix}=&\begin{pmatrix} a_1a_2 & 0\\ 0 & A_1A_2\end{pmatrix}\\\begin{pmatrix} a & 0\\ 0 & A\end{pmatrix}\begin{pmatrix} 1 & 0\\ v & I\end{pmatrix}=&
\begin{pmatrix} 1 & 0\\ a^{-1}A v^t & I\end{pmatrix}\begin{pmatrix} a & 0\\ 0 & A\end{pmatrix}.
\end{align*}

Conseqência: Seja \begin{align*}
A=&\left\{\begin{pmatrix} 1 & 0\\ v & I\end{pmatrix}\mid v\in \F^{n-1}\right\}\\
H=&\left\{\begin{pmatrix} a & 0\\ 0 & A\end{pmatrix}\mid \det A=a^{-1}\right\}.
\end{align*}
Então $H\leq G_\alpha$, $A\unlhd G_\alpha$ e $A$ é um grupo abeliano.

$G$ é gerado pelos conjugados de $A$. Seja $X$ uma matriz $n\times n$ tal que $\det X=1$. É bem conhecido que, usando as seguintes operações, $X$ pode ser transformado a matriz identidade:

somar um múltiplo da $i$-ésima linha a $j$-ésima linha ($i\neq j$);
 somar um múltiplo da $i$-ésima coluna a $j$-ésima coluna ($i\neq j$).

Denote por $e_{i,j}$ a matriz que tem toda entrada zero exceto a entrada na posição $(i,j)$ que é 1. A operação 1. corresponde à multiplicação por $I+\lambda e_{ji}$ no lado esquerdo, enquanto a operação 2. corresponde à multiplicação no lado direito com $I+\lambda e_{ij}$ (onde $\lambda\in\F$). Logo $G=\left<I+\lambda e_{ij}\mid i\neq j,\ \lambda\in\F\right>$.

Denote por $e_1,\ldots,e_n$ a base canônica de $\F^n$. Seja $T=I+\lambda e_{ij}$. Note que $e_kT=e_k$ se $k\neq i$, enquanto $e_iT=e_i+\lambda e_j$. Seja $X\in SL(n,\F)$ tal que as imagens de $e_k$ com $k\not\in\{i,j\}$ são $e_3,\ldots,e_n$, respetivamente, enquanto $e_i X=e_2$ e $e_jX=\pm e_1$. Neste caso,
\begin{align*}
e_2X^{-1}TX=&e_iTX=(e_i+\lambda e_j)X=e_2\pm \lambda e_1\mbox{ e};\\
e_m X^{-1}TX=&e_{m'}TX=e_{m'}X=e_m\mbox{ se $m\neq 2$}
\end{align*}
onde $m'$ é tal que $e_{m'}X=e_m$. Obtemos então que $T^X\in A$; ou seja, $T\in A^{X^{-1}}$. Como o conjunto de transformações na forma $I+\lambda e_{ij}$ com $i\neq j$ geram $G$, obtemos que $G=\left<A^g\mid g\in G\right>$.

$G'=G$. Pelo argumento no parágrafo anterior, é suficiente provar que o elemento $I+\lambda e_{1n}$ pode ser escrito como um comutador.  Se $n\geq 3$, então
$$
I+\lambda e_{1n}=[I+\lambda e_{12},I+e_{2n}].
$$
Se $n=2$, e $|\F|\geq 4$, então sejam $x\in \F$ e $a\in\F^*$ tais que $a\neq \pm 1$ e $\lambda = x(a^{-2}-1)$. Então
$$
I+\lambda e_{12}=\left[\begin{pmatrix} 1 & x \\ 0 & 1 \end{pmatrix},\begin{pmatrix} a & 0 \\ 0 & a^{-1} \end{pmatrix}\right].
$$
</div>