
---
number-sections: true
lang: pt-BR
title: "Anéis e corpos"
---

## Definições

:::{#def-ring}
Seja $R$ um conjunto não vazio equipado com duas operações $+$ (adição) e $\cdot$ (multiplicação) que satisfazem as seguintes propriedades para todo $a,b,c\in R$:


- $(a+b)+c=a+(b+c)$;
- $a+b=b+a$;
- existe elemento neutro $0$ para a adição: $0+a=a+0=a$;
- $a\in R$ possui negativo; ou seja existe $-a\in R$ tal que $a+(-a)=0$;
- $(ab)c=a(bc)$;
- $ab=ba$;
- existe elemento neutro $1$ para multiplicação: $1\cdot a=a\cdot 1=a$;
- $a(b+c)=ab+ac$.

A estrutura $(R,+,\cdot)$ chama-se <em>anel comutativo com identidade</em>. Como nesta parte da disciplina nós não vamos tratar anéis que não são comutativos com identidade, nós vamos chamar a estrutura $R$ simplesmente <em>anel</em>.
:::

Em particular, se $(R,+,\cdot)$ é um anel então $(R,+)$ é  um grupo abeliano.

:::{#def-field}
Um anel $R$ com pelo menos dois elementos é dito <em>corpo, </em>se, além das propriedades 1-8 acima, todo elemento $a\in R\setminus\{0\}$ possui inverso multiplicativo. Ou seja, se $a\in R\setminus\{0\}$, então existe $a^{-1}\in R$ tal que $aa^{-1}=1$. Isto significa, que se $(R,+,\cdot)$ é um corpo, então $(R,+)$ e $(R\setminus\{0\},\cdot)$ são grupos abelianos.
:::

:::{#exr-unique}
Mostre em um anel $R$ que os elementos $0$ e $1$ são únicos. Mostre, para $a\in R$ que $-a$ e (caso exista) $a^{-1}$ são únicos.
:::

:::{#exm-ring}
Os principais exemplos de anéis são $\mathbb Z$, $\mathbb Z_n$ e $\F[x]$ (com $\F$ sendo um corpo). Os principais exemplos de corpos são $\mathbb Z_p$ (com $p$ primo), $\mathbb Q$, $\mathbb R$, e $\mathbb C$.
:::


## Ideais

:::{#def-ideal}
Um conjunto não vazio $I$ de um anel é dito ideal se

- $a\pm b\in I$ para todo $a,b\in I$ (em outras palavras $I$ é um subgrupo de $(R,+)$);
- $ab\in I$ para todo $a\in I$ e $b\in R$.
:::

:::{#exm-ideal}
Se $R$ é um anel e $a\in R$, então
$$
(a)=Ra=\{ba\mid b\in R\}
$$
é um ideal de $R$. Um ideal desta forma chama-se<em> ideal principal</em>.
:::


:::{#exr-ideal}
Usando a notação do parágrafo anterior, mostre que $(a)=R$ se e somente se existe $a^{-1}\in R$.
:::

:::{#def-ring-quot}
Se $R$ é um anel e $I$ é um ideal, então o quociente
$$
R/I=\{I+r\mid r\in R\}
$$
pode ser considerado como um anel com as operações
$$
(I+a)+(I+b)=I+(a+b),\quad (I+a)(I+b)=I+ab.
$$
:::

:::{#exm-ideal}
Caso $R=\mathbb Z$ e $n\in \mathbb Z$, o ideal principal $(n)$ é o conjunto $\{bn\mid b\in\mathbb Z\}$ dos múltiplos de $n$. Se $n\geq 2$, então o quociente $\mathbb Z/(n)$ é o anel $\mathbb Z_n$ das classes residuais.
:::

## Anéis de polinômios

Nós vamos trabalhar principalmente com anéis de polinômios e com seus ideais. Eu assumo que vocês têm familiaridade com alguns conceitos relacionados com polinômios que estudamos na disciplina Fundamentos de Álgebra:


- conceito de polinômio sobre um corpo (@def-pol);
- grau de um polinômio (@def-pol);
- polinômio mônico (@def-pol);
- divisibilidade entre polinômios (@def-div-pols);
- o MDC de dois polinômios (@def-mdc-pol);
- polinômios coprimos (primos entre si) (@def-coprime-pol);
- o Algoritmo de Euclides para polinômios (@sec-euclid-pols);
- Polinômios irredutíveis (@def-irred);
- a caraterização de polinômios irredutíveis sobre $\mathbb C$ e $\mathbb R$ (@thm-irred-R-C);
- O critério de Eisenstein para irredutibilidade de um polinômio sobre $\mathbb Q$ (@thm-eisenstein).

Seja $\F$ um corpo e considere o anel $R=\F[x]$ de polinômios sobre $\F$. Seja $f(x)$ um polinômio de $\F[x]$ com grau maior ou igual a $1$. Pelo exemplo acima,  o conjunto
$$
(f(x))=\F[x]f(x)=\{q(x)f(x)\mid q(x)\in \F[x]\}
$$
é um ideal de $\F[x]$. Se $g(x)\in \F[x]$ então denote por $\overline{g(x)}$ o elemento $(f(x))+g(x)$ do quociente $\F[x]/(f(x))$. Usando o Teorema de Divisão de Euclides para polinômios, pode-se escrever que
$$
g(x)=q(x)f(x)+r(x)\quad \mbox{onde}\quad r(x)=0\mbox{ ou }\mbox{grau}\,r(x)<\mbox{grau}\,f(x),
$$
mas isso implica que
$$
\overline{r(x)}=\overline{g(x)-q(x)f(x)}=\overline{g(x)}-\overline{q(x)}\overline{f(x)}=
\overline{g(x)}.
$$
Ou seja, $\overline{g(x)}$ e $\overline{r(x)}$ são elementos iguais em $\F[x]/(f(x))$. Além disso, se $\mbox{grau}\,g(x)<\mbox{grau}\,f(x)$, então a penúltima equação destacada implica que $g(x)=r(x)$. Estas considerações demonstram o seguinte resultado.

:::{#lem-euclid-quot}
Usando a notação acima, todo elemento de $\F[x]/(f(x))$ pode ser escrito unicamente como $\overline{g(x)}$ onde $g(x)\in\F[x]$ com $g(x)=0$ ou $\mbox{grau}\,g(x)<\mbox{grau}\,f(x)$. Em particular, pondo $k=\mbox{grau}\,f(x)$,
$$
\F[x]/(f(x))=\{\overline{g(x)}\mid g(x)=0\mbox{ ou grau}\,g(x)<k\}=
\{\alpha_0+\alpha_1\overline x+\cdots+\alpha_{k-1}\overline x^{k-1}\mid \alpha_0,\ldots,\alpha_{k-1}\in\F\}.
$$
e $\F[x]/(f(x))$ é um espaço vetorial de dimensão $k$ sobre $\F$.
:::

:::{#thm-quot}
Se $I\neq\{0\}$ é um ideal de $\F[x]$ então existe um único polinômio mônico $f(x)\in I$ tal que
$$
I=(f(x))=\F[x]f(x)=\{q(x)f(x)\mid q(x)\in \F[x]\}.
$$
Consequentemente, $I$ é principal.
Além disso as seguintes são equivalentes:

- $I$ é um ideal maximal;
- $f(x)$ é um polinômio irredutível;
- $\F[x]/I$ é um corpo.
:::

:::{.proof}
Seja $I\subseteq \F[x]$ um ideal não nulo e seja $f(x)$ um polinômio não nulo em $I$ de grau minimal. Multiplicando $f(x)$ com um escalar, podemos assumir que $f(x)$ é um polinômio mônico. Claramente, $(f(x))\subseteq I$. Seja $g(x)\in I$ um polinômio arbitrário. Pelo Teorema de Divisão de Euclides para polinômios, existem $q(x),r(x)\in\F[x]$ únicos tais que
$$
g(x)=f(x)q(x)+r(x)\quad \mbox{onde}\quad r(x)=0\mbox{ ou }\mbox{grau}\,r(x)<\mbox{grau}\,f(x).
$$
Como $f(x),g(x)\in I$, vimos que $r(x)\in I$. Pela minimalidade de $\mbox{grau}\,f(x)$ entre os polinômios não nulos de $I$, segue obrigatoriamente que $r(x)=0$. Ou seja $g(x)=f(x)q(x)$. Isto mostra que $I\subseteq (f(x))$ e portanto $I=(f(x))$.

Para a primeira afirmação, precisamos mostrar ainda que $f(x)$ é único. Suponha que existem $f_1(x),f_2(x)\in I$ ambos mônicos tais que $I=(f_1(x))=(f_2(x))$. Neste caso $f_1(x)$ é um múltiplo de $f_2(x)$ e $f_2(x)$ é um múltiplo de $f_1(x)$. Como os dois destes polinômios são mônicos, segue que $f_1(x)=f_2(x)$. Então o polinômio $f(x)$ no lema é único.

Mostremos agora que as três afirmações no lema são equivalentes. Assuma que $I$ é maximal. Como $I\neq\F[x]$, temos que $f(x)$ não é invertível; ou seja $\mbox{grau}\,f(x)\geq 1$. Escreva $f(x)=g(x)h(x)$ com $g(x),h(x)\in\F[x]$ e $\mbox{grau}\,g(x)<\mbox{grau}\,f(x)$. Observe que $I=(f(x))\subseteq (g(x))$. Pela maximalidade de $I=(f(x))$, tem-se que $(g(x))=\F[x]$ ou $(g(x))=I$. A segunda opção não é possível pois $f(x)$ é um polinômio de menor grau em $I$, enquanto na primeira opção $g(x)$ é constante. Obtivemos que $f(x)$ é irredutível.

Assuma agora que $f(x)$ é irredutível. Seja $g(x)\in \F[x]$ tal que $\overline{g(x)}=g(x)+I\in \F[x]/I$ é um elemento não nulo; ou seja $g(x)\not\in I$, ou, equivalentemente, $f(x)\nmid g(x)$. Como $f(x)$ é irredutível, temos que $\mbox{mdc}(f(x),g(x))=1$ e existem (pelo Algoritmo de Euclides) $u(x),v(x)\in\F[x]$ tais que
$$
u(x)f(x)+v(x)g(x)=1.
$$
Passando para o quociente, isto quer dizer que
$$
\overline 1=\overline{u(x)f(x)+v(x)g(x)}=\overline{u(x)}\overline{f(x)}+\overline{v(x)}\overline{g(x)}=
\overline{v(x)}\overline{g(x)}.
$$
Ou seja, $\overline{v(x)}$ é inverso de $\overline{g(x)}$. Como $g(x)$ foi escolhido arbitrariamente, sujeito à condição que $\overline{g(x)}\neq 0$, temos que todo elemento não nulo de $\F[x]/I$ possui inverso e que $\F[x]/I$ é um corpo.

Assuma agora que $\F[x]/I$ é um corpo e seja $J$ um ideal de $\F[x]$ tal que $I\subset J$. Seja $g(x)\in J\setminus I$. Como $\F[x]/I$ é um corpo, $\overline{g(x)}$ possui inverso em $\F[x]/I$; ou seja, existe $h(x)\in \F[x]$ tal que $\overline{g(x)}\overline{h(x)}=\overline 1$, mas isto é equivalente ao afirmar que $g(x)h(x)=1+q(x)f(x)$. Como $g(x),f(x)\in J$, temos que $1\in J$ e isto implica que $J=\F[x]$ e que $I$ é um ideal maximal.
:::

:::{#exm-quot-pol}
Seja $\F=\mathbb R$ e considere o polinômio $f(x)=x^2+1\in\mathbb R[x]$. Como $f(x)$ é um polinômio irredutível (porque?), temos que o quociente $\mathbb K=\mathbb R[x]/(x^2+1)$ é um corpo. Pelas considerações acima,
$$
\mathbb K=\{\alpha_0+\alpha_1\overline x\mid \alpha_0,\alpha_1\in \mathbb R\}.
$$
Além disso, temos que $\overline x^2+1=0$ que implica que $\overline x^2=-1$. Escrevendo $\overline x=i$, temos que
$$
\mathbb K=\{\alpha_0+\alpha_1 i\mid \alpha_0,\alpha_1\in\mathbb R\}\quad\mbox{onde}\quad i^2=-1.
$$
Vemos então que o corpo quociente $\mathbb K$ é nada mais que o corpo bem conhecido $\mathbb C$. Obtivemos então que $\mathbb C=\mathbb R[x]/(x^2+1)$.
:::