---
title: "Grupos solúveis"
number-sections: true
lang: pt-BR
---


## Comutadores e o subgrupo derivado

:::{#def-commutator}
Seja $G$ um grupo, $g,h\in G$. O *comutador* $[g,h]$ de $g$ e $h$ é definido como 
$$
[g,h]=g^{-1}h^{-1}gh=(h^{-1})^gh=g^{-1}g^h.
$$
:::

Note que $[g,h]=1$ se e somente se $gh=hg$; ou seja, $g$ e $h$ comutam. 


:::{#def-commutator-sg}
Seja $G$ um grupo. O *subgrupo derivado* $G'$ está definida como 
$$
G'=\left<[g,h]\mid g,h\in G\right>.
$$
:::

Em outras palavras, o subgrupo derivado $G'$ é um subgrupo gerado por todos os comutadores em $G$. Note que o conjunto dos comutadores geralmente não é fechado para multiplicação e assim ele não é um subgrupo de $G$.

Note também que $G'=1$ se e somente se $G$ é abeliano.

<!--:::{#thm-comm-sg}
Seja $G$ um grupo. As seguintes afirmações são verdadeiras.

- $G'\unlhd G$;
- $G/G'$ é um grupo abeliano;
- se $N\unlhd G$ tal que $G/N$ é abeliano, então $G'\leq N$.  

A terceira afirmação diz que $G'$ é o menor subgrupo normal de $G$ com quociente abeliano.
:::

:::{.proof}
Primeiro, se $g,h,x\in G$, então
$$
[g^x,h^x]=[x^{-1}gx,x^{-1}hx]=x^{-1}g^{-1}xx^{-1}h^{-1}xx^{-1}gxx^{-1}hx=x^{-1}g^{-1}h^{-1}ghx=[g,h]^x.
$$
O seja, um conjugado de um comutador é comutador. Como o subgrupo derivado contém produtos de comutadores, ele é normal.

Sejam $g,h\in G$. Temos que 
$$
[gG',hG']=(g^{-1}G')(h^{-1}G')(gG')(hG')=[g,h]G'=G'.
$$
Logo, $G/G'$ é abeliano.

Ora seja $N\unlhd G$ tal que $G/N$ é abeliano e seja $g,h\in G$. Temos que 
$$
1=[gN,hN]=[g,h]N.
$$
Ou seja, $[g,h]\in N$. Como $G'$ é gerado por elementos na forma $[g,h]$, temos que $G'\leq N$. 
:::
-->

## Subgrupos caraterísticos

:::{#def-charsub}
Um subgroupo $H\leq G$ é dito *caraterístico*, se $H$ é invariente por automorfismos de $G$. 
:::

Um subgrupo caraterístico precisa ser invariante por automorfismos e, em particular, por automorfismos internos (veja @def-inner-aut). Ser invariante por automorfismos internos é ser invariante por conjugação (veja @sec-conjugação) e assim obtemos o seguinte resultado.

:::{#lem-char-norm}
Um subgrupo caraterístico é normal.
:::

:::{#lem-comm-HK}
Seja $G$ um grupo e sejam $H$, $K$ subgroupos de $G$ tal que $K\leq H\leq G$.

* Se $K$ é caraterístico em $H$ e $H$ é caraterístico em $G$, então $K$ é caraterístico em $G$.
* Se $K$ é caraterístico em $H$ e $H$ é normal em $G$, então $K$ é normal em $G$.
:::

:::{.proof}
Exercício.
:::

:::{#lem-comutator-abeliano}
$G'$ é um subgrupo caraterístico de $G$. Em particular, $G'$ é um subgrupo normal. Além disso, $G/G'$ é um grupo abeliano e se $N\unlhd G$ tal que $G/N$ é abeliano, então $G'\leq N$. (Pode-se dizer que $G'$ é o menor subgrupo normal de $G$ com quociente abeliano.)
:::

:::{.proof}
Se $\alpha\in\aut G$ e $x,y\in G$, então 
$$
[x,y]^\alpha=(x^{-1}y^{-1}xy)^\alpha=(x^\alpha)^{-1}(y^\alpha)^{-1}x^\alpha y^\alpha=[x^\alpha,y^\alpha];
$$
ou seja, $[x,y]^\alpha$ é um comutador de $G$. Como $\alpha$ induz uma permutação dos elementos de $G$, temos que $\alpha$ permuta os comutadores de $G$ e assim $(G')^\alpha$ é gerado pelos mesmos comutadores. Portanto $(G')^\alpha=G'$ e $G'$ é um subgrupo caraterístico.

Sejam $g,h\in G$. Temos que 
$$
[gG',hG']=(g^{-1}G')(h^{-1}G')(gG')(hG')=[g,h]G'=G'.
$$
Logo, $G/G'$ é abeliano.

Ora seja $N\unlhd G$ tal que $G/N$ é abeliano e seja $g,h\in G$. Temos que 
$$
1=[gN,hN]=[g,h]N.
$$
Ou seja, $[g,h]\in N$. Como $G'$ é gerado por elementos na forma $[g,h]$, temos que $G'\leq N$. 
:::

## Série derivada

:::{#def-sgs-derivied}
Podemos definir recursivamente $G''=(G')'$, $G'''=(G'')'$. Formalmente, definimos $G^{(0)}=G$ e para $k\geq 0$, definimos $G^{(k+1)}=(G^k)'$. Obtemos uma série 
$$
G\geq G'\geq G''\geq G^{(3)}\geq \cdots 
$$
chamada de *série derivada* ou *série comutador* de $G$. Os termos desta série são subgrupos caraterísticos, em particular, eles são normais em $G$.
:::

:::{#def-normal-series}
Seja $G$ um grupo e assuma que 
$$
G=G_0\geq G_1\geq G_2\geq \cdots.
$$
é uma série não crescente de subgrupos. 

1. A série é chamada de *normal* se $G_i\unlhd G$ para todo $i\geq 0$.
2. A série é chamada de *subnormal* se $G_i\unlhd G_{i-1}$ para todo $i\geq 1$.
Note que uma série normal é subnormal.
:::

:::{#lem-derived-series}
Seja $G$ um grupo e seja $G_0=G\geq\cdots\geq G_k>\cdots$ uma série subnormal de subgrupos tal que $G_i/G_{i+1}$ é abeliano para todo $i$. Então $G^{(i)}\leq G_i$ vale para todo $i\geq 0$.
:::

:::{.proof}
A afirmação é trivialmente verdadeira para $i=0$. Assuma que $G^{(i)}\leq G_i$. Como $G_i/G_{i+1}$ é abeliano, temos que $G_i'\leq G_{i+1}$. Logo
$$
G^{(i+1)}=(G^{(i)})'\leq G_i'\leq G_{i+1}.
$$
Então a afirmação é verdadeira para $i+1$ e segue por indução que ela é verdadeira para todo $i$.
:::

:::{#thm-solvable}
As seguintes são equivalentes para um grupo $G$.

* Existe uma série normal $G_0=G>\cdots >G_k=1$ com quocientes abelianos.
* Existe  uma série subnormal $G_0=G>\cdots> G_k=1$ com quocientes abelianos.
* Existe $k$ tal que $G^{(k)}=1$.
:::

:::{.proof}
1.$\cond$ 2.: Cada série normal é também subnormal.

2.$\cond$ 3.: @lem-derived-series.

3.$\cond$ 1. A série $G^{(k)}$ é normal.
:::

## Grupos solúveis revisitados

Na @sec-soluble já estudamos grupos solúveis. Na definição @def-solvable2, definimos um grupo solúvel como um grupo que satisfaz item 1. do @thm-solvable. Agora, aprendemos que os pontos 2. e 3. são equivalentes ao ponto 1. e podem também ser usadas para definir grupos solúveis. 



:::{#def-elabel}
Um grupo abeliano finito é dito grupo abeliano elementar,, se existe um primo $p$, tal que $x^p=1$ para todo $x\in G$. 
:::

Pelo Teorema Fundamental dos Grupos Finitos Abelianos (@thm-fund-abelian-groups), temos que $G$ é grupo abeliano elementar se e somente se $G=\Z_p\times\cdots \times \Z_p$ com algum primo $p$. Em particular, um grupo abeliano elementar pode ser considerado como um espaço vetorial sobre o corpo $\mathbb F_p$.


:::{#thm-solvable2}
As seguintes afirmações são válidas para um grupo $G$.

1. Se $\varphi:G\rightarrow K$ é um homomorfismo, então
$$
\varphi(G^{(i)})=\varphi(G)^{(i)}
$$
para todo $i\geq 0$.
2. Se $N\unlhd G$ e $Q=G/N$, então $Q^{(i)}= G^{(i)}N/N$.
3. Se $G$ é solúvel e $H\leq G$, $N\unlhd G$, então $H$ e $G/N$ são solúveis.
4. Se $N\unlhd G$, tal que $N$ e $G/N$ são solúveis, então $G$ é solúvel.
5. Se $G$ é um p-grupo finito, então $G$ é solúvel.
<!--* Se $G$ é finito, então $G$ é solúvel se e somente se os fatores de composição de $G$ são todos grupos cíclicos de ordem prima.-->
<!--6. Se $G$ é finito e solúvel e $N$ é um subgrupo minimal normal de $G$, então $N$ é abeliano elementar.-->
:::

:::{.proof}
1. Indução por $i$. Se $i=0$, então não há nada para provar. Assuma que a afirmação é verdadeira para $i\geq 0$.
O subgrupo $G^{(i+1)}$ é gerado por elementos da forma $[x,y]$ onde $x,y\in G^{(i)}$. Como
$$
\varphi([x,y])=[\varphi(x),\varphi(y)]\in \varphi(G^{(i)})'=(\varphi(G)^{(i)})'=\varphi(G)^{(i+1)},
$$
obtemos que $\varphi(G^{(i+1)})\leq \varphi(G)^{(i+1)}$.
Assuma agora que $[u,v]\in\varphi(G)^{(i+1)}$ com $u,v\in \varphi(G)^{(i)}$. Temos que existem $x,y\in G^{(i)}$ tal que $\varphi(x)=u$ e $\varphi(y)=v$. Logo
$$
[u,v]=\varphi([x,y])\in \varphi(G^{(i+1)})
$$
e $\varphi(G)^{(i+1)}\leq \varphi(G^{(i+1)})$.  Temos egualdade.
2. Seja $\varphi:G\rightarrow G/N$ o homomorfismo natural. Por parte (1), tem-se que
$$
Q^{(i)}=\varphi(G)^{(i)}=\varphi(G^{(i)})=G^{(i)}N/N.
$$
3. Assuma que $G$ é solúvel e assuma que $G^{(k)}=1$ para algum $k$. Pode-se verificar por indução que $H^{(i)}\leq G^{(i)}$ vale para todo $i\geq 0$. Portanto, $H^{(k)}=1$ e segue que $H$ é solúvel. Seja agora $N\unlhd G$ e assuma que $Q=G/N$. Por parte (2), temos que $(G/N)^{(k)}= G^{(k)}N/N=1$. Logo $(G/N)^k=1$ e portanto $G/N$ é solúvel.

4. Assuma que $N\unlhd G$ e $G/N$ são solúveis. Seja $Q=G/N$. Existe $m$ tal que $Q^{(m)}=1$. Isto quer dizer que $G^{(m)}\leq N$. Existe $l$ tal que $N^{(l)}=1$. Afirmamos que $G^{(m+l)}=1$. De fato,
$$
G^{(m+l)}=(G^{(m)})^{(l)}\leq N^{(l)}=1.
$$
Logo, $G$ é solúvel.

5. Já foi provado em @cor-solvable.

<!--6. Seja $N$ um subgrupo minimal normal de $G$. Como $N'$ é um subgrupo caraterístico em $N$, temos que $N'$ é normal de $G$, que implica, pela minimalidade de $N$, que $N'=1$. Logo $N$ é um grupo abeliano finito. Pelo Teorema Fundamental dos Grupos Abelianos Finitos, $N=N_{p_1}\times \cdots \times N_{p_k}$ onde $N_{p_i}$ é o $p_i$-subgrupo de Sylow de $N$. Cada $N_{p_i}$ é caraterístico em $N$, e normal em $G$. Pela minimalidade de $N$, temos que $N=N_{p_1}$; isto é, $N$ é um $p$-grupo abeliano. Finalmente, observe que
$$
N^p=\{x^p\mid x\in N\}
$$
é um subgrupo caraterístico em $N$ que implica que $N^p=1$; ou seja $N$ é abeliano elementar.-->
:::