---
title: "Exemplos de relações de equivalência"
number-sections: true 
lang: pt
---


## Classes residuais

Como nós já discutimos, dizemos que $a$ divide $b$ ($a$ e $b$ são números inteiros) se $b=qa$ com algum $q$ inteiro. Neste caso pode-se dizer também que $a$ é um divisor de $b$ ou que $b$ é múltiplo de $a$. Se $a$ divide $b$, então escrevemos $a\mid b$. 

Defina a seguinte relação sobre $\Z$:
$$
a\equiv_3 b\quad\bicond\quad b-a=3k\mbox{ com algum }k\in\Z.
$$
Pode também dizer que $a\equiv_3 b$ se e somente se $3\mid b-a$. 

:::{#lem-resid}
A relação $\equiv_3$ é uma relação de equivalência sobre $\Z$.
:::

:::{.proof}
Por definição, @def-eq-rel, precisamos verificar que a relação é reflexiva, simétrica, e transitiva. 

**Reflexividade:** Se $a\in\Z$, então $a-a=0=3\cdot 0$. Logo $a\equiv_3 a$.

**Simetria:** Sejam $a,b\in\Z$ tal que $a\equiv_3 b$. Então $b-a=3k$ e assim $a-b=-(b-a)=-3k=3(-k)$. 

**Transitividade:** Sejam $a,b,c\in\Z$ tais que $a\equiv_3 b$ e $b\equiv_3 c$; ou seja $b-a=3k_1$ e $c-b=3k_2$. Neste caso 
$$
c-a=(b-a)+(c-b)=3k_1+3k_2=3(k_1+k_2).
$$
Pronto.
:::

:::{#exm-resid}
Por exemplo $2\equiv_3 5$, pois $5-2=3=3\cdot 1$. Temos também que $1\equiv_3 -2$, pois $-2-1=-3=3\cdot (-1)$. Por outro lado, $1\not\equiv_3 -1$, pois $-1-1=-2\neq 3k$.
:::

Quais são as classes de equivalência (@def-class-eq)? Por exemplo, qual conjunto é a classe $[0]$ de $0$? Temos pela definição da classe $[0]$ que 
$$
[0]=\{a\in\Z\mid 0\equiv_3 a\}=\{a\in\Z\mid a-0=3k\}=\{a\in\Z\mid a=3k\}=\{3k\mid k\in \Z\}.
$$
Ou seja, 
$$
[0]=\{0,3,-3,6,-6,\ldots\}=\{3k\mid k\in\Z\}.
$$
Similarmente 
$$
[1]=\{a\in\Z\mid 1\equiv_3 a\}=\{a\in\Z\mid a-1=3k\}=\{a\in\Z\mid a=3k+1\}=\{1,-2,4,-5,7,-8,10,\ldots\}
$$
e
$$
[2]=\{a\in\Z\mid 2\equiv_3 a\}=\{a\in\Z\mid a-2=3k\}=\{a\in\Z\mid a=3k+2\}=\{2,-1,5,-4,8,-7,\ldots\}
$$

Obtemos que todo número inteiro pertençe a uma das classes de equivalência $[0],[1],[2]$. De fato se $a\in\Z$, então o resto de $a$ quando dividido por $3$ é $0$, $1$ ou $2$ e $a\in[r]$ onde $r$ é o seu resto. Assim temos apenas estas três classes. 

:::{#exr-class-res}
Seja $n\geq 2$ um inteiro e defina a relação $\equiv_n$ sobre $\Z$ na seguinte forma:
$$
a\equiv_n b\quad\mbox{se e somente se $b-a=kn$ com algum $k\in \Z$}.
$$
Descreve as classes de equivalência para a relação $\equiv_n$. 
:::

## Mais duas relações

Os seguintes dois exemplos importantes serão tratados como exercícios.

:::{#exr-ntimesn}
Seja $A=\N\times \N$ e defina a seguinte relação sobre $A$:
$$
(a,b)\equiv (c,d)\quad\bicond \quad a+d=b+c.
$$

1. Mostre que $\equiv$ é uma relação de equivalência.
2. Ache as classes de equivalência dos elementos $(1,2)$, $(2,4)$, e $(3,5)$. 
3. Dê uma descrição de todas as classes de equivalência.
:::

:::{#exr-ztimesz}
Seja $A=\Z\times \Z$ e defina a seguinte relação sobre $A$:
$$
(a,b)\equiv (c,d)\quad\bicond \quad ad=bc.
$$

1. Mostre que $\equiv$ é uma relação de equivalência.
2. Ache as classes de equivalência dos elementos $(1,2)$, $(2,4)$, e $(3,6)$. 
3. Dê uma descrição de todas as classes de equivalência.
:::
