---
number-sections: true
lang: pt-BR
format: 
    pdf:
        number-sections: true
        include-in-header:
            text: |
                \setcounter{section}{4}
---

# Lista de Exercícios

::: {.content-hidden}
$$
{{< include ../macros.tex >}}
$$
:::

Em @exr-exfun1-@exr-exfun5, 
\begin{align*}
A&=\{1,2,3,4,5\};\\
B&=\{4,6,8\};\\
C&=\{1,3,5,7\}.
\end{align*}

:::{#exr-exfun1}
Seja $f:A\to B$, definida por 
$$
1\mapsto 4,\ 2\mapsto 6,\ 3\mapsto 8,\ 4\mapsto 8,\ 5\mapsto 6.
$$

1. Quais das seguintes afirmações são verdadeiras para $f$?
    a. $f$ é injetiva;
    b. $f$ é sobrejetiva;
    c. $f$ é bijetiva.
2. Decida se $f$ possui inversa à direita ou inversa à esquerda. Construa a inversa caso ela existe. 
:::


:::{#exr-}
Seja $g:B\to C$ definida por 
$$
4\mapsto 1,\ 6\mapsto 5,\ 8\mapsto 7.
$$

1. Quais das seguintes afirmações são verdadeiras para $g$?
    a. $g$ é injetiva;
    b. $g$ é sobrejetiva;
    c. $g$ é bijetiva.
2. Decida se $g$ possui inversa à direita ou inversa à esquerda. Construa a inversa caso ela existe. 
:::

:::{#exr-}
Considere a função $h=g\circ f:A\to C$.

1. Calcule $h(a)$ para todo $a\in A$. 
2. Quais das seguintes afirmações são verdadeiras para $h$?
    a. $h$ é injetiva;
    b. $h$ é sobrejetiva;
    c. $h$ é bijetiva.
3. Decida se $h$ possui inversa à direita ou inversa à esquerda. Construa a inversa caso ela existe. 
:::



:::{#exr-}
Qual é o número de funções diferentes com domínio $A$ e codomínio $B$? Quantas destas são injetivas e quantas são sobrejetivas? 
Responde as mesmas perguntas para funções com domínio $B$ e codomíonio $C$. 
:::


:::{#exr-exfun5}
Seja $f:\R\to \R$ definida com $f(x)=x^2$. 

1. Restrinja o codomínio de $f$, sem mudar o seu domínio, tal que a nova função seja sobrejetiva. 
2. Considere a função $\tilde f$ obtida no item 1. Decida se $\tilde f$ tem inversa à esquerda ou à direita. Construa a inversa caso ela existir. 
3. Ache um conjunto $C\subseteq \R$ (maior possível) tal que a restrição $\tilde f|_C$ é invertível. Determine a inversa de $\tilde f|_C$ explicitamente. 
:::

:::{#exr-}
Considere a matriz 
$$
A=\begin{pmatrix}
1 & 1 \\ 0 & 1\\ 0 & 0 \end{pmatrix}
$$
e seja $F:\R^2\to \R^3$ a função
$$
F\begin{pmatrix} x \\ y\end{pmatrix} =A\begin{pmatrix} x \\ y\end{pmatrix}.
$$

1. Quais das seguintes afirmações são verdadeiras para $F$?
    a. $F$ é injetiva;
    b. $F$ é sobrejetiva;
    c. $F$ é bijetiva.
2. Decida se $F$ possui inversa à direita ou inversa à esquerda. Construa a inversa caso ela existe. 
:::

:::{#exr-}
Considere a matriz 
$$
B=\begin{pmatrix}
1 & 0 & 0 \\ 1 & 1 & 0 \end{pmatrix}
$$
e seja $G:\R^3\to \R^2$ a função
$$
G\begin{pmatrix} x \\ y\\ z\end{pmatrix} =B\begin{pmatrix} x \\ y\\ z\end{pmatrix}.
$$

1. Quais das seguintes afirmações são verdadeiras para $G$?
    a. $G$ é injetiva;
    b. $G$ é sobrejetiva;
    c. $G$ é bijetiva.
2. Decida se $G$ possui inversa à direita ou inversa à esquerda. Construa a inversa caso ela existe. 
:::


:::{#exr-}
Sejam $f:A\to B$ e $g:B\to C$ funções. Decide quais das seguintes afirmações são verdadeiras. Se uma afirmação for verdadeira, dê uma prova; caso contrário, exiba um contra-exemplo.

1. Se $f$ e $g$ são injetivas, então $g\circ f$ é injetiva. 
2. Se $f$ e $g$ são sobrejetivas, então $g\circ f$ é sobrejetiva. 
3. Se $f$ e $g$ são bijetivas, então $g\circ f$ é bijetiva. 
4. Se $g$ é sobrejetiva, então $g\circ f$ é sobrejetiva. 
5. Se $f$ é injetiva, então $g\circ f$ é injetiva.
:::

:::{#exr-}
Seja $\R_{\geq 0}=\{x\in\R\mid x\geq 0\}$ e seja $f:\R\to \R_{\geq 0}, f(x)=x^2$ e $g:\R_{\geq 0}\to \R$, $g(x)=\sqrt x$. Mostre que 

1. $g$ é  inversa à direita de $f$;
2. $g$ não é inversa de $f$.
:::

:::{#exr-}
Seja $f:\R\to \R, f(x)=\exp(x)(=e^x)$. Decida se $f$ possui  inversa à esquerda ou à direita e contstrua a inversa quando existir. 
:::

:::{#exr-}
Seja $f:\R\to\R$, $f(x)=x^2$. 
Determine os seguintes conjuntos:

1. $f([-1,1])$;
2. $f([0,1])$;
3. $f^{-1}(\{1\})$;
4. $f^{-1}(\{0\})$;
5. $f^{-1}(\{-1\})$;
6. $f^{-1}([-1,0])$;
:::


:::{#exr-}
Seja $f:A\to B$ uma função. Mostre que 
$$
\mathcal P_f=\{f^{-1}(\{b\})\mid b\in\mbox{Im}(f)\} 
$$ 
é uma partição de $A$. 
:::

:::{#exr-}
Determine a partição $\mathcal P_f$ para a função $f:\R^2\to \R$, $f(x,y)=x-y$. 
:::


:::{#exr-} 
Seja $f:A\to B$ uma função, sejam $X_1,X_2\subseteq A$ e $Y_1,Y_2\subseteq B$. Demonstre que 

1. $f(X_1\cup X_2)=f(X_1)\cup f(X_2)$; 
2. $f(X_1\cap X_2)\subseteq f(X_1)\cap f(X_2)$;
3. $f^{-1}(Y_1\cup Y_2)=f^{-1}(Y_1)\cup f^{-1}(Y_2)$; 
4. $f^{-1}(Y_1\cap Y_2)= f^{-1}(Y_1)\cap f^{-1}(Y_2)$.

Dê exemplo explícito de uma função $f:A\to B$ e subconjuntos $X_1,X_2\subseteq A$ tais que $f(X_1\cap X_2)\neq f(X_1)\cap f(X_2)$ mostrando que em geral igualdade não vale no item 2. do exercício anterior.
:::

