---
number-sections: true
lang: pt-BR
format: 
    pdf:
        number-sections: true
        include-in-header:
            text: |
                \setcounter{section}{4}
---

# Lista de Exercícios

:::{#exr-}
Demonstre, usando apenas os Axiomas de Peano e a definição da adição, que $1\neq a+b$ para todo $a,b\in\N$. 
:::


:::{#exr-}
Defina $m^n$, para $m,n\in\N$, usando as regras 

1. $m^1=m$;
2. $m^{S(n)}=m^n\cdot m$.

Demonstre, para todo $a,b,c\in\N$, usando indução e as propriedades da adição e multiplicação enunciadas e provadas na aula que 

1. $a^{b+c}=a^b\cdot a^c$;
2. $a^{bc}=(a^b)^c$; 
3. $(ab)^c=a^c\cdot b^c$.
:::


:::{#exr-}
Demonstre as seguintes afirmações por indução.

1. $2(1+2+\cdots+n)=n(n+1)$;
2. $6(1^2+\cdots+n^2)=n(n+1)(2n+1)$;
3. $4(1^3+\cdots+n^3)=n^2(n+1)^2$. 
:::

:::{#exr-}
Demonstre is items do @lem-fibonacci que aparecem sem demonstração. 
:::

:::{#exr-}
Demonstre que $ab=0$ implica que $a=0$ ou $b=0$ para todo $a,b\in\Z$. 
:::

:::{#exr-div-N}
Se $a,b\in\N$, dizemos que $a$ divide $b$ (e escrevemos que $a\mid b$) se existir $q\in \N$ tal que $b=qa$. Demonstre as seguintes afrirmações, 
usando  os Axiomas de Peano, a definição das operações e os resultados demonstrados ou enunciados na aula 

1. Mostre, para $a,b\in\N$ que se $a|b$,  então $a\leq b$.
2. Mostre que a relação $|$ é uma ordem parcial sobre o conjunto $\N$. 
3. Mostre que $|$ não é uma ordem total.
:::

:::{#exr-}
Defina a relação $|$ entre números inteiros na mesma forma que no @exr-div-N (para todo $a,b\in\Z$, $a\mid b$ se existir $q\in \Z$ tal que $b=qa$). 
Mostre que a relação $|$ não é antissimétrica e assim ela é não é uma ordem total em $\Z$.  
:::


:::{#exr-}
Seja $n\in \Z$ com $n\geq 2$, e defina a seguinte relação $\equiv$ entre $a,b\in \Z$:
$$
a\equiv b\mbox{ se e somente se }n\mid a-b.
$$

1. Mostre que $\equiv$ é uma relação de equivalência. 
2. Faça uma lista das classes de equivalência para valores pequenos de $n$ ($n=2,3,4$). 
:::

:::{#exr-}
Demonstre as seguintes afirmações.

1. $1\cdot 1!+2\cdot 2!+\cdots+n\cdot n!=(n+1)!-1$.
2. $\binom n0+\binom n1+\cdots+\binom nn=2^n$
3. $\binom n1+2\binom n2+\cdots+n\binom nn=2^{n-1}n$.
:::

:::{#exr-}
Demonstre as afirmações dos @lem-int-ops, @lem-pre-ordering, @lem-int-pos (que não têm demonstração nas apostilas). 
:::

:::{#exr-}
Determine o quociente e o resto da divisão de $a$ por $b$, onde são os seguintes: 

1. $a=27$, $b=5$;
2. $a=111$, $b=11$;
3. $a=-27$, $b=5$;
4. $a=-111$, $b=11$. 
:::

:::{#exr-}
Demonstre as seguintes afirmações para todo $a,b,c\in\Z$:

1. Se $c\mid a$ e $c\mid b$, então $c\mid (a+b)$;
2. Se $c\mid a$, então $c\mid ka$ para todo $k\in\Z$;
3. Se $c\mid b$ e $c\mid (a+b)$, então $c\mid a$.
:::


:::{#exr-}
Seja $a\in \Z$. Demonstre as seguintes afirmações:  

1. Na divisão de $a^2$ por $4$, o resto é $0$ ou $1$.
2. Na divisão de $a^2$ por $8$, o resto é $0$, $1$, ou $4$.
:::

:::{#exr-}
Seja $k\geq 0$ um inteiro. 

1. Mostre que o resto de $10^k$ na divisão por $3$ é $1$. 
2. Faça a mesma coisa  para o resto de $10^k$ na divisão por $9$.
3. Mostre que o resto de $10^k$ na divisão por $11$ é $1$ se $k$ é par e $10$ se $k$ é ímpar.
:::

:::{#exr-}
Sejam $a,\ b,\ c\in\Z$. Demonstre as seguintes afirmações ou dê
contraexemplo:

1. se $ac\mid bc$, então $a\mid b$;
2. se $a\mid b$ e $a\mid c$, então $a\mid (b-c)$;
3. se $c\mid (a+b)$, então $c\mid a$ ou $c\mid b$.
4. se $a\mid b$ e $c\nmid a$, então $c\nmid b$.
:::

:::{#exr-}
Escreva o número $a$ na base $b$ para:

1. $a=133$, $b=2$;
2. $a=133$, $b=3$;
3. $a=133$, $b=4$;
4. $a=133$, $b=5$;
5. $a=133$, $b=8$.
6. $a=133$, $b=16$.
:::

:::{#exr-}
Na aula consideramos bases $b\geq 2$. Considere a base $b=-2$ com os algarismos $0$ e $1$.
Escreva os números $a=-10,\ldots,10$ na base $b=-2$ sem usar o sinal de menos. 
:::

:::{#exr-}
Mostre que todo número inteiro pode ser escrito de forma única na como expansão na base $b=-2$. Ou 
seja, se $a\in\Z$, então $a$ pode ser escrito na forma
$$
a=\sum_{i=0}^n a_i(-2)^i
$$
e a sequência dos algarismos $a_0,\ldots,a_n\in\{0,1\}$ é unicamente determinada por $a$.
[Dica: Use indução em $|a|$ e siga os passos da demonstração do @thm-exp-nat.]
:::


:::{#exr-}
Sejam $a_0,q\in \Z$ e considere a progressão geométrica
$$
a_0,\ a_1=a_0\cdot q,\ a_2=a_1\cdot q,\ldots
$$
Demonstre que a soma dos $n$ primeiros termos desta progressão é dada por
$$
S_n=\begin{cases}
na_0,&\mbox{se }q=1;\\
a_0\displaystyle{\frac{q^n-1}{q-1}},&\mbox{se }q\neq 1.
\end{cases}
$$
:::

:::{#exr-}
Demonstre os critérios de divisibilidade no @thm-crit-div que não têm demonstração na apostila.
:::

:::{#exr-}
Representa os números $a,b\in\Q$ com pares ordenados $(m,n)\in\Z\times(\Z\setminus\{0\})$ e 
calcule $a+b$ e $a\cdot b$ usando estas representações para os seguintes casos:

1. $a=1/2$ e $b=1/3$.
2. $a=2/5$ e $b=3/4$.
3. $a=5/6$ e $b=7/8$.
:::

:::{#exr-}
Escreva o número $0,10\overline{123}$ na forma fracional.
:::


:::{#exr-}
Seja $a=5/7$. 
1. Escreva o número racional $a=5/7$ na forma decimal.
2. Determine o período e o pré-período da expansão decimal de $a$.
3. Escreva o mesmo número $a$ como expansão na base $3$.
:::

:::{#exr-}
Considere o número $x=a/b$ onde $a,b\in\N$ são tais que $0<a<b$. Assuma ainda que 
não existe nenhum $c\in\N$, com $c>1$, que divide simultaneamente $a$ e $b$ (ou seja, a fração $a/b$ está na sua forma irredutível). Mostre que a expansão decimal de $x$ é finita se e somente se $b$ é da forma $b=2^m5^n$ para alguns inteiros $m,n\geq 0$.
:::

:::{#exr-}
Seja $x=a/b$ um número racional com $a,b\in\N$ e $0<a<b$. Mostre que o comprimento do período da expansão decimal de $x$ é o menor que $b$. 
:::

:::{#exr-}
Demonstre que o número $0,\overline{9}=0,999\cdots$ é igual a $1$.
:::

:::{#exr-}
Seja $a=[a_n\cdots a_1a_0]_b$ um número natural escrito na base $b\geq 2$. 

1. Mostre que $b\mid a$ se e somente se $a_0=0$.
2. Mostre que $b-1\mid a$ se e somente se a soma dos dígitos de $a$ é múltiplo de $b-1$.
3. Mostre que $b+1\mid a$ se e somente se a soma dos dígitos de $a$ com sinais alternados (começando com sinal positivo) é múltiplo de $b+1$.
:::


:::{#exr-}
Caclule a soma e o produto dos seguintes números complexos: 

1. $z_1=2+i$ e $z_2=3+4i$;
2. $z_1=1-i$ e $z_2=5+2i$;
3. $z_1=4+3i$ e $z_2=2-5i$.

Esboçe os números e as suas somas e produtos no plano complexo.
:::

:::{#exr-}
Calcule o módulo, o argumento, o conjugado e o inverso dos seguintes números complexos:

1. $z=3+4i$;
2. $z=1-\sqrt{3}i$;
3. $z=-2+\sqrt{2}i$;
4. $z=-1- i$.

Esboçe os números no plano complexo.
:::

:::{#exr-polar}
Escreva os seguintes números complexos na forma polar:

1. $z=1+i$;
2. $z=1-\sqrt{3}i$;
3. $z=-\sqrt{3}+i$;
4. $z=-1-1i$.

Esboçe os números no plano complexo.
:::

:::{#exr-}
Utilizando a forma polar, calcule o produto e o quociente dos números complexos 
no @exr-polar. Esboçe os números obtidos no plano complexo.
:::

:::{#exr-}
Utilizando a forma polar, calcule $z^k$ com $k=2,3,4,5$ dos números complexos no @exr-polar.
Esboçe os números obtidos no plano complexo.
:::

:::{#exr-}
Utilizando a forma polar, calcule as raízes $n$-ésimas dos seguintes números complexos:

1. $z=1$, $n=1,2,3,4,5,6$;
2. $z=2$, $n=1,2,3,4,5,6$;
3. $z=1+i$, com $n=3$;
4. $z=1-\sqrt{3}i$, com $n=4$;
5. $z=-\sqrt{3}+i$, com $n=6$;
6. $z=-1-1i$, com $n=5$.

Esboçe os números obtidos no plano complexo.
:::

:::{#exr-}
Seja $k\geq 2$ um inteiro e sejam $\xi_1,\ldots,\xi_k$ as raízes $k$-ésimas da unidade. Mostre que

1. $\xi_1+\xi_2+\cdots+\xi_k=0$;
2. $\xi_1\xi_2\cdots \xi_k=(-1)^{k+1}$.
:::

:::{#exr-}
Resolva os seguintes polinômios no conjunto dos números complexos:

1. $z^2+2z+5=0$;
2. $z^2-4z+8=0$;
3. $z^3-3z^2+4=0$;
4. $z^3+1=0$.
5. $z^{6}-z^3+1=0$. 

Esboçe as raízes no plano complexo.
:::

:::{#exr-}
Considere a matriz 
$$
J=\begin{bmatrix}0 & 1\\-1 & 0\end{bmatrix}.
$$

1. Seguindo as técnicas que você aprendeu em GAAL, mostre que $J$ não possui autovalores reais.
2. Mostre que $J$ possui dois autovalores complexos e determine os autovetores associados 
em $\C^2$. 
3. Ache uma matriz invertível $P\in M_2(\C)$ tal que $P^{-1}JP$ é uma matriz diagonal.
:::

:::{#exr-}
Considere o conjunto das matrizes $2\times 2$ com entradas em $\R$ definido por
$$
G=\left\{\begin{bmatrix}a & -b\\b & a\end{bmatrix}\mid a,b\in\R\right\}.
$$
Seja 
$$
\psi:\C\to G,\quad \psi(a+bi)=\begin{bmatrix}a & -b\\b & a\end{bmatrix}.
$$

1. Mostre que $\psi$ é uma bijeção.
2. Mostre que $\psi(z_1+z_2)=\psi(z_1)+\psi(z_2)$ e $\psi(z_1z_2)=\psi(z_1)\psi(z_2)$ para todos $z_1,z_2\in\C$.
3. Conclua que os números complexos podem ser realizados como certas matrizes $2\times 2$ com entradas reais.
4. Identifique a matriz que corresponde ao número complexo $i$ e calcule sua potência $n$-ésima para $n\in\N$.
4. Identifique as matrizes que correspondem aos números reais e aos números puramente imaginários. 
:::

:::{#exr-}
Seja 
$$
A=\begin{bmatrix}1 & i\\i & -1\end{bmatrix}.
$$

1. Mostre que o único autovalor complexo de $A$ é $0$ e os autovetores associados são todos os múltiplos escalares de
um vetor específico que você deve encontrar. 
2. Deduza que $A$ não é diagonalizável sobre $\C$ mesmo sendo simétrica. Reflita sobre a diferença entre matrizes simétricas com entradas reais e com entradas complexas considerando o que você aprendeu em GAAL.
:::

:::{#exr-}
Demonstre a identidade de Euler que 
$$
e^{i\theta}=\cos(\theta)+i\sin(\theta)
$$ 
usando as seguintes séries de Taylor das funções exponencial, cosseno e seno:
\begin{align*}
e^x&=\sum_{n=0}^\infty \frac{x^n}{n!},\\
\cos(x)&=\sum_{n=0}^\infty \frac{(-1)^n}{(2n)!}x^{2n},\\
\sin(x)&=\sum_{n=0}^\infty \frac{(-1)^n}{(2n+1)!}x^{2n+1}.
\end{align*}
:::


:::{#exr-}
Usando a fórmula quadrática, resolva a equação $z^{2}+z+1=0$ para números complexos $z$. Demonstre que as soluções são terceiras raízes da unidade. Consegue explicar porque?
:::


:::{#exr-}
Esboce os seguintes conjuntos no plano complexo.

1. $\{z \in \mathbb{C}||z| \leq 1\}$;
2. $\{z \in \mathbb{C}||z-i| \leq 1\}$;
3. $\{z \in \mathbb{C} \mid \operatorname{Im}(z) \in[-1,1]\}$;
4. $\left\{z \in \mathbb{C} \mid \operatorname{Im}\left(z^{2}\right)=1\right\}$.
:::


:::{#exr-}
Encontre um valor $\vartheta$ tal que a $|\exp (i \vartheta)-1|=2$.
:::

:::{#exr-}
[Vestibular ITA 2023] Calcule a soma de todos os coeficientes das potências com expoentes múltiplas de 3 na expansão de
$$
p(x)=\left(1+x^{2}-x^{3}+x^{4}\right)^{10}
$$

[Dica: Sejam $1, \omega, \omega^{2}$ as três terceiras raízes da unidade. Calcule $p(1)+p(\omega)+p\left(\omega^{2}\right)$. Para mais detalhes consute o vídeo do Professor Engenheiro no youtu.be/FIwrxWT9Qr0.]
:::

:::{#exr-}
Usando as regras usuais da função logaritmo e exponencial, atribua um valor à expressão $i^{i}$.
:::


