---
title: "Funções"
number-sections: true
lang: pt-BR
---

## Definições básicas relacionadas com funções

:::{#def-function}
Sejam $A$ e $B$ conjuntos. Uma função de $A$ em $B$ é uma relação $R\subseteq A\times B$ tal que 
$$
\forall a\in A:(\exists b\in B\mbox{ único }:aRb) 
$$
Quando $R\subseteq A\times B$ é uma função e $aRb$, então escrevermos que $b=R(a)$. Nós frequentemente usamos as palavras, mapa, aplicação, correspondência em vez de função.
:::

:::{#exm-function}
Seja $A=\{1,2,3\}$ e $B=\{1,3,5,7\}$. As seguintes relações são funções:
\begin{align*}
R_1&=\{(1,3),(2,3),(3,5)\};\\
R_2&=\{(1,3),(2,3),(3,3)\};\\
R_2&=\{(1,3),(2,7),(3,5)\}.
\end{align*}
As seguintes não são funções:
\begin{align*}
R_4&=\{(1,3),(2,3)\};\\
R_5&=\{(1,3),(2,3),(3,3),(2,7)\};\\
\end{align*}
:::


:::{#def-function-dom}
Se $R\subseteq A\times B$ é uma função, então escrevemos $R$ na forma $R:A\to B$. O conjunto $A$ é chamado de domínio, o conjunto $B$ é o codomínio ou contradomínio da função $R$. A imagem de $R$ está definida como 
$$
\mbox{Im}(R)=R(A)=\{R(a)\mid a\in A\}.
$$
:::

Note que $\mbox{Im}(R)\subseteq B$, mas a imagem da função pode ser estritamente menor que o conjunto $B$. 
Por exemplo, no caso da função $f:\N\to \R,\ f(n)=n+1$,  o codomínio de $f$ é $\R$, mas a sua imagem é o conjunto $\{2,3,\ldots\}$.

:::{#def-function-dom}
Seja $f:A\to B$ uma função.

1. A função $f$ é sobrejetiva (ou sobrejetora) se $\mbox{Im}(f)=B$.
2. A função $f$ é injetiva (ou injetora) quando $f(a_1)=f(a_2)$ implica que $a_1=a_2$ para todo $a_1,a_2\in A$.
3. A função $f$ é bijetiva (bijetora) se ela é sobrejetiva e injetiva. 
4. A função $f$ é dita invertível se ela é bijetiva. 
:::


:::{#exm-functions2}
Seja $\R_+=\{x\in\R\mid x\geq 0\}$.
Considere as funções
$$
g:\R\to \R,\ g(x)=x^2,\quad f:\R\to \R_+,\ f(x)=x^2.
$$
As funções $f$ e $g$ parecem iguais, mas elas são consideradas diferentes, pois os codimonínios são diferentes. De fato, $f$ é sobrejetiva, mas $g$ não é. 
A função 
$$
h:\R_+\to \R_+,\quad h(x)=x^2
$$
é sobrejetiva e injetiva, então ela é uma função bijetiva e também é invertível.
:::

:::{#exm-id-function}
Se $A$ é um conjunto qualquer, então a função identidade em $A$ é a função 
$$
\mbox{id}_A:A\to A, \mbox{id}_A(a)=a.
$$ 
A função $\mbox{id}_A$ é bijetiva. 
:::

## A composição de funções

:::{#def-comp-func}
Sejam $f:A\to B$ e $g:B\to C$ funções. Definimos $g\circ f:A\to C$ como a função 
$$
g\circ f:A\to C,\quad g\circ f(a)=g(f(a))\quad\mbox{para todo }a\in A
$$
:::

:::{#exr-comp-func}
Demonstre que $g\circ f:A\to C$ é uma função.
:::

:::{#def-comp-func}
Assuma que $A=\{1,2,3\}$, $B=\{3,4\}$, e $C=\{2,4,6,8\}$. Sejam 
$$
f:A\to B,\quad 1\mapsto 3,\ 2\mapsto 3,\ 3\mapsto 4
$$
e 
$$
g:B\to C,\quad 3\mapsto 6,\ 4\mapsto 3.
$$
Então 
$$
g\circ f:\{1,2,3\}\to \{2,4,6,8\},\quad 1\mapsto 6,\ 2\mapsto 6,\quad 3\mapsto 3.
$$
:::

:::{#lem-comp-function}
Sejam $f:A\to B$, $g:B\to C$, $h:C\to D$ funções. Então 

1. $h\circ (g\circ f)=(h\circ g)\circ f$;
2. $f\circ \mbox{id}_A=f$;
3. $\mbox{id}_B\circ f=f$.
:::

## Funções inversas

:::{#def-inverse-func}
Seja $f:A\to B$ uma função. 

1. Uma função $g:B\to A$ é dita inversa de $f$ à direita se $g\circ f=\mbox{id}_A$. 
2. Uma função $g:B\to A$ é dita inversa de $f$ à esquerda se $f\circ g=\mbox{id}_D$.
3. Uma função $g:B\to A$ é dita inversa de $f$ se $g\circ f=\mbox{id}_A$ e $$f\circ g=\mbox{id}_D$.
:::

:::{#lem-inverse-func}
Seja $f:A\to B$ uma função. Então 

1. $f$ tem inversa à direita se e somente se $f$ é sobrejetiva.
2. $f$ tem inversa à esquerda se e somente se $f$ é injetiva.
3. $f$ tem inversa se e somente se $f$ é bijetiva.
:::

:::{#def-inverse-func2}
Se $f:A\to B$ é uma função e $g:B\to A$ é inversa de $f$, então escrevemos que $g=f^{-1}$. 
:::

## Restrição de $f$

:::{#def-func-restriction}
Seja $f:A\to B$ uma função e $C\subseteq A$. Definimos a restrição de $f$ para $C$ como a função
$$
f|_C:C\to B,\quad c\mapsto f(c)\quad\mbox{para todo }c\in C.
$$
:::