---
title: "Mais sobre inteiros e racionais"
number-sections: true
lang: pt-BR
---

## Coeficientes binomiais

Os números que aparecem no triângulo de Pascal são chamados de coeficientes binomiais. 

Primeiras seis linhas do triângulo de Pascal:
```
          1
        1   1
      1   2   1
    1   3   3   1
  1   4   6   4   1
1   5   10   10   5   1
```

A regra de formação do triângulo de Pascal é a seguinte: cada número é a soma dos dois números diretamente acima dele. Os números nas bordas do triângulo são sempre $1$. Contando as linhas a partir de $0$, a $n$-ésima linha do triângulo de Pascal contém $n + 1$ números.
Os números na $n$-ésima linha são denotados por $\binom{n}{0}, \binom{n}{1}, \binom{n}{2}, \ldots, \binom{n}{n}$. A regra de formação pode ser expressa como:
$$ 
\binom n0=\binom nn=1, \quad \binom{n}{k} = \binom{n-1}{k-1} + \binom{n-1}{k}\quad \text{para } 1 \leq k \leq n-1. 
$$

O número $\binom{n}{k}$ é chamado de *coeficiente binomial*. 

:::{#lem-}
O coeficiente binomial $\binom nk$ coincide com o número 
de maneiras de escolher  $k$ elementos de um conjunto com $n$ elementos. 
Em outras palavras $\binom nk$ coincide com o número de subconjuntos com $k$ elementos 
de um conjunto com $n$ elementos. 
:::
:::{.proof}
Demonstremos por indução em $n$ começando com $n=0$. Quando $n=0$, a afirmação é verdadeira 
porque $\binom 00=1$ e temos apenas uma maneira de escolher zero elementos de um conjunto com zero 
elementos (não escolhendo nenhum). Assuma que a afirmação é verdadeira para $n\geq 0$.
Ora assuma que 
temos um conjunto de $n+1$ elementos e queremos formar um subconjunto com $k$ elementos. 
Se $k=0$ ou $k=n+1$, há apenas uma maneira de fazer isso: escolher o conjunto vazio ou o conjunto todo, respectivamente. Logo $\binom {n+1}0=\binom{n+1}{n+1}=1$. 
Agora, suponha que $1 \leq k \leq n$. Então temos duas possibilidades. Pode ser que o $n+1$-ésimo 
elemento esteja no subconjunto escolhido ou não. Se o $n+1$-ésimo elemento estiver no subconjunto, 
então precisamos escolher os outros $k-1$ elementos dos primeiros $n$ elementos, o que pode ser feito de 
$\binom{n}{k-1}$ maneiras. Se o $n+1$-ésimo elemento não estiver no subconjunto, então precisamos escolher os $k$ elementos
dos primeiros $n$ elementos, o que pode ser feito de $\binom{n}{k}$ maneiras. Portanto, o número total de maneiras de escolher $k$
elementos de um conjunto com $n+1$ elementos é a soma dessas duas possibilidades, ou seja,
$$
\binom{n+1}{k} = \binom{n}{k-1} + \binom{n}{k}.
$$
:::

O coeficiente binomial $\binom nk$ é frequentamente escrito usando fatorial. Se $k\in \Z$ e $k\geq 0$, 
então $k!$ é definido como 
$$
0!=1\quad \mbox{e}\quad k!=1\cdot 2 \cdots n.
$$
Por exemplo, os fatoriais dos números $0$, $1$, $2$, $3$, $4$, $5$, $6$ são 
$$
0!=1, \quad 1!=1, \quad 2!=2, \quad 3!=6, \quad 4!=24, \quad 5!=120, \quad 6!=720.
$$

:::{#lem-fatorial}
Se $n$ e $k$ são inteiros com $n\geq 0$ e $0\leq k \leq n$, então 
$$
\binom nk = \frac{n!}{k!(n-k)!}=\frac{n(n-1)(n-2)\cdots (n-k+1)}{k!}.
$$
:::
:::{.proof}
Demonstremos por indução em $n$. Quando $n=0$, a afirmação é verdadeira, pois $\binom 00=1$ e 
$$
\frac{0!}{0!0!}=1.
$$
Assuma que a afirmação é verdadeira para algum $n\geq 0$. Se $k=0$ ou $k=n+1$, então
$$
\binom{n+1}0=1=\frac{(n+1)!}{0!(n+1)!} \quad \mbox{e}\quad \binom{n+1}{n+1}=1=\frac{(n+1)!}{(n+1)!0!}.
$$
Agora, suponha que $1\leq k \leq n$. Então, pela definição do coeficiente binomial e pela hipótese de indução, temos
\begin{align*}
\binom{n+1}k & = \binom nk + \binom{n}{k-1} \\
& = \frac{n!}{k!(n
-k)!} + \frac{n!}{(k-1)!(n-(k-1))!} \\
& = \frac{n!(n-k+1)}{k!(n-k+1)(n-k)!} + \frac{n!k}{k!(n-k+1)(n-k)!} \\
& = \frac{n!(n+1)}{k!(n-k+1)(n-k)!} \\
& = \frac{(n+1)!}{k!((n+1)-k)!}.
\end{align*}
:::

O fatorial $k!$ também tem uma interpretação combinatória. O número $k!$ é o número de maneiras de ordenar $k$ elementos distintos. Por exemplo, se temos $3$ elementos distintos $A$, $B$ e $C$, as possíveis permutações são $ABC$, $ACB$, $BAC$, $BCA$, $CAB$ e $CBA$, totalizando $3! = 6$ ordenações.

## O binómio de Newton

O binómio de Newton é uma fórmula que expressa a expansão de potências de binômios. 
Sabe-se que 
\begin{align*}
(a+b)^2 &= a^2 + 2ab + b^2\\
(a+b)^3 &= a^3 + 3a^2b + 3ab^2 + b^3\\
\end{align*}

Considere 
$$
(a+b)^n = (a+b)(a+b)\cdots (a+b) \quad \text{($n$ fatores)}.
$$
A potência $(a+b)^n$ pode ser expandida como uma soma de termos da forma $a^{n-k}b^k$. Inicialmente podemos pensar assim: ao expandir o produto, cada termo $a^{n-k}b^k$ é obtido escolhendo-se $a$ de $n-k$ fatores e $b$ de $k$ fatores. O número de maneiras de fazer isso é exatamente o coeficiente binomial $\binom nk$. Portanto, a expansão geral é dada por:
\begin{align*}
(a + b)^n &= \binom n0 a^n+\binom n1 a^{n-1}b+\binom n2 a^{n-2}b^2+\cdots+\binom n{n-1} ab^{n-1}+\binom n{n} b^n\\
&= \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^k.
\end{align*}    


A seguir, apresentamos uma demonstração formal do binómio de Newton usando indução matemática.

:::{#lem-binomio}
Para quaisquer números  $a$ e $b$ e um inteiro não negativo $n$, temos:
$$
(a + b)^n = \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^k.
$$
:::
:::{.proof}
Demonstremos por indução em $n$. Quando $n=0$, a afirmação é verdadeira, pois 
$$
(a + b)^0 = 1 = \sum_{k=0}^{0} \binom{0}{k} a^{0-k} b^k.
$$
Assuma que a afirmação é verdadeira para algum $n\geq 0$. Então, temos
\begin{align*}
(a + b)^{n+1} & = (a + b)(a + b)^n \\
& = (a + b) \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^k \\
& = \sum_{k=0}^{n} \binom{n}{k} a^{n-k+1} b^k + \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^{k+1} \\
& = a^{n+1} + \sum_{k=1}^{n} \binom{n}{k} a^{n-k+1} b^k + \sum_{k=0}^{n-1} \binom{n}{k} a^{n-k} b^{k+1} + b^{n+1} \\
& = a^{n+1} + \sum_{k=1}^{n} \binom{n}{k} a^{n-k+1} b^k + \sum_{k=1}^{n} \binom{n}{k-1} a^{n-(k-1)} b^k + b^{n+1} \\
& = a^{n+1} + \sum_{k=1}^{n} \left( \binom{n}{k} + \binom{n}{k-1} \right) a^{n-k+1} b^k + b^{n+1} \\
& = a^{n+1} + \sum_{k=1}^{n} \binom{n+1}{k} a^{n-k+1} b^k + b^{n+1} \\
& = \sum_{k=0}^{n+1} \binom{n+1}{k} a^{(n+1)-k} b^k.
\end{align*}
::: 

## O Lema de divisão de Euclides


:::{#lem-euclides}
Para quaisquer inteiros $a$ e $b$ com $b > 0$, existem únicos inteiros $q$ e $r$ tais que:
$$
a = bq + r \quad \text{com } 0 \leq r < b.
$$
Aqui, $q$ é chamado de *quociente* e $r$ é chamado de *resto* da divisão de $a$ por $b$.
:::
:::{.proof}
Primeiro, provemos a existência de tais inteiros $q$ e $r$. Considere o conjunto 
$$S = \{a - bk \mid k \in \Z \text{ e } a - bk \geq 0\}.$$
O conjunto $S$ é não vazio, pois, escolhendo $k$ adequadamente, podemos garantir que $a - bk$ seja não negativo. Pelo Princípio da Boa Ordem (@lem-N-well-ordered), o conjunto $S$ possui um menor elemento, que chamaremos de $r$. Assim, existe um inteiro $q$ tal que $r = a - bq$ e $r \geq 0$. Agora, precisamos mostrar que $r < b$. Suponha, por contradição, que $r \geq b$. Então, podemos escrever:
$$
r - b = a - bq - b = a - b(q + 1).
$$
Como $r - b \geq 0$, isso implica que $a - b(q + 1) \geq 0$, o que significa que $r - b$ pertence ao conjunto $S$. No entanto, isso contradiz a escolha de $r$ como o menor elemento de $S$. Portanto, devemos ter $r < b$. 

Agora, provemos a unicidade de $q$ e $r$. Suponha que existam outros inteiros $q'$ e $r'$ tais que:
$$
a = bq' + r' \quad \text{com } 0 \leq r' \leq r< b.
$$
Subtraindo as duas expressões para $a$, obtemos:
$$bq + r = bq' + r' \implies b(q - q') = r' - r.$$
Isso implica que $b$ divide $r' - r$. No entanto, como $0 \leq r\leq r' < b$, a diferença $r' - r$ deve satisfazer $0 \leq r' - r < b$. A única maneira de $b$ dividir $r' - r$ dentro desse intervalo é se $r' - r = 0$, ou seja, $r' = r$. Substituindo isso de volta na equação $b(q - q') = r' - r$, obtemos $b(q - q') = 0$, o que implica que $q - q' = 0$, ou seja, $q = q'$. Portanto, os inteiros $q$ e $r$ são únicos.
:::

:::{#def-divisivel}
Um número inteiro $a$ é *divisível* por um número inteiro $b$ se existe um inteiro $k$ tal que $a = bk$. Nesse caso, dizemos que $b$ é um divisor de $a$ e que $a$ é um múltiplo de $b$. Por exemplo, $12$ é divisível por $3$ porque $12 = 3 \cdot 4$.
:::

## Números primos

:::{#def-primo} 
Um número natural $p$ maior que $1$ é chamado de *número primo* se seus únicos divisores são $1$ e $p$. Se um número natural maior que $1$ não é primo, então ele é chamado de *número composto*. Por convenção, o número $1$ não é considerado nem primo nem composto.
:::

:::{#lem-divisivel}
Todo número natural $n\geq 2$ é divisível por algum número primo.
:::
:::{.proof}
Fazemos indução em $n$. Se $n=1$, então não há nada para provar porque $1$ não é considerado. 
Assuma que a afirmação é verdadeira para todo número natural entre $1$ e $n$. Se $n+1$ é primo, então ele é divisível por si mesmo. Se $n+1$ não é primo, então existem inteiros $a$ e $b$ tais que $n+1=ab$ com $2\leq a,b\leq n$. Pela hipótese de indução, existe um número primo $p$ que divide $a$. Então $p$ também divide $n+1$. Portanto, em ambos os casos, o número $n+1$ é divisível por algum número primo.
:::

:::{#thm-infinitos-primos}
Existem infinitos números primos.
:::
:::{.proof}
Assuma ao contrário que existem apenas finitos números primos $p_1,p_2,\ldots,p_n$. Considere o número
$$
N = p_1p_2\cdots p_n + 1.
$$
Por @lem-divisivel, $N$ é disvisível por algum número primo. Seja esse número primo $p$. Então $p$ deve ser igual a algum dos primos $p_1,p_2,\ldots,p_n$ (pela suposição inicial). Mas observe que $N$ não pode ser divisível por $p_i$ para qualquer $i=1,2,\ldots,n$, pois ao dividir $N$ por $p_i$ o resto é $1$. Portanto, nossa suposição inicial deve estar errada, e assim existem infinitos números primos.
:::

## Expansão de naturais na base $b$

Números naturais são escritos normalmente como sequências de algarismos na base decimal. Por exemplo, a sequência $1056$ significa o número
$$
1\cdot 1000+0\cdot 100+5\cdot 10+6.
$$
Mais geralmente, a sequência $[a_na_{n-1}\cdots a_1a_0]$ denota o número
$$
\sum_{k=0}^n a_k\cdot 10^k.
$$

É possível fazer a mesma coisa em uma outra base $b$ assumindo que $b\geq 2$.

:::{#thm-exp-nat}
Assuma que $a$ e $b$ são números  naturais e $b\geq 2$. Então $a$ pode ser escrito unicamente na forma
$$
a=[a_na_{n-1}\cdots a_0]_b=\sum_{k=0}^n a_kb^k
$$
onde $n\geq 0$ e $a_k\in\{0,\ldots,b-1\}$ para todo $k$
:::

Os números $a_k$ são chamados de algarismos de $a$ na base $b$.

:::{.proof}
**Existência.** Usaremos indução por $a$. Se $a\in\{0,\ldots,b-1\}$ então $a$ pode ser escrito como $[a]_b$. Assuma agora que $a\geq b$ e os números menores que $a$ podem ser escritos na base $b$. Usando o Teorema de Divisão de Euclides, escreva $a=qb+a_0$ onde $0\leq a_0\leq b-1$. Como $b\geq 2$, temos que $q<a$, e a hipótese de indução é válida para $q$. Portanto
existem $a_n,\ldots,a_1\in\{0,\ldots,b-1\}$ tais que
$$
q=[a_na_{n-1}\cdots a_1]_b=\sum_{k=1}^n a_kb^{k-1}
$$
e
$$
a=bq+a_0=b\left(\sum_{k=1}^n a_kb^{k-1}\right)+a_0=\sum_{k=0}^n a_kb^{k}=[a_na_{n-1}\cdots a_1a_0]_b
$$
Então a expressão desejada para $a$ existe.

**Unicidade.** Provaremos esta parte também por indução em $a$. Se $a\in\{0,\ldots,b-1\}$, então $a=[a]_b$ é a única expansão de $a$ na base $b$. Assuma que $a\geq b$ e assuma também que todo número menor que $a$ possui única expansão na base $b$. Suponha que $a$ possui duas expansões
$$
a=[a_n\cdots a_1a_0]_b=\sum_{k=0}^n a_kb^k
$$
e
$$
a=[c_m\cdots c_1c_0]_b=\sum_{k=0}^m c_kb^k.
$$
Como acima, escreva $a=qb+r$ onde $0\leq r\leq b-1$ e note que os números $q$ e $r$ são únicos. Pelas duas expressões para o número $a$ obtemos que
$$
a=\sum_{k=0}^n a_kb^k=b\cdot\left(\sum_{k=1}^n a_kb^{k-1}\right)+a_0
$$
e
$$
a=\sum_{k=0}^m c_kb^k=b\cdot\left(\sum_{k=1}^m c_kb^{k-1}\right)+c_0.
$$
Pela unicidade do resto no Teorema de Euclides, obtemos que $r=a_0=c_0$; ou seja, os últimos algarismos são determinados unicamento.

Agora,
$$
q=\sum_{k=1}^n a_kb^{k-1}=\sum_{k=1}^m c_kb^{k-1};
$$
ou seja
$$
q=[a_n\cdots a_1]_b=[c_m\cdots c_1]_b.
$$
A hipótese de indução aplica-se para o número $q$, e assim as as sequências
$[a_n\cdots a_1]_b$ e $[c_m\cdots c_1]_b$ são iguais. Portanto as duas expansões para o número $a$ são iguais como foi afirmado.
:::


:::{#exm-}
Seguindo a demonstração do teorema anterior, obtemos um algoritmo para determinar a sequência dos dígitos de um número natural em uma base $b$. Tome o número $a=168$ e seja $b=5$.

Passo 1:
$$
168=33\cdot 5+3,
$$
portanto o último algarismo de $168$ é $3$ e os demais algarismos são os algarismos de $33$.

Passo 2:
$$
33 = 6\cdot 5+3.
$$
Logo o penúltimo algarismo é $3$ e os demais algarismos são os algarismos de $6$.

Passo 3:
$$
6=1\cdot 5+1;
$$
ou seja, o seguinte algarismo é $1$ e os demais algarismos são os algarismos de $1$.

Passo  4:
$$
1=0\cdot 5+1
$$
que diz que $1=[1]_5$.

Juntando as peças, obtemos que $168=[1133]_5$.
:::


## Critérios de divisibilidade


Seja $a$ um número natural escrito na base $10$ (decimal) como
$$
a=[a_na_{n-1}\cdots a_1a_0]_{10}=[a_na_{n-1}\cdots a_1a_0].
$$
É bem conhecido que, para alguns valores de $b$, a divisibilidade de $a$ por $b$ pode ser determinado olhando apenas os dígitos de $a$.

:::{#exr-}
Demonstre que para todo $i\geq 0$, existe $q_i\in\N_0$ tal que $10^i=3q_i+1$
:::


:::{#thm-crit-div}
(Critérios de divisibilidade)
As seguintes afirmações são verdadeiras para um número natural $a=[a_na_{n-1}\cdots a_1a_0]$ escrito na base decimal.


-  $2\mid a$ se e somente se $2\mid a_0$;
-  $3\mid a$ se e somente se $3\mid a_n+a_{n-1}+\cdots+a_0$;
-  $4\mid a$ se e somente se $4\mid [a_1a_0]$;
-  $5\mid a$ se e somente se $5\mid a_0$;
-  $7\mid a$ se e somente se $7\mid [a_n\cdots a_1]-2a_0$;
-  $8\mid a$ se e somente se $8\mid [a_2a_1a_0]$;
-  $9\mid a$ se e somente se $9\mid a_n+a_{n-1}+\cdots+a_0$;
-  $10\mid a$ se e somente se $10\mid a_0$ (ou seja, $a_0=0$);
-  $11\mid a$ se e somente se $11\mid (-1)^na_n+(-1)^{n-1}a_{n-1}+\cdots-a_1+a_0$;
:::


:::{.proof}
Demonstraremos algumas destas afirmações, o resto será exercício.

1. Considere que
\begin{align*}
a&=[a_na_{n-1}\cdots a_1a_0]=\sum_{k=0}^n10^ka_k=10\left(\sum_{k=1}^n10^{k-1}a_k\right)+a_0\\&=10q+a_0
\end{align*}
com
$$
q=\sum_{k=1}^n10^{k-1}a_k\in\mathbb N.
$$
Como $2\mid 10$, obtemos que o número $a$ é divisível por $2$ se e somente se o algarismo $a_0$ é divisível por $2$.

3. Temos, pelo exercício antes do teorema, para todo $i\geq 0$, existe $q_i\in\N_0$ tal que $10^i=3q_i+1$. Agora considere
\begin{align*}
a&=[a_n\cdots a_1a_0]=\sum_{k=0}^n 10^ka_k=\sum_{k=0}^n (3q_k+1)a_k\\&=3\sum_{k=0}^nq_ka_k+
\sum_{k=0}^na_k.
\end{align*}
No última expressão, a primeira parcela é um múltiplo de $3$. Logo $a$ é divisível por $3$ se e somente se a segunda parcela na última expressão é divisível por $3$, mas esta segunda parcela é justamente a soma dos dígitos de $a$.
:::



## Expansão de racionais

Comecemos por um resultado conhecido de cálculo.

:::{#lem-}
Se $|q| <1$, então a série
$$
\sum_{n=0}^\infty q^n
$$
é convergente e a sua soma é igual a
$$
\frac{1}{1-q}.
$$
:::


:::{.proof}
Exercício
:::

No bloco anterior, estudamos expansões de números naturais na base $b$. Escrevemos naturais na base $b$ como $[a_na_{n-1}\cdots a_1a_0]_b$. Quando $b=10$, escrevemos o mesmo número como $[a_na_{n-1}\cdots a_1a_0]$ (sem explicitamente indicar a base).

Uma fração decimal (ou expansão decimal) não negativa é uma sequência (possivelmente infinita) de algarismos na forma $[a_na_{n-1}\cdots a_1a_0,a_{-1}a_{-2}\cdots]$ onde $a_{i}\in\{0,\ldots,9\}$. O número representado pela fração é
\begin{align*}
a&=\sum_{k=n}^{-\infty}a_k10^k=\sum_{k=0}^n a_k10^k+\sum_{k=1}^{\infty}a_{-k}10^{-k}\\&=
[a_na_{n-1}\cdots a_1a_0]+\sum_{k=1}^{\infty}a_{-k}10^{-k}.
\end{align*}
A expressão acima mostra que cada fração decimal não negativa pode ser escrita como a soma de um número natural e uma fração decimal na forma $[0,a_{-1}a_{-2}\cdots]$. Como os números naturais foram tratados na unidade anterior, aqui vamos focar apenas frações na forma $[0,a_{-1}a_{-2}\cdots]$. Uma fração natural desta forma pode ser finita ou infinita. Quando a sequência de algarismos depois da vírgula é infinita, então a fração é infinita; caso contrário a fração é finita. Uma fração finita pode ser escrita na forma $[0,a_{-1}a_{-2}\cdots a_{-n}]$. Note que uma fração finita pode ser considerada infinita adicionando uma sequência infinita de zeros e assim nós frequentemente assumimos que as frações analizadas são infinitas.

:::{#lem-}
Para qualquer sequência (possivelmente infinita) de algarismos, a expansão $[0,a_{1}a_{2}\cdots]$ representa um número real entre zero e um
:::


:::{.proof}
Precisa provar que a série
$$
\sum_{k=1}^\infty a_{k}10^{-k}
$$
é convergente e converge a um número entre zero e um. Como $0\leq a_i\leq 9$ para todo $i$, obtemos que
$$
\sum_{k=1}^\infty a_{k}10^{-k}\leq\sum_{k=1}^\infty 9\cdot 10^{-k}=\frac 9{10}\sum_{k=0}^\infty 10^{-k}=\frac 9{10}\frac 1{1-1/10}=1.
$$
Como os termos da série na última linha são não negativas, a conta acima mostra que a série que corresponde à expansão $[0,a_{1}a_{2}\cdots]$ é convergente e converge a um número não negativo menor ou igual a $1$
:::

Note que o mesmo número real pode ser escrito de maneiras distintas como fração decimal. Por exemplo, $1,00\cdots=0,99\cdots$.

Considere a fração decimal $[0,a_{1}a_{2}\cdots]$. Esta fração chama-se periódica se existem $m\geq 0$ e $r\geq 1$ tais que $a_{r+k}=a_k$ para todo $k> m$. A sequência $[a_1\cdots a_m]$ chama-se pré-período, enquanto a sequência $[a_{m+1}\cdots a_{m+r}]$ chama-se período da fração.

Uma fração periódica com pré-período $[a_1\cdots a_m]$ e período $[a_{m+1}\cdots a_{m+r}]$ tem a forma
$$
[0,a_1\cdots a_ma_{m+1}\cdots a_{m+r}a_{m+1}\cdots a_{m+r}\cdots];
$$
ou seja, a fração começa com a sequência $[a_1\cdots a_m]$ e depois a sequência $[a_{m+1}\cdots a_{m+r}]$ está se repetindo. Neste caso escrevemos a fração como
$$
[0,a_1\cdots a_m\overline{a_{m+1}\cdots a_{m+r}}].
$$
Por exemplo
$$
1/44=0,02272727\cdots=0,02\overline{27}.
$$

:::{#thm-}
As seguintes afirmações são verdadeiras.

-  Toda expansão decimal periódica representa um número racional.
-  Se $a/b$ é um número racional tal que $0<a<b$, então sua expansão decimal é periódica
:::


:::{.proof}
11. Considere a expansão decimal
$$
[0,a_1a_2\cdots]=[0,a_1a_2\cdots a_m\overline{a_{m+1}\cdots a_{m+r}}]
$$
e seja $a$ o número representado por esta expansão. Pelo lema anterior, $0\leq a\leq 1$. Sejam $u$ e $v$ os números naturais
$$
u=[a_1a_2\cdots a_m]\quad\mbox{e}\quad v=[a_{m+1}\cdots a_{m+r}].
$$
Tem-se que
\begin{align*}
a&=\sum_{k=1}^\infty a_k10^{-k}=\frac u{10^{m}}+\sum_{k=1}^\infty \frac{v}{10^{m+kr}}\\&=\frac u{10^{m}}+\frac{v}{10^{m+r}}\sum_{k=0}^\infty \frac{1}{10^{kr}}=\frac{u}{10^{m}}+\frac{v}{10^{m+r}}\frac{1}{1-10^{-r}}.
\end{align*}
Ora note apenas que o número no lado direito da última equação é um número racional.

2. Assuma que $0< a<b$ e considere o racional $q=a/b$. Vamos determinar a sequência de algarismos para $q$. Seja $a_0=a$, $q_0=0$ e escreva, usando o Teorema de Divisão de Euclides,
$$
10a_0=q_1b+a_1\quad\mbox{onde}\quad 0\leq a_1<b.
$$
Assuma que as sequências $a_0,\ldots,a_k$ e $q_0,\ldots,q_k$ são determinadas, e defina $q_{k+1}$ e $a_{k+1}$ pela equação
$$
10a_k=q_{k+1}b+a_{k+1}\quad\mbox{onde}\quad 0\leq a_{k+1}<b
$$
usando o Teorema de Divisão de Euclides.

Afirmamos que a expansão decimal de $a/b$ é $[0,q_1q_2\cdots]$. Para isso nós precisamos verificar que
$$
\sum_{k=1}^\infty q_k10^{-k}\to \frac ab.
$$
De fato, nós provaremos que
$$
10^k a=\sum_{i=1}^k10^{k-i}q_ib+a_k
$$
Para $k=1$, esta afirmação segue da expressão acima para $10a_0=10a$. Assuma que esta igualdade é verdadeira para algum $k$. Então
\begin{align*}
10^{k+1}a&=10\cdot 10^ka=10\cdot\left(\sum_{i=1}^k10^{k-i}q_ib+a_k\right)
\\&=\sum_{i=1}^{k}10^{k+1-i}q_ib+10a_k\\&=
\sum_{i=1}^{k}10^{k+1-i}q_ib+q_{k+1}b+a_{k+1}\\&=\sum_{i=1}^{k+1}10^{k+1-i}q_ib+a_{k+1}.
\end{align*}
Então a afirmação é verdadeira para todo $k$. Segue, para todo $k\geq 1$, da mesma afirmação que
$$
\frac ab=\sum_{i=1}^k10^{-i}q_i+a_k/(10^kb)=[0,q_1\cdots q_k]+\frac{a_k}{10^kb};
$$
e assim
$$
\frac ab-[0,q_1\cdots q_k]=\frac{a_k}{10^kb}<\frac{b}{10^kb}=10^{-k}.
$$
Isso implica que a sequência $[0,q_1\cdots q_k]$ converge para $a/b$ quando $k\to\infty$ e então a expansão do número racional $a/b$ é $[0,q_1q_2\cdots]$.

Finalmente precisamos provar que a expansão $[0,q_1q_2\cdots]$ de $a/b$ é periódica. Para isso, note que a sequência $a_1,a_2,\ldots$ é uma sequência de números naturais com $a_i\in\{0,\ldots,b-1\}$ para todo $i$. Então vai existir $m$ e $r$ tal que $a_{m+r}=a_m$. Logo
$$
q_{m+r+1}b+a_{m+r+1}=10a_{m+r}=10a_m=q_{m+1}b+a_{m+1}.
$$
Obtemos pela unicidade na Teorema de Divisão de Euclides que $q_{m+r+1}=q_{m+1}$ e $a_{m+r+1}=a_{m+1}$. Similarmente, $q_{m+r+2}=q_{m+2}$ e $a_{m+r+2}=a_{m+2}$ e mais geralmente
$$
q_{k+r}=q_{k}\quad e \quad a_{k+r}=a_{k}.
$$
para todo $k\geq m+1$. Ou seja, a expansão do número $a/b$ é periódica.
:::


:::{#exm-}
A demonstração do resultado anterior dá um algoritmo para calcular a expansão de um número natural $a/b$ onde $0<a<b$. Considere por exemplo o racional $1/54$. Seguindo a demonstração do teorema para $a=1$ e $b=54$, fazemos a seguinte conta.\begin{align*}
10a=10=0\cdot 54+10\quad &\Rightarrow\quad q_1=0\mbox{ e }a_1=10\\
10a_1=100=1\cdot 54+46\quad &\Rightarrow\quad q_2=1\mbox{ e }a_2=46\\
10a_2=460=8\cdot 54+28\quad &\Rightarrow\quad q_3=8\mbox{ e }a_3=28\\
10a_3=280=5\cdot 54+10\quad &\Rightarrow\quad q_4=5\mbox{ e }a_4=10\\
10a_4=100=1\cdot 54+46\quad &\Rightarrow\quad q_5=1\mbox{ e }a_5=46
\end{align*}
Observamos que $a_4=a_1$ como foi previsto na demonstração do teorema e a computação vai se repetir a partir deste ponto. Obtemos então que
$$
\frac 1{54}=0,0\overline{185}.
$$
:::

Obtemos também como consequência do teorema anterior que existem números irracionais no intervalo $[0,1]$. Por exemplo, considere o número
$$
a=0,1010010001000010000010000001\cdots.
$$
Pelo lema anterior, $a$ é um número real, mas a sua expansão decimal não é periódoca, portanto este número não é racional.

Exatamente como a expansão dos números naturais pode ser calculada em qualquer base $d\geq 2$, a expansão dos números racionais também pode ser calculada em bases $d$ tal que $d\geq 2$. Os resultados em uma base arbitrária são muito similares aos resultados na base $d=10$ (caso decimal) e estes detalhes são omitidos. No entanto recomendamos que o leitor traduza os resultados acima para uma base $d\neq 10$.

