---
title: "Os números inteiros e racionais"
number-sections: true
lang: pt-BR
---

## Os números inteiros. 

Nas aulas anteriores, nós construímos os números naturais. Agora, vamos construir os números inteiros. 

Considere o conjunto $\N\times\N$ e considere a relação $\sim$ sobre $\N\times\N$ definida como 
$$
(a,b)\sim (c,d)\quad\mbox{quando}\quad a+d=b+c.
$$

:::{#lem-rel-int}
A relação $\sim$ é uma relação de equivalência. 
:::
:::{.proof}
Consulte o @exr-ntimesn
:::

Seja $(a,b)\in\N\times \N$. A classe de equivalência de $(a,b)$ será denotado por $[a,b]$. Por exemplo 
\begin{align*}
[1,1]&=\{(1,1),(2,2),(3,3),\ldots\}\\
[2,1]&=\{(2,1),(3,2),(4,3),\ldots\}\\
[1,2]&=\{(1,2),(2,3),(3,4),\ldots\}
\end{align*}
Observe que a classe $[1,1]$ contem os pares na form $(a,a)$; ou seja, os pares com os dois componentes iguals. A classe $[2,1]$ contem os pares na forma $[a+1,a]$; ou seja, os pares onde o primeiro componente é um maior que o segundo. A classe $[1,2]$ contém os pares na forma $(a,a+1)$ onde o segundo componente é um maior que o primeiro. Geralmente, temos uma classe na forma 
$$
[1,1]=\{(a,a)\mid a\in\N\}
$${#eq-pair-zero}
e as demais classes têm a forma 
$$
[1+k,1]=\{(a+k,a)\mid a\in \N\} 
$${#eq-pair-pos}
ou 
$$
[1,1+k]\{(a,a+k)\mid a\in \N\}.
$${#eq-pair-neg}
A ideia de construir os número inteiros é que a classe na @eq-pair-pos pode ser identificada com o número $k\in\N$, enquanto a classe na @eq-pair-zero pode ser identificada com um novo número que representa a ideia do zero, e a classe na @eq-pair-neg com um número que representa a ideia do negativo de $k$.

:::{#def-int}
Um número inteiro é uma classe de equivalência $[a,b]$ para a relação $\sim$. O conjunto dos inteiros é denotado por $\mathbb Z$. 
:::


:::{#def-int-ops}
Definimos as operações de $+$ e $\cdot$ entre elementos de $\Z$:

1. $[a,b]+[c,d]=[a+c,b+d]$;
2. $[a,b][c,d]=[ac+bd,ad+bc]$.
:::


:::{#lem-int-ops}
As operações $+$ e $\cdot$ são bem definidas; ou seja, o resultado não depende da escolha do representate da classe. Além disso, temos as seguintes propriedades para todo $x,y,z\in\Z$:

1. $(x+y)+z=x+(y+z)$;
2. $x+y=y+x$;
3. Existe elemento neutro para a soma. Nomeadamente, denotando $0=[1,1]$, temos que $x+0=0+x=x$;
4. $x$ possui negativo $-x$ que satisfaz $x+(-x)=0$;
5. $(xy)z=x(yz)$;
6. $xy=yx$;
7. Existe elemento neutro para o produto. Nomeadamente, denotando $1_\Z=[2,1]$, temos que $1_\Z x=x1_\Z=x$;
8. $x(y+z)=xy+xz$;
9. se $x+z=y+z$, então $x=y$;
10. se $xz=yz$ e $z\neq 0$, então $x=y$.
:::

:::{.proof}
Primeiro provaremos que as operações são bem definidas. Demonstramos isso para o produto, pois a soma é mais simples 
e o leitor poderá fazer. Assuma que $[a,b]=[a',b'],[c,d]\in\Z$. Precisa provar que o produto $[a,b][c,d]$ pode 
ser calculada também como $[a',b'][c,d]$ e o resultado vai ser o mesmo. De fato,
$$
[a,b][c,d]=[ac+bd,ad+bc]
$$
e
$$
[a',b'][c,d]=[a'c+b'd,a'd+b'c].
$$
Para provar que estes dois números são os mesmos, precisa verificar que 
$$
ac+bd+a'd+b'c=ad+bc+a'c+b'd.
$${#eq-prod-ver}
Como $[a,b]=[a',b']$, temos que $a+b'=a'+b$. Logo, 
$$
ac+bd+a'd+b'c=(a+b')c+(b+a')d=(a'+b)c+(a+b')d=ad+bc+a'c+b'd
$$
e a @eq-prod-ver está verificada. Pode provar com argumento similar, que se 
$[a,b],[c,d]=[c',d']\in\Z$, então $[a,b][c,d]=[a,b][c',d']$. 

Note que no ponto 4., o inverso de $x=[x_1,x_2]$ é $[x_2,x_1]$. De fato, 
$$
[x_1,x_2]+[x_2,x_1]=[x_1+x_2,x_2+x_1]=0.
$$

As demais afirmações são fáceis de provar usando as propriedades já provadas dos números naturais. 
Para ilustrar a técnica, vamos provar o  item 8 e o item 9. O resto é exercício para o leitor. 

Assuma que $x=[x_1,x_2]$, $y=[y_1,y_2]$, $z=[z_1,z_2]$ e vamos computar que 
\begin{align*}
x(y+z)&=[x_1,x_2]([y_1,y_2]+[z_1,z_2])=[x_1,x_2]([y_1+z_1,y_2+z_2])\\&=
[x_1(y_1+z_1)+x_2(y_2+z_2),x_1(y_2+z_2)+x_2(y_1+z_1)]\\&=
[x_1y_1+x_1z_1+x_2y_2+x_2z_2,x_1y_2+x_1z_2+x_2y_1+x_2z_1].
\end{align*}
Por outro lado, 
\begin{align*}
xy+xz&=[x_1,x_2][y_1,y_2]+[x_1,x_2][z_1,z_2]\\&=[x_1y_1+x_2y_2,x_1y_2+x_2y_1]+[x_1z_1+x_2z_2,x_1z_2+x_2z_1]\\&=
[x_1y_1+x_2y_2+x_1z_1+x_2z_2,x_1y_2+x_2y_1+x_1z_2+x_2z_1]
\end{align*}

Assuma que $x+z=y+z$. Sejam $x=[x_1,x_2]$, $y=[y_1,y_2]$, $z=[z_1,z_2]$ e assuma que 
$x+z=y+z$; ou seja, 
$$
[x_1+z_1,x_2+z_2]=[y_1+z_1,y_2+z_2].
$$
Logo, 
$$
x_1+z_1+y_2+z_2=x_2+z_2+y_1+z_1.
$$
Ora, usamos a lei cancelativa para números naturais e obtemos que 
$$
x_1+y_2=x_2+y_1;
$$
ou seja, $x=[x_1,x_2]=[y_1,y_2]=y$. 
:::

:::{#def-int-pos}
Seja $x=[x_1,x_2]$. 

1. Se $x_2<x_1$, então $x$ chama-se *positivo*.
2. Se $x_1<x_2$, então $x$ chama-se *negativo*.

Segue da definição da igualdade entre números inteiros que a positividade do número está bem definida; 
ou seja, ela não depende da escolha do representante. 

Se $x,y\in\Z$, dizemos que $x<y$ se $y-x=y+(-x)$ é positivo. Dizemos que $x\leq y$ se $x=y$ ou $x<y$. 
:::

:::{#lem-int-pos}
Sejam $x,y,z\in\Z$ As seguinte propriedades estão válidas. 

1. $x\leq x$;
2. se $x\leq y$ e $y\leq x$, então $x=y$;
3. se $x\leq y$ e $y\leq z$, então $x\leq z$; 
4. se $x\leq y$, então $x+z\leq y+z$; 
5. se $x\leq y$ e $z$ é positivo, então $xz\leq yz$;
6. se $x\leq y$ e $z$ é negativo, então $yz\leq xz$;
7. temos que exatamente uma das alternativas $x<y$ ou $x=y$ ou $y<x$ está válida.
:::
:::{.proof}
Provaremos por exemplo o item 5. Assuma que $x\leq y$ e $z$ é positivo. Se $x=y$, então não tem nada para provar e assuma que 
$x<y$. Logo, $y-x$ é positivo. Colocando, $x=[x_1,x_2]$, $y=[y_1,y_2]$, $z=[z_1,z_2]$, temos que 
$$
y-x=[y_1,y_2]+[x_2,x_1]=[y_1+x_2,y_2+x_1].
$$
Pela positividade, obtemos que $y_1+x_2>y_2+x_1$. 
Como $z$ é positivo, temos que $z=[1+a,1]$ e assim 
\begin{align*}
(y-x)z&=[(y_1+x_2)(1+a)+y_2+x_1,y_1+x_2+(y_2+x_1)(1+a)]\\&=
[y_1+x_2+ay_1+ax_2+y_2+x_1,y_1+x_2+y_2+x_1+y_2a+x_1a]\\&=
[ay_1+ax_2,y_2a+x_1a]=[a(y_1+x_2),a(y_2+x_1)].
\end{align*}
Ora, a compatibilidade das operações com a ordenação dos naturais implica que $a(y_1+x_2)>a(y_2+x_1)$. 
Ou seja, $yz-xz=(y-x)z$ é positivo e $xz<yz$. 
:::

O @lem-int-pos diz que a relação $\leq$ é uma relação de ordem total no conjunto $\Z$ que é compatível com 
as operações.

## Os números racionais

Vamos agora ver como definir os números racionais. Aqui vamos dar as definições e resultados principais; as demonstrações serão feitas pelo leitor. 

:::{#def-rat-rel}
Considere o conjunto $\Z\times\Z\setminus\{0\}$ e seja $\sim$ a relação em $\Z\times\Z\setminus\{0\}$ definida pela regra que 
$$
(a,b)\sim (c,d)\quad\mbox{quando}\quad ad=bc.
$$ 
:::

:::{#lem-rat-equiv}
A relação $\sim$ é uma relação de equivalência no conjunto $\Z\times\Z\setminus\{0\}$. Se $(a,b)\in\Z\times\Z\setminus\{0\}$, então a sua classe de equivalência será denotada por $[a,b]$. 
:::

:::{#def-rat}
Um número racional é uma classe de equivalência $[a,b]$. O conjunto dos números racionais é denotado por $\Q$. 
:::

:::{#def-rat-ops}
As operações $+$ e $\cdot$ serão definidas entre números racionais $[a,b],[c,d]\in\Q$ com as seguintes regras:
\begin{align*}
[a,b]+[c,d]&=[ad+cb,bd];\\
[a,b][c,d]&=[ac,bd].
\end{align*}
:::

:::{#lem-rat-ops}
As operações na @def-rat-ops são bem definidas; ou seja, o resultado não depende da escolha dos representantes das classes de equivalência. Além disso, elas satisfazem as seguintes propriedades para todo $a,b,c\in\Q$.

- **(A1):** $(a+b)+c=a+(b+c)$;
- **(A2):** $a+b=b+a$;
- **(A3):** existe $0_\Q\in\Q$ tal que $a+0_\Q=0_\Q+a=a$; 
- **(A4):** para todo $a\in\Q$ existe $-a\in\Q$ tal que $a+(-a)=0_\Q$;
- **(M1):** $(ab)c=a(bc)$;
- **(M2):** $ab=ba$;
- **(M3):** existe $1_\Q\in\Q$ tal que $a1_\Q=1_\Q a=a$; 
- **(M4):** para todo $a\in\Q\setminus\{0_\Q\}$ existe $a^{-1}\in\Q$ tal que $aa^{-1}=1_\Q$;
- **(D):** $(a+b)c=ac+bc$.
:::
:::{.proof}
É tarefa do leitor. Só vamos comentar que $0_\Q=[0,1]$, $1_\Q=[1,1]$, se $a=[x,y]$, então $-a=[-x,y]$ e se $a\neq [0,1]$, então $a^{-1}=[y,x]$.
:::

Nós escrevemos o número racional $[x,y]$ como $x/y$. Os números $0_\Q$ e $1_\Q$ serão escritos simplesmente como $0$ e $1$. Note, para $k\in \Z$ que o número $[k,1]=k/1$ pode ser identificado com o inteiro $k$. Assim, podemos pensar os inteiros como números racionais e escrever que $\Z\subseteq\Q$. Se $a,b\in\Q$, então $a+(-b)$ será escrito como $a-b$ e $ab^{-1}$ será escrito como $a/b$.  

Entre os números racionais, podemos definir os números não negativos como 
$$
\Q^+=\{a/b\in \Q\mid a,b\geq 0\mbox{ e }b\neq 0\}
$$

:::{#lem-qplus}
Temos que $\Q^+$ satisfaz as seguintes propriedades.

- **(O1):** Se $a,b\in\Q^+$, então $a+b,ab\in\Q^+$;
- **(O2):** Se $a\in\Q$, então $a\in\Q^+$ ou $-a\in\Q^+$;
- **(O3):** $\Q^+\cap\{x\in\Q\mid -x\in\Q^+\}=\{0\}$.
:::

:::{#def-order-q}
Defina para $a,b\in\Q$ a relação $a\leq b$ para significar que $b-a\in\Q^+$. 
:::

:::{#lem-order-q}
Temos que $\leq$ é uma ordem total no conjunto $\Q$. Ou seja, temos para todo $a,b,c\in\Q$, que 

1. $a\leq a$;
2. se $a\leq b$ e $b\leq a$, então $a=b$;
3. se $a\leq b$ e $b\leq c$, então $a\leq c$;
4. temos que ou $a\leq b$ ou $b\leq a$ vale.
   
Além disso, a relação $\leq$ é compatível com as operações. Ou seja, 

1. se $a\leq b$, então $a+c\leq b+c$;
2. se $a\leq b$ e $c\in\Q^+$, então $ac\leq bc$. 
:::