--- 
title: "Autovalores e autovetores"
number-sections: true
lang: pt-BR
--- 

:::{#exm-autoval-refl}
Considere a transformação $R:\R^2\to \R^2$ onde $R(v)$ é a reflexão de $v$ no eixo que tem $30$ graus com o eixo-$x$. A matriz da transformação na base canônica é
$$
\begin{pmatrix} 1/2 & \sqrt{3}/2\\ \sqrt{3}/2 & -1/2 \end{pmatrix}.
$$
Ou seja, esta é uma matriz complicada. Por outro lado, se usarmos a base que contém o eixo da reflexão e uma outro vetor perpendicular ao eixo, temos que a matriz da transformação fica na forma
$$
\begin{pmatrix} 1 & 0\\ 0 & -1 \end{pmatrix}.
$$
:::

Escolhendo os vetores na maneira "certa", a matriz da transformação fica bem mais simples. Nesta parte da disciplina nós vamos estudar


 -  como escolher a base de um espaço vetorial para que a matriz de um endomorfismo seja a mais simples possível;
 -  até qual ponto pode a matriz de um endomorfismo ser simplificada.


:::{#def-}
Seja $f:V\to V$ um endomorfismo de um $\F$-espaço vetorial $V$. Seja $\lambda\in\F$. Se $v\in V$ tal que $f(v)=\lambda v$, então $v$ chama-se **autovetor** de $f$. Se $v\neq 0$, então $\lambda$ chama-se **autovalor** de $\F$. Nós escrevemos
$$
V_\lambda=\{v\in V\mid f(v)=\lambda v\}.
$$
O espaço $V_\lambda$ chama-se **autoespaço** de $f$ associado com o autovalor $\lambda$. Note que $0\in V_\lambda$ vale para 
todo $\lambda$.   Temos que $\lambda$ é autovalor de $f$ se e somente se $V_\lambda\neq 0$.

:::


:::{#exr-}
Mostre que $V_\lambda\leq V$. Sejam $\lambda_1,\ldots,\lambda_k\in\F$ distintos. Mostre que
$$
V_{\lambda_1}+\cdots+V_{\lambda_k}=V_{\lambda_1}\oplus\cdots\oplus V_{\lambda_k}.
$$
:::

:::{#exm-}
Considere os seguintes exemplos. 

1.  No @exm-autoval-refl, o eixo da reflexão é um autovetor com autovalor $1$ enquanto um vetor perpendicular ao eixo é autovetor com autovalor $-1$.
2.  Se $f:C^\infty(\R)\to C^\infty(\R)$  é a derivação ($C^\infty(\R)$ sendo o espaço de funções reais infinitamente deriváveis), então a função $x\mapsto \exp(\lambda x)$ é autovetor com autovalor $\lambda$.
3.  Se $f:V\to V$ é um endomorfismo, então $V_0=\ker f$.
:::


:::{#def-}
Um endomorfismo $f:V\to V$ de um espaço vetorial $V$ de dimensão finita é chamada <b>diagonalizável</b> se $V$ possui uma base formada por autovetores de $f$.
:::

O endomorfismo no primeiro exemplo é diagonalizável.

Se $V$ é um espaço de dimensão finita e $f:V\to V$ é um endomorfismo, o determinante de $f$ pode ser 
definido como na @def-determinant-f. Na prática, nós  calculamos $\det f$ como o determinante $\det [f]^B_B$ da matriz de $f$ em uma base $B$ 
de $V$. Pelas regras da mudança de base (@lem-base-change), $\det f$ é independente da escolha de $B$.


:::{#lem-eigen}
Seja $f:V\to V$ um endomorfismo e $\lambda\in\F$. As seguintes afirmações são verdadeiras:

1. $V_\lambda=\ker(\lambda\cdot \mbox{id}_V-f)$.
2. Assumindo que $\dim V$ é finita, $\lambda$ é autovalor de $f$ se e somente se $\det(\lambda\cdot \mbox{id}_V-f)=0$.
:::


:::{.proof}
1. Seja $v\in V$. Então $f(v)=\lambda v$ se e somente se $\lambda v-f(v)=0$ que é e mesma coisa que $\lambda\mbox{id}_V(v)-f(v)=0$. A última equação pode ser escrita na forma $(\lambda\mbox{id}_V-f)(v)=0$; ou seja, $v\in \ker (\lambda\cdot \mbox{id}_V-f)$.

2. $\lambda$ é autovalor de $f$ se e somente se $V_\lambda\neq 0$ que equivale à afirmação $\ker(\lambda\mbox{id}_V-f)\neq 0$; ou seja $\lambda\mbox{id}_V-f$ não é invertível, ou equivalentemente, $\det(\lambda\mbox{id}_V-f)=0$.
:::


:::{#exm-eigen-2x2}
Seja $f:\F^2\to \F^2$ definida por $f(x,y)=(x+y,y)$. A matriz de $f$ na base canônica é
$$
\begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}
$$
Se $\lambda\in\F$, então $\lambda$ é autovalor de $f$ se e somente se
$$
0=\det\begin{pmatrix} \lambda-1 & -1 \\ 0 & \lambda-1 \end{pmatrix}=(\lambda-1)^2.
$$
Obtemos que $\det(\lambda\mbox{id}_V-f)=0$ apenas para $\lambda=1$. Então o único autovalor de $f$ é $\lambda=1$. Neste caso, o autoespaço $V_1$ coincide com o núcleo da matriz
$$
\begin{pmatrix} 0 & -1 \\ 0 & 0 \end{pmatrix}
$$
que é $\langle(1,0)^t\rangle$. Obtemos que os autovetores de $f$ são os múltiplos de $(1,0)^t$, então não existe base de $V$ tal que a matriz desta transformação seja diagonalizável. Ou seja, $f$ não é diagonalizável.
:::


:::{#def-carpol}
Seja $V$ um $\F$-espaço de dimensão finita e seja $f:V\to V$ um endomorfismo. Seja $t$ uma incôgnita sobre o corpo $\F$. Então o determinante $\det(t\cdot \mbox{id}_V-f)$ pode ser visto como um polinômio em $\F[t]$. Este polinômio chama-se o<b> polinômio caraterístico</b> de $f$ e está escrito como $\mbox{pcar}_f(t)$.
:::

Note que para calcular o polinômio caraterístico, precisa-se escolher uma base de $V$, mas o resultado será independente da escolha da base 
(por @lem-base-change).

:::{#exm-}
No @exm-eigen-2x2, $\mbox{pcar}_f(t)=(t-1)^2$.
:::

O polinômio caraterístico é um polinômio mônico de grau $n=\dim V$:
$$
\mbox{pcar}_f(t)=t^n+\alpha_{n-1}t^{n-1}+\cdots+\alpha_1t+\alpha_0\in\F[t].
$$

:::{#cor-}
Seja $V$ um espaço vetorial de dimensão $n$ (finita) sobre um corpo $\F$ e seja $f:V\to V$ um endomorfismo.

1. O conjunto dos autovalores de $f:V\to V$ é igual ao conjunto das raízes do seu polinômio caraterístico.
2. $f$ possui no máximo $n$ autovalores distintos.
3. Se $\F=\C$, então $f$ possui pelo menos um autovalor.
:::
:::{.proof}
1. Segue do @lem-eigen e da @def-carpol.
2. Segue do fato que o polinômio caraterística tem grau igual à $\dim V=n$ e um polinômio de grau $n$ em $\F[x]$ pode ter no máximo $n$ raízes distintas (@cor-nr-roots). 
3. Se $\F=\C$, então o Teorema Fundamental da Álgebra diz que todo polinômio de grau maior ou igual a um tem raíz complexa (@thm-fundamental-da-algebra). Esta raiz é autovalor de $f$.
:::

:::{#def-}
O conjunto dos autovalores de $f$ chama-se o <b>espectro</b> de $f$. A <b>multiplicidade algébrica</b> de um autovalor $\lambda$ é a multiplicidade como raiz de $\mbox{pcar}_f(t)$. A <b>multiplicidade geométrica</b> é $\dim V_\lambda$.
:::


:::{#lem-}
A multiplicidade geométrica de um autovalor de um endomorfismo é menor ou igual a sua multiplicidade algébrica.
:::


:::{.proof}
Exercício: Use uma base que contém uma base para $V_\lambda$ para calcular o polinômio caraterístico.
:::

