--- 
title: "Operadores autoadjuntos e normais"
number-sections: true
lang: pt-BR
--- 

## Operadores autoadjuntos

Nesta página $V$ é um $\F$-espaço vetorial, $\sigma\in\mbox{Aut}(\F)$ com $\sigma^2=\mbox{id}_\F$ e $B$ é uma forma $\sigma$-hermitiana não degenerada sobre $V$.

:::{#def-}
Um operador $f:V\to V$ é **autoadjunto** se existe $f^*$ e $f^*=f$. Em outras palavras,
$$
B(f(v),w)=B(v,f(w))
$$
para todo $v,w\in V$.
:::


:::{#lem-}
Seja $f:V\to V$ autoadjunto.


1.  Se $\lambda\in\F$ é um autovalor de $f$ tal que $V_\lambda$ contém um vetor não isotrópico, então $\lambda\in\mbox{Fix}(\sigma)$.
2.  Sejam $v_1$ e $v_2$  autovetores de $f$ associados com autovalores $\lambda_1$ e $\lambda_2$, respetivamente, tais que $\lambda_1^\sigma\neq \lambda_2$. Então $v_1\perp v_2$ (ou seja, $B(v_1,v_2)=0$).
:::


:::{.proof}
1. Seja $v\in V\setminus\{0\}$ tal que $f(v)=\lambda v$ e assuma que $v$ não é isotrópico; ou seja $Q(v)=B(v,v)\neq 0$. Ora,
$$
\lambda B(v,v)=B(\lambda v,v)=B(f(v),w)=B(v,f(v))=B(v,\lambda v)=\lambda^\sigma B(v,v).
$$
Portanto, $(\lambda-\lambda^\sigma)B(v,v)=0$ e $\lambda-\lambda^\sigma=0$. Logo $\lambda=\mbox{Fix}(\sigma)$.
2. Assuma que $v_1$ e $v_2$ são autovetores associados com autovalores $\lambda_1$ e $\lambda_2$ com $\lambda_1\neq \lambda_2^\sigma$. Temos que
\begin{align*}
\lambda_1 B(v_1,v_2)&=B(f(v_1),w_2)=B(v_1,f(v_2))=B(v_1,\lambda_2 v_2)\\&=\lambda_2^\sigma B(v_1,v_2).
\end{align*}
Isso implica que $(\lambda_1-\lambda_2^\sigma)B(v_1,v_2)=0$. Ou seja, $\lambda_1=\lambda_2^\sigma$ ou $B(v_1,v_2)=0$.
Como $\lambda_1\neq \lambda_2^\sigma$, nos resta que $B(v_1,v_2)=0$.
:::

## Produto interno

:::{#def-}
Seja $V$ um espaço vetorial sobre $\F$ onde $\F=\R$ ou $\F=\C$ e seja $\sigma=\mbox{id}_\R$ se $\F=\R$ e $\sigma$ o conjugado complexo se $\F=\C$. Um **produto interno** sobre $V$ é uma forma $\sigma$-hermitiana que satisfaz a propriedade de positividade; ou seja,
$$
Q(v)=B(v,v)\geq 0\quad\mbox{para todo}\quad v\in V
$$
e $Q(v)=0$ se e somente se $v=0$. Neste caso dizemos que $V$ é um **espaço com produto interno**. A forma $B(-,-)$ é frquentamente escrita como $\langle -,-\rangle$. Se $V$ é espaço com produto interno e $v\in V$, então $Q(v)\geq 0$ e definimos
$$
\|v\|=\sqrt{Q(v)}=\sqrt{\langle v,v\rangle}\in \R.
$$
O número $\|v\|$ é chamado **norma** de $v$. Temos que $\|v\|\geq 0$ e $\|v\|=0$ se e somente se $v=0$.
:::


:::{#lem-}
Uma forma $B$ que define produto interno é não degenerada. Além disso, se $\dim V=n$ for finita, então $(V,B)$ é isométrico ao espaço $\R^{0+n}$ ou $\C^{0+n}$.
:::


:::{.proof}
Se $v\in\mbox{Rad}(B)$, então $v\perp v$ e $Q(v,v)=B(v,v)=0$. Logo, $v=0$ e $B$ é não degenerada.

Sabe-se do resultado anterior que quando $\dim V=n$ finita, então $(V,B)$ é isométrica ao espaço $\R^{p+q}$ ou $\C^{p+q}$ com $p+q=n$. Se $p\geq 1$, então $B(b_1,b_1)=-1$, que não é possível pela positividade da forma.

:::

Note que a notação $\langle u,v\rangle$ foi usada anteriormente para o espaço gerado por $u$ e $v$. A partir deste ponto, este espaço será denotado por $\mbox{span}\langle u,v\rangle$.

:::{#cor-}
Assuma que $V$ é espaço com produto interno e $f:V\to V$ é autoadjunto.


1.  Os autovalores de $v$ são números reais.
2.  Se $v_1$ e $v_2$ são autovetores de $f$ com autovalores distintos, então $v_1\perp v_2$.
:::


:::{.proof}
1. Se $v$ é uma autovetor não nulo de $f$ com autovalor $\lambda$, então $v$ não é isotrópico (pela positividade do produto interno) e temos pelo lema anterior que $\lambda\in\mbox{Fix}(\sigma)=\R$.

2. Sejam $v_1$ e $v_2$ autovetores de $f$ com autovalores distintos $\lambda_1$ e $\lambda_2$, respetivamente. Temos pelo item 1. que $\lambda_1,\lambda_2\in\R$ e $\lambda_1\neq \lambda_2^\sigma=\lambda_2$. O lema acima implica que $v_1\perp v_2$.
:::


## Diagonalização de operadores autoadjuntos

:::{#cor-}
Seja $A\in M_{n\times n}(\C)$ tal que $A^t=\overline A$ (a transposta é igual à conjugada complexa). Então os autovalores de $A$ são números reais. Em particular, se $A\in M_{n\times n}(\R)$ tal que $A^t = A$ e $\lambda\in\C$ é autovalor de $A$, então $\lambda\in \R$.
:::


:::{.proof}
Considere $A$ como a matriz de uma transformação linear $f_A:\C^n\to \C^n$ em uma base ortonormal em relação ao produto interno usual de $\C^n$. A matriz de $f_A^*$ é $\overline A^t=A$ e assim $f_A^*=f_A$; ou seja $f_A$ é autoadjunta. Pelo resultado anterior os autovalores de $f_A$ (que são os mesmos que os autovalores de $A$) são números reais. A segunda afirmação segue da primeira, observando que se $A\in M_{n\times n}(\R)$, então $\overline A=A$.
:::


:::{#thm-diag-selfadj}
(O Teorema de Diagonalização para Operadores Autoadjuntos)
Seja $V$ um espaço com produto interno e assuma que $\dim V=n$ é finita e seja $f:V\to V$ um operador autoadjunto. Então os autovalores de $f$ são números reais e $V$ possui uma base $B$ ortonormal formada por autovetores de $f$. Em particular, $f$ é diagonalizável e $[f]_B^B=D$ é diagonal.
:::


:::{.proof}
Usamos indução por $\dim V$. Seja $\F=\R$ ou $\F=\C$ o corpo para o espaço $V$. Quando $\dim V=1$, então $(V,\langle-,-\rangle)$ é isométrico ao espaço $\F^{0+1}$ e existe uma base $\{b_1\}$ tal que $\langle b_1,b_1\rangle=1$. Como $\dim V=1$, $b_1$ é autovetor de $f$ e a base $\{b_1\}$ é ortonormal formada por autovetores de $f$.

Assuma que o teorema está verdadeiro para espaços de dimensão menor que $n$ e assuma que $\dim V=n$. Seja inicialmente $X$ uma base ortonormal de $V$ qualquer (existe por resultado anterior). A matriz $A$ de $f$ nesta base $X$ satisfaz $X^t=\overline X$ (ou $X^t=X$ quando $\F=\R$). Por resultado anterior $A$ e $f$ possuem autovalor $\lambda\in \R$. Seja $b_1'$ um autovetor para autovalor $\lambda$. Ponha $\alpha_1=\langle b_1',b_1'\rangle$ e note que a positividade do produto interno implica que $\alpha_1\in \R$ e $\alpha_1 > 0$. Pondo $b_1=(\alpha_1)^{-1/2}b_1'$ obtemos que $\langle b_1,b_1\rangle =1$.

Considere $U=\mbox{span}\{b_1\}$. Então $\dim U^\perp=n-1$, $U^{\perp}\cap U=0$ e $V=U\perp U^\perp$. Além disso, $U$ sendo $f$-invariante, $U^\perp$ é invariante por $f^*=f$. Por hipótese de indução, $U^\perp$ possui uma base ortonormal $\{b_2,\ldots,b_n\}$ que composta de autovetores de $f$. Ora, $\{b_1,\ldots,b_n\}$ é base ortonormal de $V$ composta de autovetores de $f$.
:::


## Diagonalização de matrizes simétricas e hermitianas.

:::{#def-}
Para uma matriz $A\in M_{n\times n}(\C)$, denotamos $A^*=\overline A^t$ (conjugada transposta). 

1. Uma matrix $A\in M_{n\times n}(\F)$ ($\F$ é corpo qualquer) é chamada **simétrica** se $A=A^t$.
1. Uma matrix $A\in M_{n\times n}(\C)$ é chamada **hermitiana** se $A=A^*$. 
2. Uma matriz $A\in M_{n\times n}(\R)$ é chamada **ortogonal** se as colunas de $A$ são ortonormais. 
3. Uma matriz $A\in M_{n\times n}(\C)$ é chamada de **unitária** as colunas de $A$ são ortonormais (no produto interno de $\C^n$).
:::


:::{#exr-}
Mostre que

1.  $A$ é ortogonal se e somente se $A^tA=I$ e $A^{-1}=A^t$;
2.  $A$ é unitária se e somente se $A^*A=I$ e $A^{-1}=A^*$.
:::


:::{#cor-}
1.  Seja $A\in M_{n\times n}(\R)$ uma matriz simétrica. Existe uma matriz ortogonal $P$ tal que $P^tAP$ é diagonal.
2.  $A\in M_{n\times n}(\C)$ uma matriz hermitiana. Existe uma matriz unitária $P$ tal que $P^*AP$ é diagonal.
:::


:::{.proof}
Nos dois casos, considere a transformação $f_A:\F^n\to \F^n$, $f_A(v)=A\cdot v$. A transformação $f_A$ é autoadjunta em relação ao produto interno em $\F^n$. Além disso, a matriz de $f_A$ na base canônica é a própria $A$. Pelo teorema anterior, $f_A$ é diaganalizável. Mais precisamente, existe uma base ortonormal $B$ tal que $[f_A]_B^B$ é diagonal $D$. Seja $P$ a matriz que tem os elementos de $B$ nas suas colunas. Temos que
$$
D=[f]_B^B=P^{-1}AP=P^*AP
$$
pois $P^{-1}=P^*$  pelo exercício anterior. Quando $P\in M_{n\times n}(\R)$, então $P^*=P^t$.
:::


:::{#exm-}
O teorema anterior não é válido para matrizes simétricas sobre $\C$. Considere por exemplo
$$
A=\begin{pmatrix} 1 & i \\ i & -1\end{pmatrix}
$$
O polinômio caraterístico de $A$ é $t^2$ e $0$ é o único autovalor de $A$. Mas como $A$ não é a transformação nula, não existe base de $\C^2$ formada por autovetores de $A$.
:::


## Operadores normais

No resto da página, $\F=\R$ ou $\F=\C$ e $V$ é um $\F$-espaço com produto interno $\langle -,-\rangle$. Alguns resultados são válidos para espaços vetoriais sobre corpos arbitrários com formas $\sigma$-hermitianas, mas nós vamos trabalhar com as suposições da frase anterior.

:::{#def-}
Um operador $f:V\to V$ é dito normal se existe $f^*$ e $ff^*=f^*f$. Ou seja, um operador é normal se e somente se existe o adjunto e  ele comuta com seu adjunto.
:::


:::{#lem-}
Seja $f:V\to V$ um operador.

1.  Se $f$ é autoadjunto, então $f$ é normal.
2.  Se $\dim V$ é finita e $f$ é diagonalizável por uma base ortonormal, então $f$ é normal.
:::


:::{.proof}
A primeira afirmação é óbvia, pois $f$ e $f$ claramente comutam. Para a segunda afirmação,  assuma que existe uma base ortonormal $\{b_1,\ldots,b_n\}$ de $V$ composta de autovetores de $f$. A matriz de $f$ nesta base é uma matriz diagonal $D$ com os autovalores $\lambda_1,\ldots,\lambda_n$ no diagonal principal. Na mesma base, a matriz $\overline D$ de $f^*$ é diagonal com $\overline \lambda_1,\ldots,\overline \lambda_n$ no diagonal principal. Como as matrizes diagonais $D$ e $\overline D$ comutam, temos que $f$ também comuta com $f^*$.
:::


:::{#exm-}
Um operador normal não precisa ser autoadjunto. Considere por exemplo o operador $R_\alpha:\R^2\to \R^2$ que é a rotação por $\alpha$ graus. A matriz deste operador na base canônica (que é ortonormal) é
$$
\begin{pmatrix}
\cos\alpha &-\mbox{sen}\,\alpha\\ \mbox{sen}\,\alpha & \cos\alpha\end{pmatrix}.
$$
A matriz da adjunta de $R_\alpha$ na mesma base é
$$
\begin{pmatrix}
\cos\alpha &\mbox{sen}\,\alpha\\ -\mbox{sen}\,\alpha & \cos\alpha\end{pmatrix};
$$
ou seja, $(R_\alpha)^*=R_{-\alpha}$. Como rotações do plano comutam, $R_\alpha$ comuta com $R_\alpha^*=R_{-\alpha}$ e $R_\alpha$ é normal. Por outro lado se $\alpha$ não é múltipo de $180$ graus, $R_\alpha\neq R_{-\alpha}$ e neste caso $R_\alpha$ não é autoadjunto.
:::

## Diagonalização de operadores normais


:::{#lem-}
Assuma que $f:V\to V$ é normal.


1. $\|f(v)\|=\|f^*(v)\|$ para todo $v\in V$.
2.  Se $v$ é autovetor de $f$ com autovalor $\lambda$, então o mesmo $v$ é autovetor de $f^*$ com autovalor $\overline\lambda$.
3.  Se $v_1$ e $v_2$ são autovetores de $f$ com autovalores $\alpha_1$ e $\alpha_2$ distintos, então $v_1\perp v_2$.
:::


:::{.proof}
1. Seja $v\in V$. Então
\begin{align*}
\|f(v)\|^2&=\langle f(v),f(v)\rangle =\langle v,f^*(f(v))\rangle=\overline{\langle f(f^*(v),v\rangle}\\&=\overline{\langle f^*(v),f^*(v)\rangle}\\&=\overline{\| f^*(v)\|^2}=\|f^*(v)\|^2.
\end{align*}

1. Assuma que $f(v)=\lambda v$; ou seja $(f-\lambda\mbox{id})(v)=0$. Obtemos que $\|(f-\lambda\mbox{id})(v)\|=0$. Pelo item anterior, $\|(f-\lambda\mbox{id})^*(v)\|=0$. Então $(f-\lambda\mbox{id})^*(v)=0$; ou seja, $f^*(v)=\overline \lambda v$.

2. Temos que
$$
\alpha_1\langle v_1,v_2\rangle =\langle f(v_1),v_2\rangle=\langle v_1,f^*(v_2)\rangle = \alpha_2 \langle v_1,v_2\rangle.
$$
Logo $(\alpha_1-\alpha_2)\langle v_1,v_2\rangle=0$ e obtemos que $\langle v_1,v_2\rangle=0$.
:::


:::{#thm-}
Seja $V$ um $\C$-espaço de dimensão finita e $f:V\to V$ um operador. Existe uma base ortonormal formada por autovetores de $V$ se e somente se $f$ é um operador normal.
:::


:::{.proof}
Já vimos que quando existe uma base ortonormal formada por autovetores de $f$, então $f$ é normal.

A outra direção será demonstrada por indução na dimensão de $V$. Quando $\dim V=1$, então escolhe qualquer vetor não nulo $v\in V\setminus\{0\}$ e tome $\|v\|^{-1}v$ para base ortonormal formada por autovetores de $f$. Assuma que o resultado vale para espaços de dimensão $n-1$ e assuma que $\dim V=n$. Como o corpo é $\C$, $f$ possui autovalor $\lambda$ e seja $v\in V$ um autovetor não nulo. Seja $b_1=\|v\|^{-1}v$ um vetor unitário. Considere $U=\langle v\rangle$ e $W=U^\perp$. Note que $U$ é $f$-invariente. Mas $U$ também é $f^*$-invariante, pois $b_1$ é autovetor de $f^*$ com autovalor $\overline \lambda$. Assim, um resultado anterior implica que $W$ é $f$-invariante (pois $f=(f^*)^*$). As restrições de $f$ e $f^*$ para $W$ claramente comutam e $(f|_W)^*=(f^*)|_W$. Logo, a hipótese da indução é válida para $f|_W$ e $W$ e $W$ possui uma base $\{b_2,\ldots,b_n\}$ ortonormal formada por autovetores de $f$. Ora, $\{b_1,\ldots,b_n\}$ é a base procurada.
:::


:::{#exm-}
Seja $f:\C^2\to \C^2$ o operador com matriz
$$
A=\begin{pmatrix} 1 & i \\ i & 1\end{pmatrix}
$$
na base canônica. Note que a matriz de $f^*$ é
$$
A^*=\begin{pmatrix} 1 & -i \\ -i & 1\end{pmatrix}
$$
e $f$ não é autoadjunto. Mas
$$
AA^*=A^*A=\begin{pmatrix} 2 & 0 \\ 0 & 2\end{pmatrix}
$$
e $f$ é normal. Note que os autovalores de $f$ são raízes do polinômio caraterístico $t^2-2t+2$ que são $1\pm i$. Os autovetores ortonormais correspondentes são $(1/\sqrt{2})(1,1)$ e $(1/\sqrt{2})(1,-1)$. Logo pondo
$$
P=\frac 1{\sqrt 2}\begin{pmatrix} 1 & 1 \\ 1 & -1\end{pmatrix}
$$
temos que
$$
P^*AP=\begin{pmatrix} 1+i & 0 \\ 0 & 1-i\end{pmatrix}
$$
:::
