--- 
title: "O Teorema de Cayley-Hamilton"
number-sections: true
lang: pt-BR
--- 

:::{#thm-}
(<a href="https://en.wikipedia.org/wiki/Cayley%E2%80%93Hamilton_theorem">Cayley-Hamilton</a>)
Seja $f:V\to V$ um endomorfismo com $\dim V=n$ (finita). Então $\mbox{pcar}_f(f)=0$. Em particular, $m_f(t)\mid \mbox{pcar}_f(t)$.
:::

Existem várias demonstrações do Teorema (veja a página da Wikipédia refenciada em  cima), e todas têm as suas vantagens e desvantagens. Algumas demonstrações são mais elementares, mas as computações são mais complicadas, algumas são computacionalmente mais simples, mas usam teoria mais profunda, outras funcionam apenas sobre corpo algebricamente fechado (tal como $\C$).
Aqui, eu escolhi uma demonstração um pouco mais abstrata, mas tecnicamente mais fácil. O leitor está encorajado consultar as notas do John e Rodney para demonstrações alternativas e decidir qual gosta mais.

Antes da demonstração, nós precisamos de algumas ferramentas. Seja $R$ um anel comutativo e assuma que $A\in M_{n\times n}(R)$. Denote por $A_{i,j}$ a matriz $(n-1)\times (n-1)$ que obtemos por apagar a $i$-ésima linha e $j$-ésima coluna de $A$. Denote por $\mbox{adj}(A)=(b_{i,j})$ a matriz com entradas $b_{i,j}=(-1)^{i+j}\det A_{j,i}$. A matriz $\mbox{adj}(A)$ é  a <b>adjunta</b> de $A$.

:::{#thm-}
$\mbox{adj}(A)A=(\det A)I_n$. Em particular, se $\det A$ é invertível em $R$, então $A^{-1}=(\det A)^{-1}\mbox{adj}(A)$.
:::


:::{.proof}
Este teorema está frequentemente mencionado, ou inclusive provado, nas disciplinas anteriores. Se isso for o caso, revisar a demonstração; caso contrário, exercício.
:::


:::{.proof}
(A demonstração do Teorema de Cayley-Hamilton)
Suponhamos que $B=\{b_1,\ldots,b_n\}$ é uma base de $V$ e seja $A=(a_{i,j})=[f]_B^B$.  Considere o anel formada pelas combinações lineares das potências $f^0=\mbox{id}_V,f,f^2,f^3,\ldots$ dentro de $\mbox{End}(V)$. Embora $\mbox{End}(V)$ não seja comutativo, este $R$ é um anel comutativo. Considere a matriz
$$
A = \begin{pmatrix}
f-a_{1,1}\mbox{id}_V &  -a_{2,1}\mbox{id}_V & \cdots & -a_{n-1,1}\mbox{id}_V & -a_{n,1}\mbox{id}_V\\
-a_{1,2}\mbox{id}_V &  f-a_{2,2}\mbox{id}_V & \cdots & -a_{n-1,2}\mbox{id}_V & -a_{n,2}\mbox{id}_V\\
\vdots & \vdots & \ddots & \vdots & \vdots\\
-a_{1,n-1}\mbox{id}_V &  -a_{2,n-1}\mbox{id}_V & \cdots & f-a_{n-1,n-1}\mbox{id}_V & -a_{n,n-1}\mbox{id}_V\\
-a_{1,n}\mbox{id}_V &  -a_{2,n}\mbox{id}_V & \cdots & -a_{n-1,n}\mbox{id}_V & f-a_{n,n}\mbox{id}_V\\
\end{pmatrix}
$$
A matriz $A$ é um elemento de $M_{n\times n}(R)$ e note que $\det A =\mbox{pcar}_f(f)$. Pondo $b=(b_1,\ldots,b_n)^t$ (vetor coluna), temos que $Ab=0$. Por outro lado
$$
0=\mbox{adj}(A)Ab=(\det A)I_nb=(\det A)b=\mbox{pcar}_f(f)b.
$$
Logo $\mbox{pcar}_f(f)b_i=0$ para todo $i$. Como os $b_i$ formam uma base de $V$, obtemos que $\mbox{pcar}_f(f)=0$.

O fato que $m_f(t)\mid \mbox{pcar}_f(t)$ segue das propriedades do polinômio mínimo na página anterior.

:::

