
---
title: "Exercícios: Lista 1"
number-sections: true
lang: pt-BR
--- 

:::{#exr-}
Seja $\F$ um corpo. Mostre que

1. O elemento neutro aditivo $0_\F$ é único.
2. O elemento neutro multiplicativo $1_\F$ é único.
3. Se $a\in\F$, então o negativo $-a$ é único.
4. Se $a\in\F\setminus\{0_\F\}$, então o inverso $a^{-1}$ é único.
:::

:::{.sol .callout-tip collapse="true"}
### Solução: 
Apresentamos a solução dos itens 1. e 3. O leitor poderá fazer itens 2. e 4. 

1. O elemento neutro aditivo $0_\F$ é único. Suponha que existam dois elementos neutros aditivos $0_\F$ e $0'_\F$. Então, por definição de elemento neutro aditivo, temos que $0_\F + 0'_\F = 0'_\F$ e $0_\F + 0'_\F = 0_\F$. Portanto, $0_\F = 0'_\F$, mostrando que o elemento neutro aditivo é único.

2.  

3. Se $a\in\F$, então o negativo $-a$ é único. Suponha que existam dois negativos de $a$, denotados por $-a$ e $-a'$. Então, usando a definição do negativo e a associatividade,
   $$
   -a = -a+(a+(-a'))=(-a+a)+(-a')=-a'.
   $$

4. 
:::

:::{#exr-}
Seja $\F$ um corpo. Demonstre as seguintes leis cancelativas.

1. Se $a+b=a+c$, então $b=c$ para todo $a,b,c\in\F$.
2. Se $ab=ac$, então $b=c$ para todo $a,b,c\in\F$ com $a\neq 0_\F$.
:::

:::{.sol .callout-tip collapse="true"}
### Solução:
1. Suponha que $a + b = a + c$. Podemos adicionar o elemento neutro aditivo $-a$ em ambos os lados da equação:
    $$
    -a + (a + b) = -a + (a + c).
    $$
    Pela associatividade da adição, temos:
    $$
    (-a + a) + b = (-a + a) + c.
    $$
    Como $-a + a = 0_\F$, obtemos:
    $$
    0_\F + b = 0_\F + c.
    $$
    E, pela propriedade do elemento neutro aditivo, concluímos que $b = c$.

2. Suponha que $ab = ac$ com $a \neq 0_\F$. Podemos multiplicar ambos os lados da equação pelo inverso multiplicativo de $a$, denotado por $a^{-1}$:
    $$
    a^{-1}(ab) = a^{-1}(ac).
    $$
    Pela associatividade da multiplicação, temos:
    $$
    (a^{-1}a)b = (a^{-1}a)c.
    $$
    Como $a^{-1}a = 1_\F$, obtemos:
    $$
    1_\F b = 1_\F c.
    $$
    E, pela propriedade do elemento neutro multiplicativo, concluímos que $b = c$.
:::

:::{#exr-}
Decide quais dos seguintes conjuntos são corpos (com as operações $+$ e $\cdot$ usuais). Justifique sua resposta.

1. $\Z[i]=\{a+bi\mid a,b\in\Z\}$ (como subconjunto de $\C$).
2. $\Q[i]=\{a+bi\mid a,b\in\Q\}$ (como subconjunto de $\C$).
3. $\Z_{10}=\{0,\ldots,9\}$ com as operações mod $10$. 
4. 
$$
    \left\{\begin{pmatrix} 0 & 0 \\ 0 & 0\end{pmatrix}, 
    \begin{pmatrix} 1 & 0 \\ 0 & 1\end{pmatrix}
    \begin{pmatrix} 0 & 1 \\ 1 & 1\end{pmatrix}
    \begin{pmatrix} 1 & 1 \\ 1 & 0\end{pmatrix}\right\}
$$ 
considerado como subconjunto de $M_2(\Z_2)$.
:::

:::{.sol .callout-tip collapse="true"}
### Solução:
1. $\Z[i]$ não é um corpo. Embora $\Z[i]$ seja fechado sob adição e multiplicação, ele não é fechado sob inversão multiplicativa. Por exemplo, o inverso de $1 + i$ em $\C$ é $\frac{1}{2}(1 - i)$, que não está em $\Z[i]$.

2. $\Q[i]$ é um corpo. $\Q[i]$ é fechado sob adição, multiplicação e inversão multiplicativa. Para qualquer $a + bi \in \Q[i]$ com $a, b \in \Q$ e $a + bi \neq 0$, 
o inverso multiplicativo é 
$$
\frac{a}{a^2 + b^2} - \frac{b}{a^2 + b^2}i,
$$ 
que também está em $\Q[i]$.

3. $\Z_{10}$ não é um corpo. Embora $\Z_{10}$ seja fechado sob adição e multiplicação módulo 10, ele não possui inversos multiplicativos para todos os elementos não nulos. Por exemplo, 2 não tem inverso multiplicativo em $\Z_{10}$.

4. O conjunto dado é um corpo. Ele contém quatro matrizes $2 \times 2$ sobre $\Z_2$ e é fechado sob adição e multiplicação de matrizes. Além disso, cada elemento não nulo tem um inverso multiplicativo. Por exemplo, o inverso de 
$$
\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}
$$ 
é ele mesmo, o inverso de 
$$
\begin{pmatrix} 0 & 1 \\ 1 & 1 \end{pmatrix}
$$ 
é 
$$
\begin{pmatrix} 1 & 1 \\ 1 & 0 \end{pmatrix}
$$ 
e vice-versa. Portanto, todas as propriedades de um corpo são satisfeitas.
:::

:::{#exr-carateristica}
A caraterística de um corpo $\F$ é definida na seguinte forma. Se não existir um número $n\geq 1$ tal que $1+\cdots+1=0$ (tomando $n$ cópias de $1$), 
então a caraterística de $\F$ é zero. Se existir tal $n$, então a caraterística de $\F$ é o menor tal $n$. 
Mostre que a caraterística de um corpo ou é zero ou é um número primo. 
:::
:::{.sol .callout-tip collapse="true"}
### Solução:
Seja $\F$ um corpo e suponha que a característica de $\F$ não é zero. Então, existe um número $n \geq 1$ tal que $1 + 1 + \cdots + 1 = 0$ (com $n$ cópias de $1$). Seja $n$ o menor tal número. Vamos mostrar que $n$ é primo.

Suponha, por contradição, que $n$ não é primo. Então, existem inteiros $a, b \geq 2$ tais que $n = ab$. Considere a soma
$$
(1 + 1 + \cdots + 1)(1 + 1 + \cdots + 1)
$$
onde cada parêntese contém $a$ e $b$ cópias de $1$, respectivamente. Pela associatividade e comutatividade da adição, temos
$$
(1 + 1 + \cdots + 1)(1 + 1 + \cdots + 1) = ab = n = 0.
$$
Portanto, temos
$$
(1 + 1 + \cdots + 1) = 0 \quad \text{ou} \quad (1 + 1 + \cdots + 1) = 0,
$$
onde cada parêntese contém $a$ ou $b$ cópias de $1$, respectivamente. Isso contradiz a minimalidade de $n$, pois $a, b < n$.

Portanto, $n$ deve ser primo. Concluímos que a característica de um corpo ou é zero ou é um número primo.
:::


:::{#exr-}
Seja $V$ um espaço vetorial sobre um corpo $\F$. 

1. Mostre que o vetor nulo $0_V$ é único.
2. Mostre que o negativo $-v$ é único para todo $v\in V$. 
3. Mostre que $\alpha v=0_V$ se e somente se $\alpha=0_\F$ ou $v=0_V$.
4. Mostre que $(-1_\F)\cdot v=-v$ para todo $v\in V$. 
:::


:::{#exr-func-fin}
Seja $\F$ um corpo, $n\in\N$, $X=\{1,\ldots,n\}$, e seja $\mbox{Func}(X,\F)=\{f:X\to\F\}$ o $\F$-espaço vetorial das funções de $X$ para $\F$.
Para $i\in X$, defina 
$$
    f_i:X\to \F,\quad f_i(j)=\left\{\begin{array}{ll}1\mbox{ caso $i=j$}\\0\mbox{ caso $i\neq j$}
    \end{array}\right.\quad \mbox{para todo $j\in X$}.
$$ 
Mostre que $\{f_1,\ldots,f_n\}$ é uma base de $\mbox{Func}(X,\F)$. 
:::
:::{.sol .callout-tip collapse="true"}
### Solução:
Para mostrar que $\{f_1, \ldots, f_n\}$ é L.I., considere uma combinação linear arbitrária dos elementos de $\{f_1, \ldots, f_n\}$ que resulta no vetor nulo:
$$
\alpha_1 f_1 + \alpha_2 f_2 + \cdots + \alpha_n f_n = 0,
$$
onde $\alpha_1, \alpha_2, \ldots, \alpha_n \in \F$. Para cada $j \in X$, temos:
$$
(\alpha_1 f_1 + \alpha_2 f_2 + \cdots + \alpha_n f_n)(j) = 0.
$$
Por definição de $f_i$, isso se torna:
$$
\alpha_1 f_1(j) + \alpha_2 f_2(j) + \cdots + \alpha_n f_n(j) = 0.
$$
Note que $f_i(j) = 1$ se $i = j$ e $f_i(j) = 0$ se $i \neq j$. Portanto, para cada $j \in X$, a equação acima se reduz a:
$$
\alpha_j = 0.
$$
Como isso é válido para todo $j \in X$, concluímos que $\alpha_1 = \alpha_2 = \cdots = \alpha_n = 0$. Portanto, $\{f_1, \ldots, f_n\}$ é L.I.

Para mostrar que $\{f_1, \ldots, f_n\}$ é um sistema gerador de $\mbox{Func}(X, \F)$, precisamos mostrar que qualquer função $f \in \mbox{Func}(X, \F)$ pode ser escrita como uma combinação linear dos elementos de $\{f_1, \ldots, f_n\}$.

Seja $f \in \mbox{Func}(X, \F)$. Para cada $j \in X$, defina $\alpha_j = f(j)$. Então, podemos escrever $f$ como:
$$
f = \alpha_1 f_1 + \alpha_2 f_2 + \cdots + \alpha_n f_n.
$$
Para ver isso, considere qualquer $i \in X$. Então,
$$
(\alpha_1 f_1 + \alpha_2 f_2 + \cdots + \alpha_n f_n)(i) = \alpha_1 f_1(i) + \alpha_2 f_2(i) + \cdots + \alpha_n f_n(i).
$$
Por definição de $f_i$, temos $f_i(i) = 1$ e $f_i(j) = 0$ para $j \neq i$. Portanto, a expressão acima se reduz a:
$$
\alpha_i f_i(i) = \alpha_i \cdot 1 = \alpha_i.
$$
Como $\alpha_i = f(i)$, obtemos:
$$
(\alpha_1 f_1 + \alpha_2 f_2 + \cdots + \alpha_n f_n)(i) = f(i).
$$
Como isso é válido para todo $i \in X$, concluímos que:
$$
f = \alpha_1 f_1 + \alpha_2 f_2 + \cdots + \alpha_n f_n.
$$
Portanto, $\{f_1, \ldots, f_n\}$ é um sistema gerador de $\mbox{Func}(X, \F)$.
:::

:::{#exr-}
Considere o espaço $\mbox{Func}(X,\F)$ como no @exr-func-fin, mas agora ponha $X=\N$. Para todo 
$i\in\N$, defina $f_i$ na mesma forma como no @exr-func-fin que pode dizer sobre o conjunto $\{f_1,f_2,f_3,\ldots\}$? Ele é L.I.? Ele é gerador? Ele é base?  
:::
:::{.sol .callout-tip collapse="true"}
### Solução:
O conjunto $\{f_1, f_2, f_3, \ldots\}$ é L.I. Para ver isso, considere uma combinação linear finita arbitrária dos elementos de $\{f_1, f_2, f_3, \ldots\}$ que resulta no vetor nulo:
$$
\alpha_1 f_1 + \alpha_2 f_2 + \alpha_3 f_3 + \cdots + \alpha_k f_k = 0,
$$
onde $\alpha_1, \alpha_2, \alpha_3, \ldots, \alpha_k \in \F$. Para cada $j \in \{1, 2, \ldots, k\}$, temos:
$$
(\alpha_1 f_1 + \alpha_2 f_2 + \alpha_3 f_3 + \cdots + \alpha_k f_k)(j) = 0.
$$
Por definição de $f_i$, isso se torna:
$$
\alpha_1 f_1(j) + \alpha_2 f_2(j) + \alpha_3 f_3(j) + \cdots + \alpha_k f_k(j) = 0.
$$
Note que $f_i(j) = 1$ se $i = j$ e $f_i(j) = 0$ se $i \neq j$. Portanto, para cada $j \in \{1, 2, \ldots, k\}$, a equação acima se reduz a:
$$
\alpha_j = 0.
$$
Como isso é válido para todo $j \in \{1, 2, \ldots, k\}$, concluímos que $\alpha_1 = \alpha_2 = \alpha_3 = \cdots = \alpha_k = 0$. Portanto, $\{f_1, f_2, f_3, \ldots\}$ é L.I.

No entanto, $\{f_1, f_2, f_3, \ldots\}$ não é um sistema gerador de $\mbox{Func}(\N, \F)$. Para ver isso, considere uma função $f \in \mbox{Func}(\N, \F)$ tal que $f(i) = 1$ para todo $i \in \N$. Não existe uma combinação linear finita dos elementos de $\{f_1, f_2, f_3, \ldots\}$ que resulta em $f$, pois qualquer combinação linear finita de $f_i$ terá apenas um número finito de entradas não nulas, enquanto $f$ tem infinitas entradas não nulas.

Portanto, $\{f_1, f_2, f_3, \ldots\}$ não é uma base de $\mbox{Func}(\N, \F)$, pois não é um sistema gerador.
:::

:::{#exr-}
Usando o Lema de Zorn, demonstre as seguintes afirmações em um espaço vetorial $V$ não nulo qualquer.

1. Se $X\subseteq V$ é um conjunto L.I., então existe uma base $\overline X\subseteq V$ tal que 
$X\subseteq \overline X$. 
2. Se $X\subseteq V$ é um conjunto gerador, então existe uma base $\widetilde X\subseteq V$ tal que 
$\widetilde X\subseteq X$.
:::
:::{.sol .callout-tip collapse="true"}
### Solução:
1. Seja $X \subseteq V$ um conjunto L.I. Considere a coleção $\mathcal{C}$ de todos os conjuntos L.I. em $V$ que contêm $X$. Note que $\mathcal{C}$ é não vazia, pois $X \in \mathcal{C}$. Ordenamos $\mathcal{C}$ por inclusão. Seja $\{Y_i\}_{i \in I}$ uma cadeia em $\mathcal{C}$. Defina $Y = \bigcup_{i \in I} Y_i$. Usando o argumento na aula, pode-se verificar que $Y$ é L.I. e contém $X$. Portanto, $Y \in \mathcal{C}$, mostrando que toda cadeia em $\mathcal{C}$ tem uma cota superior em $\mathcal{C}$. Pelo Lema de Zorn, $\mathcal{C}$ tem um elemento maximal, denotado por $\overline{X}$. Mostraremos que $\overline{X}$ é uma base de $V$. Suponha, por contradição, que $\overline{X}$ não é um sistema gerador de $V$. Então, existe $v \in V \setminus \overline{X}$ tal que $\overline{X} \cup \{v\}$ é L.I., contradizendo a maximalidade de $\overline{X}$. Portanto, $\overline{X}$ é uma base de $V$ que contém $X$.

2. Seja $X \subseteq V$ um conjunto gerador. Considere a coleção $\mathcal{C}$ de todos os subconjuntos de $X$ que são L.I. Ordenamos $\mathcal{C}$ por inclusão. O resto do argumento é como no item 1 e deixamos ao leitor.
:::

:::{#exr-}
Considere o conjunto $X=\{(1,-1,0,0),(0,1,-1,0,),(0,0,1,-1),(1,0,-1,0)\}\subseteq\R^4$.

1. Mostre que $X$ não é sistema gerador de $\R^4$.
2. Ache todos os subconjuntos L.I. de $X$.
:::


:::{#exr-}
Se $\F$ é corpo e $k\geq 1$, defina 
$$
\F[x]_k=\{f\in\F[x]\mid \mbox{grau}f\leq k\}.
$$
Considere $X=\{1+x+x^2+x^3,1-x+x^2+x^3,1+x-x^2+x^3\}\subseteq \R[x]_3$. 

1. Mostre que $X$  é L.I.
2. Ache uma base $\overline X$ de $\R[x]_3$ tal que $X\subseteq \overline X$. 
:::

:::{#exr-}
Sejam $U,W$ subespaços de um espaço vetorial $V$. Demonstre que $U\cup W$ é um subespaço de $V$ 
se e somente se $U\subseteq W$ ou $W\subseteq U$. 
(Dica: veja a conversa [na página de stackexchange](https://math.stackexchange.com/q/71872).)
:::

:::{#exr-}
Seja $\F$ um corpo de caraterística diferente de 2 e seja $V=M_n(\F)$ 
(espaço de matrizes $n\times n$ sobre $\F$).  Para $A\in V$, denotamos a transposta de $A$ com $A^t$. Defina 
\begin{align*}
U_1&=\{A\in V\mid A^t=A\};\\
U_2&=\{A\in V\mid A^t=-A\}.
\end{align*}
Ou seja, $U_1$ é o conjunto das matrizes simétricas, enquanto $U_2$ é o conjunto das matrizes antisimétricas em $V$.

1. Mostre que $V=U_1\oplus U_2$.
2. Explique a necessidade da condição que a caraterística de $\F$ é diferente de 2.
[Dica: Consulte o @exm-direct-sum.]
:::

:::{#exr-}
Sejam $U_1,U_2,\ldots,U_k$ subespaços de um espaço vetorial $V$. Mostre que as segunites afirmações são equivalentes:

1. Todo elemento $v\in V$ pode ser escrito unicamente como $v=u_1+\cdots+u_k$ com $u_i\in U_i$.
2. $V=U_1+\cdots+U_k$ e $U_i\cap (\sum_{j\neq i}U_j)=0$ para todo $i\in\{1,\ldots,k\}$.
:::

:::{#exr-}
Decide quais dos seguintes conjuntos são subespaços de $V=\mbox{Func}([0,1],\R)$. 

1. $\{f\in V\mid f\mbox{ é limitado}\}$;
2. $\{f\in V\mid f\mbox{ é limitado superiormente}\}$;
3. $\{f\in V\mid f\mbox{ é limitado inferiormente}\}$;
4. $\{f\in V\mid f\mbox{ é diferenciável}\}$;
5. $\{f\in V\mid f\mbox{ é contínua}\}$;
6. $\{f\in V\mid f\mbox{ é crescente}\}$;
:::

:::{#exr-}
Defina os seguintes vetores em $\R^6$:
\begin{align*}
    v_1 &=( 1, 1, -1, -1,  0,  0)\\
    v_2 &= ( 1,  1,  0,  0, -1,  1)\\
    v_3 &= (-1, -1, -1, -1,  0,  0)\\
    v_4 &= ( 0,  0, -1, -1, 2, 0)\\
    v_5 &= ( 0,  0, 0, 0,  1,  0)\\
    v_6 &= ( 0,  0,  0,  0,  -1, -1)\\
\end{align*}
Defina $U_1=\left<v_1,v_2,v_3\right>$ e $U_2=\left<v_4,v_5,v_6\right>$.

1. Determine uma base para $U_1\cap U_2$. 
2. Estenda a base determinada no primeiro ponto para uma base de $U_1$ e também para uma base de 
    $U_2$.
3. Determina uma base de $U_1+U_2$.
:::

:::{#exr-}
Ache um complemento para o espaço $U_1$ em $V$ no exercício anterior.
:::

:::{#exr-}
Seja $\F$ um corpo com cardinalidade finita.

1. Deduza do @exr-carateristica que a caraterística de $\F$ é um primo $p$. 
2. Mostre que $\F$ é um espaço vetorial sobre o corpo $\Z_p$. 
3. Deduza que $\dim \F$ (considerado como $\Z_p$-espaço) é finita e ponha $\dim \F=d$. 
4. Mostre que $|\F|=p^d$. 
5. Parabens! Você acabou de demonstrar o seguinte teorema: ``Se $\F$ é  um corpo finito, então 
a cardinalidade de $\F$ é uma potência de um primo''.
(Dica: [página no stackexchange](https://math.stackexchange.com/q/72856))
:::      

:::{#exr-}
Se $B$ é o sistema $b_1,\ldots,b_k$ de vetores de $\F^n$, denote por $M_B$ a matriz $k\times n$ cujas linhas são $b_1,\ldots,b_k$. 
    
1. Seja $V\leq \F^n$. Mostre que $V$ possui uma base $B$ tal que $M_B$ está na forma escalonada reduzida. 
2. Mostre que a base $B$ no item anterior é única para o espaço $V$. 
:::

:::{#exr-}
Escreva uma função em uma linguagem de programação (por exemplo, Python) que toma duas matrizes (arrays) $A$ e $B$ com entradas no mesmo corpo e devolva `True` se os espaços gerados pelas linhas de $A$ e $B$ (respectivamente) são iguais. A função deve devolver `False` no caso contrário.
:::

::: {.callout-tip}
#### Dica:
Use o exercício anterior e ache as formas escalonadas reduzidas de $A$ e $B$ usando alguma implementação da Eliminação de Gauss-Jordan. Se usar Python, pode usar a função `rref` na biblioteca SymPy.
:::

:::{#exr-}
Seja $V\leq\F^n$ e assuma que $B=\{b_1,\ldots,b_k\}$ é base de $V$ tal que $M_B$ está na forma escalonada reduzida. Assuma que o pivô da linha $i$ está na coluna $p_i$. Seja $v=(v_1,\ldots,v_n)\in \F^n$ arbitrário e defina 
$$
v_B=v-\sum_{i=1}^kv_{p_i}b_i.
$$
    
1. Mostre que $v+V=v_B+V$.
2. Mostre que $(v_B)_{p_i}=0$ para todo $i$.
3. Mostre, para $v,w\in\F^n$, que $v+V=w+V$ se e somente se $v_B=w_B$.
:::

:::{#exr-}
O exercício anterior pode ser usado para decidir igualdade da forma algorítmica no quociente $\F^n/V$. Escreva uma função em uma linguagem de programação (por exemplo, Python) que toma uma matriz $B$ $(k\times n)$ na forma escalonada reduzida e toma dois vetores $v,w\in\F^n$ e devolve `True` se e somente se $v+V=w+V$, onde $V$ denota o espaço gerado pelas linhas de $B$. 
:::

::: {.callout-tip}
#### Dica:
Implemente o procedimento no exercício anterior e verifique se $v_B=w_B$.
:::

:::{#exr-}
Sejam $V$ e $W$ $\F$-espaços vetoriais de dimensão finita com $\dim V=k$ e $\dim W=m$. Assuma que $B=\{b_1,\ldots,b_k\}$ e $C=\{c_1,\ldots,c_m\}$ são bases de $V$ e $W$, respectivamente.  
    
1.  Considere o mapa 
$$
\psi:\mbox{Hom}(V,W)\to W^{k\oplus},\quad f\mapsto (f(b_1),\ldots,f(b_k))
$$
onde $W^{k\oplus}=W\oplus\cdots\oplus W$ (soma direta externa de $k$ cópias de $W$). Mostre que $\psi$ é um isomorfismo.
2. Mostre que $f\mapsto [f]_C^B$ é um isomorfismo $\mbox{Hom}(V,W)\to M_{m\times k}(\F)$.
:::

:::{#exr-}
Seja $V=\F_3[x]_3$ e considere as bases $B=\{1,x,x^2,x^3\}$ e $C=\{1,1-x,1-x^2,1-x^3\}$. Seja $d:V\to V$ o endomorfismo definido com $d(f)=f'$ (derivado formal). 
    
1. Ache as matrizes $[\mbox{id}_V]_B^C$ e $[\mbox{id}_V]_C^B$.
2. Ache as matrizes $[f]_B^B$, $[f]_B^C$, $[f]_C^B$ e $[f]_C^C$. 
:::

:::{#exr-}
Resolva os exercícios nas apostilas disponibilizadas nas abas das Semanas 2-3 que não aparecerem nas listas.
:::


      