--- 
title: "Operadores normais"
number-sections: true
lang: pt-BR
--- 
Nesta página $\F=\R$ ou $\F=\C$ e $V$ é um $\F$-espaço com produto interno $\langle -,-\rangle$. Alguns resultados são válidos para espaços vetoriais sobre corpos arbitrários com formas $\sigma$-hermitianas, mas nós vamos trabalhar com as suposições da frase anterior.

:::{#def-}
Um operador $f:V\to V$ é dito normal se existe $f^*$ e $ff^*=f^*f$. Ou seja, um operador é normal se e somente se existe o adjunto e  ele comuta com seu adjunto.
:::


:::{#lem-}
Seja $f:V\to V$ um operador.


 -  Se $f$ é autoadjunto, então $f$ é normal.
 -  Se $\dim V$ é finita e $f$ é diagonalizável por uma base ortonormal, então $f$ é normal.

:::


:::{.proof}
A primeira afirmação é óbvia, pois $f$ e $f$ claramente comutam. Para a segunda afirmação,  assuma que existe uma base ortonormal $\{b_1,\ldots,b_n\}$ de $V$ composta de autovetores de $f$. A matriz de $f$ nesta base é uma matriz diagonal $D$ com os autovalores $\lambda_1,\ldots,\lambda_n$ no diagonal principal. Na mesma base, a matriz $\overline D$ de $f^*$ é diagonal com $\overline \lambda_1,\ldots,\overline \lambda_n$ no diagonal principal. Como as matrizes diagonais $D$ e $\overline D$ comutam, temos que $f$ também comuta com $f^*$.
:::


:::{#exm-}
Um operador normal não precisa ser autoadjunto. Considere por exemplo o operador $R_\alpha:\R^2\to \R^2$ que é a rotação por $\alpha$ graus. A matriz deste operador na base canônica (que é ortonormal) é
$$
\begin{pmatrix}
\cos\alpha &-\mbox{sen}\,\alpha\\ \mbox{sen}\,\alpha & \cos\alpha\end{pmatrix}.
$$
A matriz da adjunta de $R_\alpha$ na mesma base é
$$
\begin{pmatrix}
\cos\alpha &\mbox{sen}\,\alpha\\ -\mbox{sen}\,\alpha & \cos\alpha\end{pmatrix};
$$
ou seja, $(R_\alpha)^*=R_{-\alpha}$. Como rotações do plano comutam, $R_\alpha$ comuta com $R_\alpha^*=R_{-\alpha}$ e $R_\alpha$ é normal. Por outro lado se $\alpha$ não é múltipo de $180$ graus, $R_\alpha\neq R_{-\alpha}$ e neste caso $R_\alpha$ não é autoadjunto.
:::


:::{#lem-}
Assuma que $f:V\to V$ é normal.


 -  $\|f(v)\|=\|f^*(v)\|$ para todo $v\in V$.
 -  Se $v$ é autovetor de $f$ com autovalor $\lambda$, então o mesmo $v$ é autovetor de $f^*$ com autovalor $\overline\lambda$.
 -  Se $v_1$ e $v_2$ são autovetores de $f$ com autovalores $\alpha_1$ e $\alpha_2$ distintos, então $v_1\perp v_2$.

:::


:::{.proof}
1. Seja $v\in V$. Então
\begin{align*}
\|f(v)\|^2&=\langle f(v),f(v)\rangle =\langle v,f^*(f(v))\rangle=\overline{\langle f(f^*(v),v\rangle}\\&=\overline{\langle f^*(v),f^*(v)\rangle}\\&=\overline{\| f^*(v)\|}=\|f^*(v)\|.
\end{align*}

2. Assuma que $f(v)=\lambda v$; ou seja $(f-\lambda\mbox{id})(v)=0$. Obtemos que $\|(f-\lambda\mbox{id})(v)\|=0$. Pelo item anterior, $\|(f-\lambda\mbox{id})^*(v)\|=0$. Então $(f-\lambda\mbox{id})^*(v)=0$; ou seja, $f^*(v)=\overline \lambda v$.

3. Temos que
$$
\alpha_1\langle v_1,v_2\rangle =\langle f(v_1),v_2\rangle=\langle v_1,f^*(v_2)\rangle = \alpha_2 \langle v_1,v_2\rangle.
$$
Logo $(\alpha_1-\alpha_2)\langle v_1,v_2\rangle=0$ e obtemos que $\langle v_1,v_2\rangle=0$.

:::


:::{#thm-}
Seja $V$ um $\C$-espaço de dimensão finita e $f:V\to V$ um operador. Existe uma base ortonormal formada por autovetores de $V$ se e somente se $f$ é um operador normal.
:::


:::{.proof}
Já vimos que quando existe uma base ortonormal formada por autovetores de $f$, então $f$ é normal.

A outra direção será demonstrada por indução na dimensão de $V$. Quando $\dim V=1$, então escolhe qualquer vetor não nulo $v\in V\setminus\{0\}$ e tome $\|v\|^{-1}v$ para base ortonormal formada por autovetores de $f$. Assuma que o resultado vale para espaços de dimensão $n-1$ e assuma que $\dim V=n$. Como o corpo é $\C$, $f$ possui autovalor $\lambda$ e seja $v\in V$ um autovetor não nulo. Seja $b_1=\|v\|^{-1}v$ um vetor unitário. Considere $U=\langle v\rangle$ e $W=U^\perp$. Note que $U$ é $f$-invariente. Mas $U$ também é $f^*$-invariante, pois $b_1$ é autovetor de $f^*$ com autovalor $\overline \lambda$. Assim, um resultado anterior implica que $W$ é $f$-invariante (pois $f=(f^*)^*$). As restrições de $f$ e $f^*$ para $W$ claramente comutam e $(f|_W)^*=(f^*)|_W$. Logo, a hipótese da indução é válida para $f|_W$ e $W$ e $W$ possui uma base $\{b_2,\ldots,b_n\}$ ortonormal formada por autovetores de $f$. Ora, $\{b_1,\ldots,b_n\}$ é a base procurada.

:::


:::{#exm-}
Seja $f:\C^2\to \C^2$ o operador com matriz
$$
A=\begin{pmatrix} 1 & i \\ i & 1\end{pmatrix}
$$
na base canônica. Note que a matriz de $f^*$ é
$$
A^*=\begin{pmatrix} 1 & -i \\ -i & 1\end{pmatrix}
$$
e $f$ não é autoadjunto. Mas
$$
AA^*=A^*A=\begin{pmatrix} 2 & 0 \\ 0 & 2\end{pmatrix}
$$
e $f$ é normal. Note que os autovalores de $f$ são raízes do polinômio caraterístico $t^2-2t+2$ que são $1\pm i$. Os autovetores ortonormais correspondentes são $(1/\sqrt{2})(1,1)$ e $(1/\sqrt{2})(1,-1)$. Logo pondo
$$
P=\frac 1{\sqrt 2}\begin{pmatrix} 1 & 1 \\ 1 & -1\end{pmatrix}
$$
temos que
$$
P^*AP=\begin{pmatrix} 1+i & 0 \\ 0 & 1-i\end{pmatrix}
$$
:::
