--- 
title: "Operadores positivos e decomposição em valores singulares"
number-sections: true
lang: pt-BR
--- 

Nesta página, $V$ é um $\C$-espaço de dimensão finita $n$ com produto interno $\left<-,-\right>$.

## Operadores positivos

:::{#lem-zero-op}
Assuma que $f\in\mbox{End}(V)$ é tal que 
$$
\left<f(v),v\right>=0\quad\mbox{para todo}\quad v\in V.
$$
Mostre que $f=0$. 
:::
:::{.proof}
Conta simples mostra que 
\begin{align*}
\left<f(v),w\right>&=\frac 14(\left<f(v+w),v+w\right>-\left<f(v-w),v-w\right>)+\\
&+\frac i4(\left<f(v+iw),v+iw\right>-\left<f(v-iw),v-iw\right>)=0
\end{align*}
vale para todo $v,w\in V$. Ora, toma $w=f(v)$ para obter que $\|f(v)\|^2=\left<f(v),f(v)\right>=0$; 
ou seja $f(v)=0$. 
:::

Note que o @lem-zero-op não vale para $\R$-espaços. Por exemplo, a rotação $f$ por 90 graus em $\R^2$ 
tem a propriedade que $f(v)\perp v$; ou seja $\left<f(v),v\right>=0$ para todo $v\in \R^2$, mas $f\neq 0$. 


:::{#def-}
Um operador $f\in\mbox{End}(V)$ é dito **positivo** se $\left<f(v),v\right>\in \R$ e $\left<f(v),v\right>\geq 0$ para todo $v\in V$.
$f$ é dito **positivo definido** se $\left<f(v),v\right>> 0$ para todo $v\in V$. 
:::

:::{#lem-pos}
Um operador positivo é autoadjunto e portanto é ortogonalmente diagonalizável. Além disso, os seus autovalores são não negativos. 
Vice versa, um operador autoadjunto é positivo se e somente se seus autvalores são não negativos. 
:::

:::{.proof}
Assums que $f$ é positivo. Então $\left<f(v),v\right>\in\R$ e assim $\left<f(v),v\right>=\left<v,f(v)\right>$. Mas também, pela definição do 
adjunto $f^*$, 
$$
\left<f(v),v\right>=\left<v,f^*(v)\right>.
$$
Logo, $\left<v,f(v)\right>=\left<v,f^*(v)\right>$ para todo $v\in V$; ou seja, $\left<v,(f-f^*)(v)\right>=0$ para todo $v\in V$. Ora, @lem-zero-op implica que 
$f-f^*=0$, portanto $f=f^*$. O fato que $f$ é diagonalizável segue por @thm-diag-selfadj. Se $\lambda$ é autovalor de $f$ com autovetor $v$, então 
$$
0\leq \left<f(v),v\right>=\lambda\left<v,v\right>=\lambda\|v\|^2,
$$
logo $\lambda \geq 0$. 

Assuma agora que $f$ é autoadjunto e seja $b_1,\ldots,b_n$ uma base ortonormal composta por autovetores de $f$ que correspondem aos 
autovalores $\lambda_1,\ldots,\lambda_n\geq 0$, respetivamente. Seja $v=\sum_{i=1}^n\alpha_i b_i$. Então 
$$
\left<f(v),v\right>=\left<f\left(\sum_{i=1}^n\alpha_i b_i\right),\sum_{i=1}^n\alpha_i b_i\right>=
\left<\sum_{i=1}^n\alpha_i \lambda_i b_i,\sum_{i=1}^n\alpha_i b_i\right>
\sum_{i=1}^n \lambda_i|\alpha_i|^2\geq 0.
$$ 
Portanto $f$ é positivo. 
:::

## A raiz quadrada de um operador positivo

Seja $f\in\mbox{End}(V)$ positivo. Pelo @lem-pos, temos que $f$ é ortogonalmente diagonalizável e existe uma base ortonormal 
$b_1,\ldots,b_n$ composta por autovetores de $f$ que correspondem aos autovalores $\lambda_1,\ldots,\lambda_n$, respetivamente, 
tais que $\lambda_i\geq 0$ para todo $i$. Considere o operador, $g:b_i\mapsto \sqrt{\lambda_i} b_i$ para todo $i$. Note que 

1. $g$ é autoadjunto;
2. os autovalores de $g$ são $\sqrt{\lambda_1},\ldots,\sqrt{\lambda_n}$;
3. $g$ é positivo por @lem-pos;
4. $g^2=f$;
5. se $v$ é autovetor de $f$ com autovalor $\lambda_i$ então $v$ é autovetor de $g$ com autovalor $\sqrt{\lambda_i}$. 

:::{#def-}
O operador $g$ é dito **raiz quadrada** de $f$ e escrevemos $g=\sqrt f$. 
:::

:::{#lem-}
Assuma que $f\in\mbox{End}(V)$ é positivo. Então existe único $g\in\mbox{End}(V)$ positivo tal que $g^2=f$. 
:::

:::{.proof}
Seja $g$ como no argumento no parágrafo antes do lema. 
A existência segue da construção de $g$. Para a unicidade, suponha que $h$ também é positivo e $h^2 = f$. Então $h$ é autoadjunto 
e existe uma base ortonormal $c_1,\ldots,c_n$  tal que $h(c_i) = \mu_i c_i$ para certos $\mu_i \geq 0$. Como $h^2=f$, temos que 
$f(c_i)=\mu_i^2 c_i$, ou seja, cada $c_i$ é autovetor para $f$ com autovalor $\mu_i^2$. Mas, pela observação 5. em cima, os autovetores de $f$ são autovetores de $g$, e assim 
$g(c_i)=\mu_ic_i$ e isso implica que $g(c_i)=h(c_i)$ para todo $i$ e $g=h$. 
:::

:::{#lem-fstarf-positive}
Seja $f\in \mbox{End}(V)$ qualquer. Então $f^* f$ é um operador autoadjunto e positivo e existe $\sqrt{f^*f}$.  
:::
:::{.proof}
Precisa verificar que 
$$
\left<f^*f(v),v\right>\geq 0\quad\mbox{para todo}\quad v\in V.
$$
Mas, como $(f^*)^*=f$, 
$$
\left<f^*f(v),v\right>=\left<f(v),(f^*)^*v\right>=\left<f(v),f(v)\right>=\|f(v)\|^2\geq 0.
$$
:::

## A decomposição polar

:::{#prp-polar}
(Decomposição polar)
Assuma que $f\in\mbox{End}(V)$ um operador qualquer. Então $f=u p$ onde $u$ é unitário e $p$ é positivo. 
:::

:::{.proof}
Considere o operador $p = \sqrt{f^* f}$, que é positivo por @lem-fstarf-positive. Se $p$ é invertível, defina $u = f p^{-1}$. Então:
$$
u^* u = (f p^{-1})^* (f p^{-1}) = (p^{-1})^* f^* f p^{-1} = p^{-1} f^* f p^{-1} = p^{-1} p^2 p^{-1} = \mbox{id}_V,
$$
ou seja, $u$ é unitário. Assim, $f = u p$.

Se $p$ não é invertível, seja $b_1,\ldots,b_n$ uma base ortonormal composta por autovetores de $p$  com 
autovalores $\lambda_1,\ldots,\lambda_n\geq 0$. Assuma ainda que $\lambda_1,\ldots,\lambda_k>0$ e $\lambda_{k+1}=\cdots=\lambda_n=0$. 
Com $i\in\{1,\ldots,n\}$, ponha $c_i=f(b_i)$. Afirmamos que $c_1,\ldots,c_n$ é um sistema ortogonal com 
$\|c_i\|=\lambda_i$. De fato, 
$$
\left<c_i,c_j\right>=\left<f(b_i),f(b_j)\right>=\left<b_i,f^*f(b_j)\right>=\left<b_i,p^2(b_j)\right>=\lambda_j^2\left<b_i,b_j\right>
$$
e a afirmação segue do fato que os $b_i$ formam base ortonormal. 
Para $i\in\{1,\ldots,k\}$, seja $d_i=\lambda_i^{-1}c_i$ e note que $d_1,\ldots,d_k$ é um sistema ortonormal. Usando ortogonalização de 
Gram-Schmidt, estenda este sistema para sistema ortonormal $d_1,\ldots,d_n$. Com o sistema estendido, temos que $c_i=\lambda_i d_i$ 
vale para todo $i\in\{1,\ldots,n\}$. Seja $u:V\to V$ a aplicação que manda 
$b_i\mapsto d_i$. Como os $b_i$ e os $d_i$ formam sistema ortonormal, temos que $u$ é operador unitário. Além disso, vale para todo $i$ que
$$
up(b_i)=u(\lambda_i b_i)=\lambda_i u(b_i)=\lambda_i d_i
$$
e 
$$
f(b_i)=c_i=\lambda_i d_i.
$$
Portanto $f$ $up$ são iguais sobre uma base que implica que $f=up$. 
:::

## Valores singulares

:::{#thm-}
(Decomposição em valores singulares)
Seja $A\in M_{n\times n}(\C)$. Então $A$ pode ser escrita como $A=UDV$ onde $U,V$ são matrizes unitárias e $D$ é matriz diagonal com números reais não negativos na diagonal principal. Além disso, as entradas na diagonal de $D$ são unicamente determinadas por $A$. 
:::

:::{.proof}
Assuma que $A$ e a matriz do operador $f$ na base canônica. Pela @prp-polar, temos que $f=z p$ onde $z$ é unitária e 
$p$ é positiva. Assuma que $P$ e $Z$ são as matrizes de $p$ e $z$ na base canônica. Então $A=ZP$ e 
$Z$ é matriz unitária e $P$ é hermitiana. Em particular, $P$ é ortogonalmente diagonalizável e existe alguma matriz unitária 
$W$ tal que $W^*PW=D$ diagonal. Como $P$ é positivo e $D$ contém os autovalores de $P$ na diagonal, as entradas de $P$ na diagonal principal são 
reais a não negativos. Ora,
$$
W^*AW=W^*ZPW=W^*ZWW^*PW=W^*ZWD
$$
e obtemos que
$$
A=ZWDW^*.
$$
Tomando $D=D$, $U=ZW$ e $V=W^*$, obtemos a decomposição no enunciado. 

Assuma que as entradas de $D$ na diagonal principal são $\delta_1,\ldots,\delta_n$. Tem-se que 
$$
A^*A=V^*D^*U^*UDV=V^*D^2V,
$$ 
que implica que os autovalores de $A^*A$ são $A^*A$ são $\delta_1^2,\ldots,\delta_n^2$. Como $\delta_i\geq 0$ para todo $i$, temos que 
estes autovalores são unicamente determinados por $A^*A$ e também por $A$. 
::: 

:::{#def-}
As entradas na diagonal principal da matriz $D$ são chamadas dos **valores singulares** da matriz $A$.
:::
