--- 
title: "Projeções"
number-sections: true
lang: pt-BR
--- 

:::{#def-}
Uma transformação $f\in\mbox{End}(V)$ chama-se <b>projeção</b> (ou <b>idempotente</b> em outros contextos) se $f^2=f$.
:::


:::{#def-}
Seja $f\in\mbox{End}(V)$ e $U\leq V$. O subespaço $U$ chama-se $f$-invariante se $f(u)\in U$ para todo $u\in U$. Neste caso a restrição $f|_U:U\to U$ é uma transformação linear de $U$; ou seja $f|_U\in\mbox{End}(U)$.
:::

Seja $V=U\oplus W$ uma decomposição para soma direta. Se $v\in V$, então $v$ pode ser escrito unicamente como $v=u+w$ com $u\in U$ e $w\in W$ e pode-se definir $f:V\to V$ como $f(v)=u$. O endomorfismo $f$ é uma projeção tal que $\mbox{Im}(f)=U$ e $\ker f=W$.

:::{#lem-projections}
As seguintes afirmações são equivalentes para um endomorfismo $f:V\to V$.

1. $f$ é uma projeção.
2. $\mbox{Im}(f)$ é $f$-invariante e $f|_{\textrm{Im}(f)}=\mbox{id}_{\textrm{Im}(f)}$.
3. $f$ é raiz do polinômio $t^2-t$ e $m_f(t)\in\{t,t-1,t^2-t\}$. (Em particular, os possíveis autovalores de $f$ são $0$ e $1$.)
4. $V_0=\ker f$, enquanto $V_1=\ker(\mbox{id}_V-f)=\mbox{Im}(f)$.
5. $V=V_0\oplus V_1$.
:::


:::{.proof}
1. $\Rightarrow$ 2.: Segue do fato que $f(f(v))=f(v)$ quando $f$ for uma projeção. 
2. $\Rightarrow$ 3.: Assuma afirmação 2. Então temos para $v\in V$ que $f(f(v))=f(v)$; ou seja, $f^2=f$. Portanto $f$ é 
   raiz do polinômio $t^2-t$. O polinômio minimal $m_f(t)$ de $f$ é divisor de $t^2-t$. A fatoração do polinômio 
   $t^2-t$ é $t^2-t=t(t-1)$, então os possíveis divisores mônicos são $t$, $t-1$, ou $t^2-1$.  
3. $\Rightarrow$ 4.: $V_0=\ker f$ vale para qualquer endomorfismo. Afirmamos que $V_1=\mbox{Im}(f)$. Se $f$ é raiz de $t^2-t$, então $f^2=f$. Se $f(v)\in\mbox{Im}(f)$, então $f(f(v))=f(v)$, logo $f(v)\in V_1$. Seja $v\in V_1$. Então $f(v)=v$ e $v\in \mbox{Im}(f)$. 
4. $\Rightarrow$ 5.: Temos que $V_0\cap V_1=0$, então precisamos provar que $V=V_0+V_1$. Se $V_1=\mbox{Im}(f)$, então  $f(f(v))=f(v)$ para todo $v\in V$. 
   Seja $v\in V$. Escreva $v=(v-f(v))+f(v)$. Ora $f(v-f(v))=f(v)-f(f(v))=f(v)-f(v)=0$. Logo $v-f(v)\in\ker f$ e $V=\ker f+\mbox{Im}(f)=V_0+V_1$. 
5. $\Rightarrow$ 1.: Seja $v\in V$ e escreva $v=v_0+v_1$ com $v_0\in\ker f=V_0$ e $v_1\in V_1$. Logo 
   $$
   f(v)=f(v_0+v_1)=f(v_0)+f(v_1)=f(v_1)=v_1
   $$ e 
   $f(f(v))=f(v_1)=v_1$. 
   Logo $f^2=f$ e $f$ é uma projeção. 
:::


Lembre que um espaço vetorial $V$ é soma direta de espaços $V_1,\ldots,V_k$ (ou seja, $V=V_1\oplus\cdots\oplus V_k$), se 
$$
V=V_1+\cdots+V_k\quad \mbox{e} \quad V_i\cap (\sum_{j\neq i}V_j)=0.
$$ 
Em particular, não basta assumir que $V_i\cap V_j=0$ para todo $i\neq j$. 
Se $V=V_1\oplus\cdots\oplus V_k$, pode-se definir $p_i:V\to V$ por
$$
p_i(v)=v_i
$$
onde $v=v_1+\cdots+v_k$ com $v_i\in V_i$. Definindo assim, temos que $p_i$ é uma projeção para cada $i$, $p_1+\cdots+p_k=\mbox{id}_V$ e $p_ip_j=0$ quando $i\neq j$. O teorema seguinte diz que este argumento pode ser revertido.

:::{#thm-proj}
Sejam $p_1,\ldots,p_k:V\to V$ tais que

1. $p_1+\cdots+p_k=\mbox{id}_V$;
2. $p_ip_j=0$ para todo $i\neq j$.

Então os $p_i$ são projeções e $V=\mbox{Im}(p_1)\oplus\cdots\oplus\mbox{Im}(p_k)$.
:::


:::{.proof}
Temos para $v\in V$ que
\begin{align*}
p_i(v)&=p_i(\mbox{id}_V(v))=p_i((p_1+\cdots+p_k)(v))=p_i(p_1(v)+\cdots+p_k(v))\\
&=p_i(p_1(v))+\cdots+p_i(p_i(v))+\cdots+p_i(p_k(v))=p_i(p_i(v)).
\end{align*}
Logo $p_i^2=p_i$ e $p_i$ é uma projeção.

Se $v\in V$, então
$$
v=\mbox{id}_V(v)=(p_1+\cdots+p_k)(v)=p_1(v)+\cdots+p_k(v)\in \mbox{Im}(p_1)+\cdots+\mbox{Im}(p_k).
$$
Para provar que a soma é direta, seja $p_i(v)\in\mbox{Im}(p_i)\cap\sum_{j\neq i}\mbox{Im}(p_j)$ e escreva
$$
p_i(v)=p_1(v_1)+\cdots+p_{i-1}(v_{i-1})+p_{i+1}(v_{i+1})+\cdots+p_k(v_k).
$$
Ora,
\begin{align*}
p_i(v)&=p_i(p_i(v))=p_i(p_1(v_1)+\cdots+p_{i-1}(v_{i-1})+p_{i+1}(v_{i+1})+\cdots+p_k(v_k))\\&=0.
\end{align*}
Portanto, $\mbox{Im}(p_i)\cap\sum_{j\neq i}\mbox{Im}(p_j)=0$ e a soma é direta.
:::
