--- 
title: "Subespaços"
number-sections: true
lang: pt-BR
--- 

:::{#def-}
Seja $V$ um espaço vetorial sobre um corpo $\F$ e $U\subseteq V$ um subconjunto não vazio. Dizemos que $U$ é <b>subespaço</b> de $V$ se $\alpha_1 v_1+\alpha_2 v_2\in U$ para todo $v_1,v_2\in U$ e $\alpha_1,\alpha_2\in\F$.
:::

Equivalentemente, podemos dizer que $U$ é um subespaço quando ele é fechado para combinações lineares; ou seja, $\sum_{i=1}^k\alpha_i v_i\in U$ para todo $\alpha_i\in\F$ e $v_i\in U$.

Um subespaço vetorial é um espaço vetorial dentro de um espaço maior.

Quando $U$ é um subespaço de $V$, escrevemos que $U\leq V$.

:::{#exm-}
Vários exemplos foram dados na aula.

Seja $V$ um $\F$-espaço vetorial e $X\subseteq V$. O subespaço gerado por $X$ está definido como
$$
\langle X\rangle=\left\{\sum_{i=1}^k\alpha_i x_i\mid \alpha_i\in\F,\ x_i\in X\right\}.
$$
Ou seja, $\langle X\rangle$ é o conjunto de todas as combinações lineares em $X$. Claramente, $\langle X\rangle \leq V$ e $\langle X\rangle= V$ se e somente se $X$ é um conjunto gerador.
:::

Observe que um subespaço $U$ é não vazio. Tomando $v\in U$, temos que $v+(-1)v=v-v=0\in U$. Ou seja, todo subespaço contém o vetor nulo.

O subconjunto $\{0\}$ é subespaço em qualquer espaço e este subespaço é chamado de <b>subespaço trivial</b>. O próprio $V$ é subespaço de $V$. Quando $U\leq V$ e $U\neq V$, escrevemos que $U<V$ e chamamos $U$ de espaço <b>próprio</b>.

:::{#lem-}
Seja $V$ um espaço vetorial, seja $I$ um conjunto de índices, e sejam $U_i$ subspaços de $V$ para todo $i\in I$.


-  A soma de $U_i$
$$
\sum_{i\in I}=\{u_1+\cdots+u_k\mid u_i\in U_{j_i}\mbox{ e }k\geq 0\}
$$
é um subespaço de $V$.
- A interseção
$$
\bigcap_{i\in I} U_i
$$
é um subespaço de $V$.
:::


:::{.proof}
Dada na aula.
:::

Note que a união não é geralmente subespaço. Exemplos foram dadas na aula. Quando temos um número finito de espaços $U_1,\ldots,U_k$, a soma pode ser escrita como
$$
U_1+\cdots+U_k=\{u_1+\cdots+u_k\mid u_i\in U_i\}.
$$
Em particular,
$$
U_1+U_2=\{u_1+u_2\mid u_i\in U_i\}.
$$
Na verdade, temos que
$$
\sum_{i=1}^k U_i=\left\langle\bigcup_{i\in I} U_i\right\rangle.
$$
Ou seja, $\sum_i U_i$ é o menor subespaço que contém $U_i$ para todo $i$.

:::{#lem-}
Seja $U\leq V$. Então $\dim U\leq \dim V$. Assumindo que $\dim V$ é finita, temos que $\dim U=\dim V$ se e somente se $U=V$.
:::


:::{.proof}
Dada na aula.
:::


:::{#exr-}
Seja $X\subseteq V$ onde $V$ é um espaço vetorial. Temos que
$$
\langle X\rangle=\bigcap_{X\subseteq U\leq V} U.
$$
:::



:::{#thm-}
Seja $V$ um espaço vetorial de dimensão finita e sejam $U_1,U_2\leq V$. Então
$$
\dim (U_1+U_2)=\dim U_1+\dim U_2-\dim(U_1\cap U_2).
$$
:::


:::{.proof}
Dada na aula, veja também as notas do Rodney e John.
:::


:::{#def-}
Sejam $U_1,U_2\in V$. Dizemos que $V$ é <b>soma direta</b> de $U_1$ e $U_2$ se
$$
V=U_1+U_2\quad\mbox{e}\quad U_1\cap U_2=\{0\}.
$$
Neste caso, escrevemos $V=U_1\oplus U_2$.
:::

É imediato que
$$
\dim(U_1\oplus U_2)=\dim U_1+\dim U_2.
$$

:::{#exm-}
Nestes exemplos, $F$ é um corpo arbitrário.

Considere $V=\F^2$ com um corpo $\F$. Se $U_1=\{(\alpha,0)\mid\alpha\in\F\}$ e $U_2=\{(0,\alpha)\mid \alpha\in\F\}$. então $V=\F^2=U_1\oplus U_2$.

Seja $V=\F[x]$ e defina
$$
U_1=\left\{\sum_{i=1}^n\alpha_ix^{2i}\mid \alpha_i\in\F\mbox{ e }n\geq 0\right\}
$$
e
$$
U_2=\left\{\sum_{i=1}^n\alpha_ix^{2i+1}\mid \alpha_i\in\F\mbox{ e }n\geq 0\right\}.
$$
Então $\F[x]=U_1\oplus U_2$.

Seja $\F$ um corpo de caraterística diferente de $2$ (por exemplo, $\F=\R$). Seja $V=\mbox{Func}(\F,\F)$ e defina
$$
U_1=\{f\in V\mid f(-x)=f(x)\mbox{ para todo }x\in \F\}
$$
e
$$
U_2=\{f\in V\mid f(-x)=-f(x)\mbox{ para todo }x\in \F\}.
$$
Ou seja, $U_1$ é o conjunto de funções pares e $U_2$ é o conjunto de funções ímpares. Afirmamos que $V=U_1\oplus U_2$. Primeiro, se $f\in V$ é arbitrário, então $f=f_1+f_2$ onde
$$
f_1(x)=\frac{f(x)+f(-x)}2\quad\mbox{e}\quad f_2(x)=\frac{f(x)-f(-x)}2.
$$
Como $f_1\in U_1$ e $f_2=U_2$, temos que $V=U_1+U_2$. Além disso, se $f$ é uma função par e impar no mesmo tempo, então $f=0$ e
$U_1\cap U_2=\{0\}$. Logo $V=U_1\oplus U_2$.
:::


:::{#thm-}
Sejam $U_1,U_2\leq V$. Então $V=U_1\oplus U_2$ se e somente se todo elemento $v\in V$ pode ser escrito unicamente como
$v=u_1+u_2$ como $u_i\in U_i$.
:::


:::{.proof}
Dada na aula, veja também as notas.
:::


:::{#def-}
Seja $V\neq 0$ um espaço vetorial e $U\leq V$. Um subespaço $W\leq V$ é dito <b>complemento</b> de $U$ em $V$ se $V=U\oplus W$.
:::


:::{#thm-}
Se $U\leq V$ como na definição anterior, existe complemento $W$ de $U$ em $V$.
:::


:::{.proof}
Seja $X\subseteq U$ uma base de $U$ e seja $Y\subseteq V$ disjunto de $X$ tal que $X\cup Y$ é base de $V$. Então pode tomar $W=\langle Y\rangle$.
:::


:::{#def-}
Seja $V$ um espaço vetorial e sejam $U_1,\ldots,U_k\leq V$. Dizemos que $V=U_1\oplus\cdots \oplus U_k$ se $V=U_1+\cdots+U_k$ e
$$
U_i\cap\left(U_1+\cdots+U_{i-1}+U_{i+1}+\cdot+U_k\right)=\{0\}
$$
para todo $i\in\{1,\ldots,k\}$.
:::


:::{#thm-}
Se $U_1,\ldots,U_k\leq V$, então $V=U_1\oplus\cdots\oplus U_k$ se e somente se todo elemento $v\in V$ pode ser escrito unicamente como $v=u_1+\cdots+u_k$ com $u_i\in U_i$. Neste caso temos ainda que $\dim V=\sum_{i}\dim U_i$.
:::

A construção de soma direta em cima frequentamente chama-se <b>soma direta interna</b>, pois a soma acontece dentro de um espaço $V$. Existe uma outra construção chamada de <b>soma direta externa</b> definida na maneira seguinte.

:::{#def-}
Sejam $U$ e $V$ espaços vetoriais sobre um corpo $\F$. A soma direta (externa) $U\oplus V$ de $U$ e $V$ está definida como o conjunto
$$
U\times V=\{(u,v)\mid u\in U, v\in V\}
$$
com as seguintes operações:
$$
(u_1,v_1)+(u_2,v_2)=(u_1+u_2,v_1+v_2)\mbox{ para todo } u_i\in U\mbox{ e }v_i\in V
$$
e
$$
\alpha(u,v)=(\alpha u,\alpha v)\mbox{ para todo } u\in U,\ v\in V\mbox{ e }\alpha\in \F.
$$
:::

É fácil verificar que $U\oplus V$ é um espaço vetorial. O vetor nulo é $(0_U,0_V)$ e $-(u,v)=(-u,-v)$ para $u\in U$ e $v\in V$. No caso da soma direta externa, $U$ e $V$ não precisam ser subespaços no mesmo espaço vetorial. Se $W=U\oplus V$ (soma direta externa), então podemos definir os subespaços
\begin{align*}
U_1&=\{(u,0_V)\mid u\in U\}\\
V_1&=\{(0_U,v)\mid v\in V\}.
\end{align*}
É fácil verificar que $W=U_1\oplus V_1$ considerado como uma suma interna. Em particular, quando $U$ e $V$ têm dimensão finita, então $\dim U\oplus V=\dim U+\dim V$.
:::



