
---
title: "Divisibilidade de polinômios"
number-sections: true
lang: pt-BR
---


:::{#def-}
Seja $R$ um anel e sejam $f(x),g(x)\in R[x]$. Dizemos que $f(x)$ **divide** $g(x)$, ou que $g(x)$ é **divisível** por $f(x)$ ou que $g(x)$ é um **múltiplo** de $f(x)$ se existir $h(x)\in R[x]$ tal que $f(x)h(x)=g(x)$. Quando $f(x)$ divide $g(x)$, escrevemos que $f(x)\mid g(x)$
:::


:::{#exm-}
Podemos dizer por exemplo que $x+1\mid x^2-1$ considerando estes polinômios, por exemplo, em $\Z[x]$. De fato $x^2-1=(x-1)(x+1)$. Note que a divisibilidade entre dois polinômios depende do anel $R$ de coeficientes. Por exemplo se $f(x)=2x+2$ e $g(x)=x^2-1$ são polinômios em $\Q[x]$, então $f(x)\mid g(x)$, pois $g(x)=f(x)h(x)$ onde $h(x)=(1/2)(x-1)$. Por outro lado, se consideramos estes polinômios em $\Z[x]$ então $f(x)\nmid g(x)$
:::

As propriedades principais da divisibilidade entre polinômios são as mesmas que entre números inteiros. No seguinte lema nós resumimos as propriedades mais importantes. Pode notar que o conceito da divisibilidade pode ser definido em um anel arbitrário (e não apenas nos anéis $\Z$ ou $R[x]$), mas nós não vamos fazer isso nesta disciplina.

:::{#lem-}
Seja $R$ um anel, sejam $f(x),g(x),h(x)\in R[x]$. As seguintes afirmações são válidas.


-  $f(x)\mid f(x)$.
-  Se $f(x)\mid g(x)$ e $g(x)\mid h(x)$ então $f(x)\mid h(x)$.
-  Se $R$ é um domínio, $f(x)\mid g(x)$ e $g(x)\mid f(x)$, então existe algum $\alpha\in R$ invertível tal que $g(x)=\alpha f(x)$.

:::


:::{.proof}
(1), (2): Exercício.

(3) Assuma que $R$ é um domínio, $f(x)\mid g(x)$ e $g(x)\mid f(x)$. Se $f(x)=0$, então $g(x)=0$ e a afirmação está verdadeira. Assuma agora que $f(x)\neq 0$. Então existem $q_1(x),q_2(x)$ tais que $g(x)=f(x)q_1(x)$ e $f(x)=g(x)q_2(x)$. Logo
$$
f(x)=q_2(x)g(x)=q_2(x)q_1(x)f(x).
$$
Como $R$ é um domínio, $R[x]$ também é, e como $f(x)$ é não nulo aplica-se a lei cancelativa que implica que $1=q_2(x)q_1(x)$. Agora a definição de elementos invertíveis implica que $q_1(x)$ e $q_2(x)$ são invertíveis em $R[x]$ e obtemos de um lema anterior que $q_1(x)$ e $q_2(x)$ são elementos invertíveis de $R$.

:::

