

---
title: "O Critério de Eisenstein"
number-sections: true
lang: pt-BR
---


:::{#thm-}
(O Critério de <a href="https://pt.wikipedia.org/wiki/Gotthold_Eisenstein">Eisenstein</a>) Seja
$$
f(x)=a_nx^n+\cdots+a_1x+a_0\in\Z[x]
$$
com $a_n\neq 0$ tal que existe um primo $p$ tal que $p\nmid a_n$, $p\mid a_i$ para todo $i\in\{0,\ldots,n-1\}$ e $p^2\nmid a_0$. Então $f(x)$ é irredutível em $\Q[x]$
:::


:::{.proof}
Assuma por procurar uma contradição que $f(x)$ é redutível em $\Q[x]$. Pelo Lema de Gauss, existem $g(x),h(x)\in\Z[x]$ tal que $f(x)=g(x)h(x)$ tais que $1\leq \grau{g(x)},\grau{h(x)}\leq\grau{f(x)}-1$. Assuma que
\begin{align*}
g(x)&=b_rx^r+\cdots +b_1x+b_0\\
h(x)&=c_sx^s+\cdots +c_1x+c_0
\end{align*}
com $b_r,c_s\neq 0$, $r,s\geq 1$ e $r+s=n$. Temos que $a_n=b_rc_s$ e $a_0=b_0c_0$. Como $p\nmid a_n$, temos que $p\nmid b_r$ e $p\nmid c_s$. Similarmente, como $p\mid a_0$ e $p^2\nmid a_0$, segue que $p\mid b_0$ ou $p\mid c_0$ mas $p$ não divide ambos $b_0$ e $c_0$. Assuma sem perder generalidade que $b\mid b_0$ e $p\nmid c_0$. Seja $t$ o menor índice tal que $p\nmid b_t$. Então $t\leq r < n$. O coeficiente $a_t$ é obtido como
$$
a_t=b_tc_0+b_{t-1}c_1+\cdots+b_1c_{t-1}+b_0c_t
$$
(se $\grau{h(x)} < t$, então tomamos $c_{s+1}=\cdots=c_t=0$).
Pelas condições do lema, $p\mid a_t$ e isso implica que $p\mid b_tc_0$ mas isso é impossível como $p\nmid  b_t$ e $p\nmid c_0$. Logo a fatoração $f(x)=g(x)h(x)$ não existe e assim $f(x)$ é irredutível
:::


:::{#exm-}
Seja $f(x)=x^n-p\in\Z[x]$ onde $p$ é um primo e $n\geq 1$. O critério de Eisenstein vale para $f(x)$ e assim $f(x)$ é irredutível. Em particular $\Q[x]$ possui polinômios irredutíveis de grau arbitrário
:::


:::{#exm-}
Seja $p\in\N$ um primo e considere
$$
f(x)=x^{p-1}+x^{p-2}+\cdots+x+1\in\Z[x].
$$
O polinômio $f(x)$ é chamado polinômio ciclotómico de grau $p$. Note que
$$
f(x)=\frac{x^p-1}{x-1}.
$$
Afirmamos que $f(x)$ é irredutível em $\Q[x]$. O Critério de Eisenstein não é diretamente aplicável e nós vamos fazer uma substituição de variável $y=x+1$. Assim
\begin{align*}
f(y)&=\frac{y^p-1}{y-1}=\frac{(x+1)^p-1}{(x+1)-1}\\
&=\frac{x^p+p x^{p-1}+\binom p2x^{p-2}+\cdots+\binom p{p-2}x^2+px+1-1}{x}\\&=
x^{p-1}+p x^{p-2}+\binom p2x^{p-3}+\cdots+\binom p{p-2}x+p.
\end{align*}
O coeficiente binomial $\binom pk$ é divisível por $p$ para todo $k\in\{1,\ldots,p-1\}$.
Pelo Critério de Eisentein, $f(y)$ é irredutível. Como $x=y-1$, temos que $f(x)=f(y-1)$ é também irredutível
:::

