

---
title: "Polinômios irredutíveis e o Teorema da Fatoração"
number-sections: true
lang: pt-BR
---

## Polinômios irredutíveis

:::{#def-irred}
Seja $R$ um domínio e seja $a\in R$ tal que $a\neq 0$ e $a$ não é invertível (em $R$). O elemento $a$ é dito **redutível** se existem $b,c\in R$ tal que $a=bc$ e nem $b$ nem $c$ é invertível.  Caso contrário, o elemento $a$ é dito **irredutível**. O elemento $0\in R$ e os elementos invertíveis de $R$ não são nem redutíveis nem irredutíveis
:::


:::{#exm-}
Seja $R=\Z$. Neste caso os invertíveis de $\Z$ são $1$ e $-1$ e um elemento $a\in \Z$ é irredutível se e somente se $a$ não pode ser escrito como $a=bc$ com $b,c\not\in\{1,-1\}$. Ou seja, os elemento irredutíveis de $\Z$ são os inteiros primos, enquanto os redutíveis são os compostos
:::


:::{#exr-}
Seja $a\in R$ e seja $u\in R$ invertível. Mostre que $a$ é irredutível se e somente se $ua$ é irredutível
:::


:::{#lem-}
As seguintes afirmações são verdadeiras para um polinômio $f(x)\in\F[x]$ onde $\F$ é um corpo.


-  Seja $\alpha\in\F\setminus\{0\}$. Temos que $f(x)$ é irredutível se e somente se $\alpha f(x)$ é irredutível.
-  Se $\grau{f(x)}=1$ então $f(x)$ é irredutível.
-  Se $\grau{f(x)} > 1$ e $f(x)$ possui raiz em $\F$ então $f(x)$ é redutível.
-  Se $\grau{f(x)} \in\{2,3\}$ então $f(x)$ é redutível se e somente se $f(x)$ possui raiz em $\F$.

:::


:::{.proof}
(1) Segue do exercício anterior notando que $\alpha$ é invertível em $\F[x]$.

(2) Assuma que $f(x)\in\F[x]$ do primeiro grau e escreva $f(x)=g(x)h(x)$ com $g(x),h(x)\in\F[x]$. Temos pelas propriedades do grau que
$$
1=\grau{f(x)}=\grau{g(x)h(x)}=\grau{g(x)}+\grau{h(x)}
$$
e assim $\grau{g(x)}=0$ ou $\grau{h(x)}=0$. Logo um dos polinômios de $g(x)$ ou $h(x)$ é escalar não nulo. Como tais polinômios de $\F[x]$ são invertíveis, temos que $f(x)$ é irredutível.

(3) Se $\grau{f(x)} > 1$ e $\alpha\in\F$ é raiz de $f(x)$, então $x-\alpha\mid f(x)$ e $f(x)=(x-\alpha)g(x)$ com $g(x)\in\F[x]$. Ademais, $\grau{g(x)}=\grau{f(x)}-1\geq 1$ e assim $f(x)$ pode ser fatorado como um produto de dois polinômios em tal forma que nenhum dos fatores é invertível. Portanto $f(x)$ é redutível.

(4) Assuma que $\grau{f(x)}\in\{2,3\}$. Se $f(x)$ possui raiz, então ele é redutível pelo tericeiro item. Vice versa, se $f(x)$ é redutível, então  $f(x)=g(x)h(x)$. Considerando que $f(x)$ tem grau dois ou três, temos que ou $g(x)$ ou $h(x)$ tem grau $1$. Assim $f(x)$ é divisível por um polinômio na forma $\alpha x+\beta$ com $\alpha\neq 0$ e assim $-\beta/\alpha$ é raiz de $f(x)$.

:::


:::{#exr-}
(O Teorema das Raízes Racionais)
Seja $f(x)=\alpha_n x^n+\alpha_{n-1}x^{n-1}+\cdots+\alpha_1x+\alpha_0\in\Z[x]$ e assuma que $\alpha/\beta\in\Q$ tal que $\mdc{\alpha}\beta=1$ é uma raiz de $f(x)$. Mostre que $\alpha\mid \alpha_0$ e $\beta\mid \alpha_n$
:::


:::{#exm-}


-  Se $\alpha\in\F\setminus\{0\}$ e $\beta\in\F$, então $\alpha x+\beta$ é um polinômio irredutível.
-  No exemplo anterior, precisamos que $\F$ seja um corpo. Por exemplo $f(x)=2x+2\in\Z[x]$ é redutível, pois $f(x)=2(x+1)$ e nenhum fator é invertível em $\Z[x]$.
-  Seja $f(x)=x^3+x+1\in \Q[x]$ usando o Teorema das Raízes Racionais, vemos que $f(x)$ não tem raiz em $\Q$ e assim $f(x)$ é irredutível em $\Q[x]$.
-  Considerando $f(x)=x^3+x+1\in\R[x]$ temos que $f(x)$ possui raiz real (tendo grau ímpar) e assim $f(x)$ é redutível em $\R[x]$. O mesmo polinômio também é redutível em $\C[x]$.
-  Seja $f(x)=x^3+x+\overline 1\in \Z_3[x]$. Claramente, $\overline 1\in\Z_3$ é raiz de $f(x)$ e assim $f(x)$ é redutível em $\Z_3[x]$.
-  Seja $f(x)=x^4+2x^2+1\in\R[x]$. Então $f(x)=(x^2+1)^2$ e assim $f(x)$ é redutível mesmo que $f(x)$ não possui raíz em $\R$.

:::


:::{#thm-irred-R-C}

-  Um polinômio $f(x)\in\C[x]$ é irredutível se e somente se $\grau{f(x)}=1$.
-  Um polinômio $f(x)\in\R[x]$ é irredutível se e somente se $\grau{f(x)}=1$ ou $\grau{f(x)}=2$ e $f(x)$ tem discriminante negativo.

:::


:::{.proof}
(1) Seja $f(x)\in\C[x]$. Se $\grau{f(x)}=1$ então $f(x)$ é irredutível pelo lema anterior. Se $\grau{f(x)}\geq 2$, então $f(x)$ possui raiz complexa (pelo Teorema Fundamental da Álgebra) e $f(x)$ é redutível pelo lema anterior.

(2) Seja $f(x)\in\R[x]$. Se $\grau{f(x)}=1$, então $f(x)$ é irredutível pelo lema anterior. Se $\grau{f(x)}=2$ e o discriminante de $f(x)$ é negativo, então $f(x)$ não possui raiz real e $f(x)$ é irredutível pelo lema anterior. Se $\grau{f(x)}=2$ e o discriminante de $f(x)$ é não negativo, então $f(x)$ possui raiz real e $f(x)$ é redutível pelo lema anterior. Assuma que $\grau{f(x)} \geq 3$. Usando um Teorema na semana passada, $f(x)$ pode ser escrito como um produto
$$
f(x)=\alpha\prod_{i=1}^r (x-\alpha_i)\prod_{j=1}^s(x^2+\beta_jx+\gamma_j)
$$
onde $\alpha\in\R$ é o coeficiente líder de $f(x)$.
O fato que $\grau{f(x)}\geq 3$ implica que o número dos fatores é maior ou igual a dois e assim $f(x)$ é redutível.

:::

O problema de decidir se um polinômio é redutível ou irredutível em $\Q[x]$ ou $\Z_p[x]$ é bem mais complicado como nós também vamos ver nas aulas seguintes.


## O Teorema de Fatoração para polinômios

:::{#thm-tfa-pol}
Seja $\F$ um corpo e seja $f(x)\in\F[x]$ de grau maior ou igual a $1$. Então $f(x)$ pode ser escrito na forma
$$
f(x)=\alpha q_1(x)\cdots q_k(x)
$$
onde $\alpha\in\F\setminus\{0\}$ e os $q_i(x)\in\F[x]$ são polinômios irredutíveis e mônicos. Além disso, esta fatoração de $f(x)$ é única a menos da ordem dos fatores
:::

Primeiro nós provaremos um lema que pode ser considerado como análogo de um resultado que já provamos para números inteiros.

:::{#lem-}
Seja $f(x)\in\F[x]$ um polinômio irredutível e $g(x),h(x)\in\F[x]$ tal que $f(x)\mid g(x)h(x)$. Então $f(x)\mid g(x)$ ou $f(x)\mid h(x)$
:::


:::{.proof}
Assuma que $f(x)\nmid g(x)$. Precisamos provar que $f(x)\mid h(x)$. Então $\mdc{f(x)}{g(x)}=1$ e existem $u(x),v(x)\in\F[x]$ tais que
$$
u(x)f(x)+v(x)g(x)=1.
$$
Multiplicando a equação anterior por $h(x)$ temos que
$$
u(x)f(x)h(x)+v(x)g(x)h(x)=h(x).
$$
Note que $f(x)$ divide as duas parcelas no lado esquerdo da última equação, logo $f(x)$ precisa dividir $h(x)$ e é isso que precisamos provar
:::


:::{.proof}
((O Teorema da Fatoração)
**Existência:** Vamos provar a existência por indução em $\grau{f(x)}$. Se $\grau{f(x)}=1$, então $f(x)$ é irredutível e
$$
f(x)=\alpha f_0(x)
$$
onde $\alpha\in\F\setminus\{0\}$ é o coeficiente líder de $f(x)$ e $f_0(x)$ é irredutível e mônico.

Assumamos que a afirmação da existência do teorema está válida para polinômios de grau menor ou igual a $k-1\geq 1$ e seja $f(x)$ um polinômio de grau $k$. Se $f(x)$ é irredutível, então
$$
f(x)=\alpha f_0(x)
$$
onde $\alpha\in\F\setminus\{0\}$ é o coeficiente líder de $f(x)$ é $f_0(x)$ é irredutível e mônico e $f(x)$ pode ser fatorado. Se $f(x)$ não é irredutível, então $f(x)=f_1(x)f_2(x)$ onde $f_1(x),f_2(x)\in\F[x]$ e $\grau{f_i(x)}\geq 1$. Pela hipótese da indução,
\begin{align*}
f_1(x)&=\alpha_1 q_1(x)\cdots q_k(x)\\
f_2(x)&=\alpha_2 q_{k+1}(x)\cdots q_\ell(x)
\end{align*}
onde $\alpha_1,\alpha_2\in\F[x]\setminus\{0\}$ e os $q_i(x)$ são mônicos e irredutíveis. Ora,
$$
f(x)=f_1(x)f_2(x)=(\alpha_1\alpha_2) q_1(x)\cdots q_k(x)q_{k+1}(x)\cdots q_\ell.
$$

**Unicidade.** Demonstremos agora a unicidade por indução sobre o número minimal de fatores. Assuma que $f(x)\in\F[x]$ tem apenas um fator;  ou seja $f(x)=\alpha f_0(x)$ onde $\alpha\in\F\setminus\{0\}$ e $f_0(x)$ é irredutível e mônico. Então $f(x)$ também é irreditúvel e qualquer outra fatoração tem também um único fator e tem a forma $f(x)=\beta f_1(x)$ onde $f_1(x)$ é mônico e irredutível. Agora $f_0(x)\mid f_1(x)$ e $f_1(x)\mid f_0(x)$. Como estes dois são mônicos temos que $f_0(x)=f_1(x)$. A igualdade $\alpha=\beta$ segue do fato que os dois são iguais ao coeficiente líder de $f(x)$.

Assuma que a afirmação da unicidade está válida para polinômios que podem ser escritos com $k-1$ fatores. Assuma que
$$
f(x)=\beta_1q_1(x)\cdots q_k(x)=\beta_2r_1(x)\ldots r_m(x)
$$
onde $m\geq k$, $\beta_1,\beta_2\in\F\setminus\{0\}$ e os $q_i(x)$ e $r_j(x)$ são mônicos e irredutíveis. Agora
$$
q_1(x)\mid f(x)=\beta_2r_1(x)\ldots r_m(x)
$$
e pelo lema no início desta página $q_1(x)\mid r_j(x)$ com algum $j$. Como $q_1(x)$ e $r_j(x)$ são mônicos e irredutíveis segue que $q_1(x)=r_j(x)$. Assuma sem perder a generalidade que $q_1(x)=r_1(x)$. Então
$$
f(x)=\beta_1q_1(x)q_2(x)\cdots q_k(x)=\beta_2q_1(x)r_2(x)\ldots r_m(x).
$$
Como $\F[x]$ é um domínio, a lei cancelativa aplica-se e obtemos que
$$
\beta_1q_2(x)\cdots q_k(x)=\beta_2r_2(x)\ldots r_m(x).
$$
Agora a hipótese de indução implica que $k=m$ e que os fatores $q_2(x),\ldots,q_k(x)$ e $r_2(x),\ldots,r_m(x)$ são os mesmos exceto possivelmente a sua ordem. Portanto os fatores $q_1(x),\ldots,q_k(x)$ e $r_1(x),\ldots,r_m(x)$ são os mesmos exceto possivelmente a sua ordem. O fato que $\beta_1=\beta_2$ segue, pois os dois são iguais ao coeficiente líder de $f(x)$.

:::


:::{#exm-}
Seja $f(x)\in\C[x]$ um polinômio de grau maior ou igual a um. Seja
$$
f(x)=\beta_n x^n+\cdots+\beta_1x+\beta_0
$$
com $\beta_n\neq 0$. Então $f(x)=\beta_n f_0(x)$ onde $f_0(x)\in\C[x]$ é um polinômio mônico. Pelo teorema demonstrado na semana passada,
$$
f_0(x)=\prod_{i=1}^n(x-\alpha_i)
$$
onde os $\alpha_i$ são as raízes de $f_0(x)$ (e assim também as raízes de $f(x)$) contando com multiplicidade. Ora, a fatoração de $f(x)$ em produto de irredutíveis é
$$
f(x)=\beta_n\prod_{i=1}^n(x-\alpha_i).
$$
:::


:::{#exm-}
Agora, seja $f(x)\in\R[x]$ um polinômio de grau maior ou igual a um. Seja
$$
f(x)=\beta_n x^n+\cdots+\beta_1x+\beta_0
$$
com $\beta_i\in\R$ e $\beta_n\neq 0$. Como acima, $f(x)=\beta_n f_0(x)$ onde $f_0(x)\in\R[x]$ é um polinômio mônico. Pelo teorema demonstrado na semana passada sobre polinômios em $\R[x]$,
$$
f_0(x)=\prod_{i=1}^s(x-\alpha_i)\prod_{j=1}^r(x^2+\gamma_jx+\delta_j)
$$
onde $\alpha_i,\gamma_j,\delta_j\in\R$ e $\gamma_j^2-4\delta_j < 0$ para todo $j\geq 1$. Os fatores na fatoração na equação anterior podem ser determinados usando as raízes de $f(x)$. De fato, as raízes de $f(x)$ (contando com multiplicidade) são
$$
\alpha_1,\ldots,\alpha_s,\alpha_{s+1},\overline{\alpha_{s+1}},\ldots,\alpha_{s+r},\overline{\alpha_{s+r}}
$$
onde $n=s+2r$ e $\alpha_i\in\R$ se e somente se $i\in\{1,\ldots,s\}$. A fatoração de $f_0(x)$ pode ser escrita como
$$
f_0(x)=\prod_{i=1}^s(x-\alpha_i)\prod_{j={s+1}}^{s+r}(x^2-(\alpha_j+\overline{\alpha_j})x+\alpha_j\cdot\overline{\alpha_j}).
$$
Consequentemente a fatoração de $f(x)$ é
$$
f(x)=\beta_n\prod_{i=1}^s(x-\alpha_i)\prod_{j={s+1}}^{s+r}(x^2-(\alpha_j+\overline{\alpha_j})x+\alpha_j\cdot\overline{\alpha_j}).
$$
:::


:::{#exm-}
No terceiro exemplo considere
$$
f(x)=x^5 - 2x^3 + x^2 + x - 1\in\Q[x].
$$
Dá para verificar que $\alpha_1=1$ e $\alpha_2=-1$ são raízes de $f(x)$ e assim $f(x)$ é divisível por $(x-1)(x+1)=x^2-1$. Calculando o quociente, obtemos que
$$
f(x)=(x-1)(x+1)(x^3-x+1).
$$
O Teorema das Raízes Racionais implica que $x^3-x+1$ não possui raízes em $\Q$ e (sendo um polinômio de grau $3$) é irredutível. Então a fatoração de $f(x)$ é
$$
f(x)=x^5 - 2x^3 + x^2 + x - 1=(x-1)(x+1)(x^3-x+1)
$$
:::

