

---
title: "O anel dos polinômios"
number-sections: true
lang: pt-BR
---


## Polinômios

:::{#def-pol}
Seja $R$ um anel. Um **polinômio** sobre $R$ (ou polinômio com coeficientes em $R$) é uma expressão formal
$$
f=f(x)=\alpha_n x^n+\alpha_{n-1}x^{n-1}+\cdots+\alpha_1 x+\alpha_0
$$
onde $\alpha_i\in R$. O símbolo $x$ é uma incógnita. Por exemplo
$$
\frac 12x^2+2x-1
$$
pode ser considerado como um polinômio sobre $\Q$, $\R$ ou $\C$. O conjunto de todos os polinômios na incógnita $x$ sobre $R$ é denotado por $R[x]$. Seja $f(x)\in R[x]$ um polinômio como acima e assuma agora que $\alpha_n\neq 0$. O termo $\alpha_nx^n$ é chamado **termo líder** de $f(x)$ enquanto o coeficiente $\alpha_n$ é o **coeficiente líder**. O número $n$ é dito o **grau** de $f(x)$ e é denotado por $\grau{f(x)}$. Um polinômio $f(x)$ é dito **mônico** se o seu coeficiente líder é igual a $1$. Para o polinômio $0$ estes termos não são definidos
:::

Se $\alpha\in R$ então $\alpha$ pode ser identificado com o elemento $\alpha=\alpha x^0\in R[x]$ e assim os elementos de $R$ podem ser considerados como polinômios de grau zero em $R[x]$. Os polinômios de grau zero são também chamados de **polinômios constantes**.

Por exemplo considere $f(x)\in\Z_5[x]$ onde
$$
f(x) = \overline 2x^2+\overline 1.
$$
O termo líder de $f(x)$ é $\overline 2x^2$, o coeficiente líder é $\overline 2$, o grau de $f(x)$ é $2$ e $f(x)$ não é mônico, pois  seu coeficiente líder é diferente de $\overline 1$.

Nesta disciplina, polinômios são considerados principalmente como expressões simbólicas e não como funções. No entanto, dado um polinômio $f(x)\in R[x]$  e $\alpha\in R$ pode-se substituir $\alpha$ em $f(x)$ e obter $f(\alpha)\in R$. O elemento $\alpha\in R$ é dito **raiz** de $f(x)$ se $f(\alpha)=0$.

Podemos também definir a função polinomial
$$
\hat f:R\to R,\quad \hat f(\alpha)= f(\alpha).
$$
No entanto, note que para $p$ um primo, $f(x)=x$ e $g(x)=x^p$ são dois polinômios distintos de $\Z_p[x]$, mas pelo Pequeno Teorema de Fermat, as funções $\hat f,\hat g:\Z_p\to \Z_p$ são iguais. Assim, quando falamos de polinômios sobre um anel arbitrário, precisa-se distinguir entre o polinômio como expressão formal e a função polinomial.


## O anel dos polinômios

Seja $R$ um anel e considere o conjunto dos polinômios $R[x]$ sobre $R$. Nós introduzimos duas operações $+$ e $\cdot$ no conjunto $R[x]$. Sejam $f(x),g(x)\in R[x]$ dados como
\begin{align*}
f(x)&=\alpha_nx^n+\alpha_{n-1}x^{n-1}+\cdots+\alpha_1x+\alpha_0\\
g(x)&=\beta_nx^n+\beta_{n-1}x^{n-1}+\cdots+\beta_1x+\beta_0
\end{align*}
onde $\alpha_i,\beta_i\in R$. (Note que nós não assumimos que $\alpha_n\neq 0$ e $\beta_n\neq 0$) então os graus de $f(x)$ e $g(x)$ podem não coincidir.) Defina
\begin{align*}
f(x)+g(x)&=(\alpha_n+\beta_n)x^n+(\alpha_{n-1}+\beta_{n-1})x^{n-1}+\cdots+(\alpha_1+\beta_1)x+\alpha_0+\beta_0;\\
f(x)g(x)&=c_{2n}x^{2n}+c_{2n-1}x^{2n-1}+\cdots +c_1x+c_0
\end{align*}
onde
$$
c_k=\sum_{i,j\in\{0,\ldots,n\}\\ i+j=k} a_ib_j.
$$

:::{#exm-}
Considere $f(x)=x^3+\overline 2x$ e $g(x)=\overline 2x+\overline 1$ em $\Z_3[x]$. Então
\begin{align*}
f(x)+g(x) &= x^3+x+\overline 1\\
f(x)g(x) & = (x^3+\overline 2x)(\overline 2x+\overline 1)=\overline 2x^4+x^3+x^2+\overline 2x.
\end{align*}
:::


:::{#lem-deg-mult}
Seja $R$ um anel e $f(x),g(x)\in R[x]\setminus\{0\}$.

1. $f(x)g(x)=0$ ou $\grau{f(x)g(x)}\leq \grau{f(x)}+\grau{g(x)}$.
2. Se $R$ for um domínio, então $f(x)g(x)\neq 0$ e $\grau{f(x)g(x)}= \grau{f(x)}+\grau{g(x)}$
:::


:::{.proof}
A primeira afirmação segue da definição do produto. Assuma que $R$ é um domínio e sejam $f(x),g(x)\in R[x]$ tais que
\begin{align*}
f(x)&=\alpha_nx^n+\alpha_{n-1}x^{n-1}+\cdots+\alpha_1x+\alpha_0\\
g(x)&=\beta_mx^m+\beta_{m-1}x^{m-1}+\cdots+\beta_1x+\beta_0
\end{align*}
com $\alpha_i,\beta_j\in R$ e com $\alpha_n,\beta_m\neq 0$. Em particular, $\grau{f(x)}=n$ e $\grau{g(x)}=m$ e
$$
f(x)g(x)=\alpha_n\beta_mx^{m+n}+\cdots
$$
onde $\cdots$ significa uma soma de termos de grau menor que $m+n$. Como $R$ é um domínio, $\alpha_n\beta_m\neq 0$ e temos que $f(x)g(x)\neq 0$ e que
$$
\grau{f(x)g(x)}=m+n=\grau{f(x)}+\grau{g(x)}.
$$
:::


:::{#exm-}
É possível que o grau do produto seja estritamente menor que a soma dos graus. Considere por exemplo $f(x)=\overline 2x+\overline 1$ e $g(x)=\overline 3x+\overline 1$ em $\Z_6[x]$. Então $\grau{f(x)}=\grau{g(x)}=1$, mas
$$
f(x)g(x)=(\overline 2x+\overline 1)(\overline 3x+\overline 1)=\overline 5x+\overline 1
$$
e assim $\grau{f(x)g(x)}=1$
:::


:::{#thm-}
Seja $R$ um anel. As seguintes afirmações são verdadeiras.


-  $R[x]$ é um anel com as operações de $+$ e $\cdot$ entre polinômios.
-  $R[x]$ é um domínio se e somente se $R$ é um domínio.
-  Se $R$ é um domínio, então os elementos invertíveis de $R[x]$ são os elementos invertíveis de $R$ (considerados como polinômios de grau zero).

:::


:::{.proof}
(1) Exercício.

(2) Se $R$ é um domínio, então $R[x]$ é domínio pelo lema anterior. Vice versa, se $R[x]$ é um domínio e $a,b\in R\setminus\{0\}$, então $a$ e $b$ podem ser considerados como elementos de grau zero em $R[x]$. Como $R[x]$ é domínio, temos que $ab\neq 0$ e obtemos que $R$ também é domínio.

(3) Seja $R$ um domínio. É fácil verificar que um elemento invertível $\alpha\in R$ é invertível em $R[x]$. Assuma que $f(x)\in R[x]$ invertível. Então existe $g(x)\in R[x]$ tal que $f(x)g(x)=1$. Daí temos que $f(x),g(x)\neq 0$ e
$$
0=\grau{1}=\grau{f(x)g(x)}=\grau{f(x)}+\grau{g(x)}.
$$
Como os graus de $f(x)$ e de $g(x)$ são inteiros não negativos, segue que
$$
\grau{f(x)}=\grau{g(x)}=0;
$$
ou seja $f(x)=\alpha$ e $g(x)=\beta$ com $\alpha,\beta\in R$ e $\alpha\beta=1$. Portanto $f(x)=\alpha$ é um elemento invertível de $R$.

:::

