

---
title: "Raízes e fatoração"
number-sections: true
lang: pt-BR
---

Seja $\F$ um corpo. Lembre que $\alpha\in\F$ é raiz de um polinômio $f(x)\in\F[x]$ se $f(\alpha)=0$.

:::{#lem-root-div}
Seja $f(x)\in\F[x]\setminus\{0\}$ um polinômio e $\alpha\in\F$. Então existe um polinômio $q(x)\in\F[x]$ tal que
$$
f(x)=q(x)(x-\alpha)+f(\alpha).
$$
Em particular, $x-\alpha\mid f(x)$ se e somente se $f(\alpha)=0$ (ou seja, $\alpha$ é raiz do polinômio $f(x)$)
:::


:::{.proof}
Use o Teorema de Divisão de Euclides para escrever
$$
f(x)=q(x)(x-\alpha)+\beta
$$
com $\beta\in\F$. Substituindo $\alpha$ na equação anterior, obtemos que
$$
f(\alpha)=\beta.
$$
Para provar a segunda afirmação, observe que $\alpha$ é raiz do polinômio $f(x)$ se e somente se $f(\alpha)=0$ e isso vale se e somente se $f(x)=q(x)(x-\alpha)$ com algum $q(x)\in\F[x]$. Esta última afirmação é equivalente a dizer que $x-\alpha\mid f(x)$
:::


:::{#cor-nr-roots}
Seja $f(x)\in\F[x]\setminus\{0\}$ um polinômio. O número das raízes de $f(x)$ em $\F$ é menor ou igual a $\grau{f(x)}$
:::


:::{.proof}
Fazemos indução pelo $\grau{f(x)}$. Se $\grau{f(x)}=0$, então $f(x)=\alpha$ com $\alpha\in\F\setminus\{0\}$ e $f(x)$ não possui raízes em $\F$ e assim a afirmação é verdadeira. Assuma que um polinômio de $\F[x]$ de grau $k-1$ possui no máximo $k-1$ raízes em $\F$ e seja $f(x)\in\F[x]$ com grau $k$. Se $f(x)$ não possui raízes em $\F$ então a afirmação do corolário é verdadeira para $f(x)$. Assuma que $\alpha\in\F$ é raiz de $f(x)$. Então $f(x)=(x-\alpha)g(x)$ com $\grau{g(x)}=k-1$. Se $\beta\in\F\setminus\{\alpha\}$ é raiz de $f(x)$, então
$$
0=f(\beta)=(\beta-\alpha)g(\beta)
$$
e, como $\beta-\alpha\neq 0$, $g(\beta)=0$. Logo $\beta$ precisa ser raiz de $g(x)$. Obtemos assim que as raizes de $f(x)$ são $\alpha$ e as raízes de $g(x)$. Pela hipótese de indução, $g(x)$ tem no máximo $k-1$ raízes, portanto $f(x)$ tem no máximo $k$ raízes
:::


:::{#thm-fundamental-da-algebra}
 (O Teorema fundamental da Álgebra)
Seja $f(x)\in\C[x]$ um polinômio de grau maior ou igual a $1$. Então $f(x)$ possui raiz em $\C$
:::


:::{#thm-}
Seja $f(x)\in\C[x]$ um polinômio mônico de grau $k\geq 1$. Então existem $\alpha_1,\ldots,\alpha_k\in\C$ tais que
$$
f(x)=(x-\alpha_1)(x-\alpha_2)\cdots(x-\alpha_k).
$$
:::


:::{.proof}
Vamos fazer indução em $k$. Se $k=1$, então $f(x)=x-\alpha$ ($f(x)$ é mônico), então a afirmação está verdadeira. Assuma que a afirmação está válida para polinômios de grau menor que $k$ e seja $\grau{f(x)}=k$. Pelo Teorema Fundamental da Álgebra, $f(x)$ possui raiz $\alpha_k\in\C$ e assim $x-\alpha_k\mid f(x)$ pelo lema anterior. Escreva
$$
f(x)=(x-\alpha_k)q(x)
$$
e note que $q(x)$ é mônico e $\grau{q(x)}=k-1$. Pela hipótese da indução, existem $\alpha_1,\ldots,\alpha_{k-1}\in\C$ tais que
$$
q(x)=(x-\alpha_1)\cdots (x-\alpha_{k-1}).
$$
Portanto
$$
f(x)=q(x)(x-\alpha_k)=(x-\alpha_1)\cdots(x-\alpha_{k-1})(x-\alpha_k).
$$
:::

Na decomposição dada pelo teorema anterior os escalares $\alpha_1,\ldots,\alpha_k$ são as raízes complexas de $f(x)$ contadas com multiplicidade. Isso quer dizer que uma raiz pode ocorrer várias vezes nesta lista.

:::{#exm-}
Considere o polinômio
$$
f(x)=x^{n-1}+x^{n-2}+\cdots+x+1\in\C[x]
$$
com $n\geq 2$. Note que $x^n-1=(x-1)f(x)$ e assim as raízes de  $f(x)$ são os números $\alpha\in\C\setminus\{1\}$ tais que $\alpha^n=1$. Estes números são $\alpha_1,\ldots,\alpha_{n-1}$ onde
$$
\alpha_k=\exp(2k\pi i/n)=\cos(2k\pi/n)+i\,\mbox{sen}(2k\pi/n).
$$
Assim
\begin{align*}
f(x)&=x^{n-1}+x^{n-2}+\cdots+x+1\\
&=\prod_{k=1}^{n-1}(x-\alpha_k)\\
&=\prod_{k=1}^{n-1}(x-\exp(2k\pi i/n))\\
&=\prod_{k=1}^{n-1}(x-\cos(2k\pi/n)-i\,\mbox{sen}(2k\pi/n))
\end{align*}
:::

Lembre que se $z=a+bi\in\C$, então o **conjugado complexo** $\overline z$ de $z$ está definido como
$$
\overline z=a-bi.
$$

:::{#exr-}
Demonstre para $z_1,z_2\in\C$ que


-  $\overbar{z_1+z_2}=\overline{z_1}+\overline{z_2}$;
-  $\overline{z_1z_2}=\overline{z_1}\cdot\overline{z_2}$;
-  $\overline{z_1}=z_1$ se e somente se $z_1\in\R$.

:::


:::{#lem-comp-conj-root}
Seja $f(x)\in\R[x]$ e seja $\alpha\in\C$. Se $\alpha$ raiz de $f(x)$, então $\bar\alpha$ também é
:::


:::{.proof}
Seja
$$
f(x)=\alpha_nx^n+\cdots+\alpha_1x+\alpha_0
$$
e assuma que $\alpha\in\C$ tal que $f(\alpha)=0$. Então, usando o exercício anterior, obtemos que
\begin{align*}
0&=\overline 0=\overline{f(\alpha)}=\overline{\alpha_n\alpha^n+\cdots+\alpha_1\alpha+\alpha_0}\\&=
\alpha_n\overline \alpha^n+\cdots+\alpha_1\overline \alpha+\alpha_0.
\end{align*}
Logo $f(\overline\alpha)=0$
:::

Seja $f(x)=x^2+\alpha x+\beta\in\R[x]$. Lembre que o **discriminante** $\Delta$ de $f(x)$ é definido como $\Delta=\alpha^2-4\beta$. Ademais,  $f(x)$ possui duas raízes distintas em $\R$ se $\Delta >  0$, $f(x)$ possui uma única raiz em $\R$ se $\Delta=0$ e $f(x)$ não possui raízes em $\R$ se $\Delta < 0$.

:::{#thm-}
Seja $f(x)\in\R[x]$ um polinômio mônico de grau $k\geq 1$.  Então $f(x)$ pode ser escrito na forma
$$
f(x)=(x-\alpha_1)\cdots (x-\alpha_s)(x^2+\beta_1x+\gamma_1)\cdots (x^2+\beta_rx+\gamma_r)
$$
onde $s+2r=k$, $\alpha_i,\beta_j,\gamma_\ell\in\R$ com $\beta_i^2-4\gamma_i < 0$ para todo $i\in\{1,\ldots,r\}$
:::


:::{.proof}
Usaremos indução por $k$. Se $k=1$, então $f(x)=x-\alpha$ com algum $\alpha\in\R$ e o resultado está válido.
Assuma que o teorema está verdadeiro para polinômios $f(x)\in\F[x]$ com  $\grau{f(x)} < k$ e seja $f(x)\in\R[x]$ um polinômio de grau $k$. Pelo Teorema Fundamental da Álgebra, existe $\alpha\in\C$ tal que $f(\alpha)=0$.

Se $\alpha\in\R$, então $x-\alpha\mid f(x)$ e $f(x)=(x-\alpha)q(x)$ com $q(x)\in\R[x]$ mônico e $\grau{q(x)}=k-1$. Pela hipótese da indução,
$$
q(x)=(x-\alpha_1)\cdots (x-\alpha_s)(x^2+\beta_1x+\gamma_1)\cdots (x^2+\beta_rx+\gamma_r)
$$
com $s+2r=k-1$ e $\beta_i^2-4\gamma_i < 0$ para todo $i$.
Assim
\begin{align*}
f(x)&=(x-\alpha)q(x)\\&=(x-\alpha)(x-\alpha_1)\cdots(x-\alpha_s)(x^2+\beta_1x+\gamma_1)\cdots (x^2+\beta_rx+\gamma_r).
\end{align*}
com $\alpha_i,\beta_j,\gamma_\ell\in\R$ e $\beta_i^2-4\gamma_i < 0$ para todo $i$.

Se $\alpha\not\in\R$, então $f(\overline\alpha)=0$ e
$$
(x-\alpha)(x-\overline\alpha)\mid f(x).
$$
Note que
$$
(x-\alpha)(x-\overline\alpha)=x^2-(\alpha+\overline\alpha)x+\alpha\overline\alpha\in\R[x],
$$
pois se $\alpha=a+bi$, então $\overline\alpha=a-bi$ e assim
\begin{align*}
\alpha+\overline\alpha&=2a\in\R\\
\alpha\overline\alpha&=a^2+b^2\in\R.
\end{align*}
Portanto
$$
(x-\alpha)(x-\overline\alpha)=x^2+\beta+\gamma\in\R[x]
$$
com
\begin{align*}
\beta&=-\alpha-\overline{\alpha}=-2a; \\
\gamma&=\alpha\cdot\overline{\alpha}=a^2+b^2
\end{align*}
é um polinômio sem raízes em $\R$ e assim $\beta^2-4\gamma < 0$.
Escreva $f(x)=(x^2+\beta+\gamma)q(x)$ com $q(x)\in\R[x]$ mônico e $\grau{g(x)}=k-2$. Pela hipótese da indução,
$$
q(x)=(x-\alpha_1)\cdots (x-\alpha_s)(x^2+\beta_1x+\gamma_1)\cdots (x^2+\beta_rx+\gamma_r)
$$
com $\alpha_i,\beta_i,\gamma_i\in\R$, $k-2=s+2r$ e $\beta_i^2-4\gamma_i < 0 $ para todo $i\geq 1$. Ora,
$$
f(x)=(x-\alpha_1)\cdots (x-\alpha_s)(x^2+\beta_1x+\gamma_1)\cdots (x^2+\beta_rx+\gamma_r)(x^2+\beta x+\gamma)
$$
como foi afirmado.

:::

Na decomposição dada pelo teorema anterior os escalares $\alpha_1,\ldots,\alpha_s$ são as raízes reais de $f(x)$ contadas com multiplicidade. Isso quer dizer que uma raiz pode ocorrer várias vezes nesta lista. No caso de polinômios sobre $\R$, o número das raízes de $f(x)$ pode ser menor que $\grau{f(x)}$.

:::{#exm-}
Considere o polinômio
$$
f(x)=x^{n-1}+x^{n-2}+\cdots+x+1\in\R[x]
$$
com $n\geq 2$. No exemplo anterior determinamos as raízes complexas de $f(x)$. Se $n$ for par, então $f(x)$ possui uma única raiz real, nomeadamente o $-1$, enquanto se $n$ for ímpar, então $f(x)$ não possui raiz real. Denotando por $\alpha_k$ a $k$-ésima raiz complexa de $f(x)$ como no exemplo anterior, temos, para $k\leq n/2$ que
$$
\overline{\alpha_k}=\alpha_{n-k}.
$$
Para $k\leq n/2$, seja
$$
\beta_k=-\alpha_k-\overline{\alpha_k}=-2\cos(2k\pi /n)
$$
e note que
$$
\alpha_k\cdot \overline{\alpha_k}=\cos^2(2k\pi /n)+\mbox{sen}^2(2k\pi /n)=1.
$$
Assim obtemos a seguinte decomposição. Se $n$ for par,
\begin{align*}
f(x)&=(x+1)\prod_{k=1}^{(n-2)/2}(x^2+\beta_kx+1)\\&=(x+1)\prod_{i=1}^{(n-2)/2}(x^2-2\cos(2k\pi/n)x+1);
\end{align*}
se $n$ for ímpar, então
\begin{align*}
f(x)&=\prod_{k=1}^{(n-1)/2}(x^2+\beta_kx+1)\\&=\prod_{i=1}^{(n-1)/2}(x^2-2\cos(2k\pi/n)x+1).
\end{align*}
:::


:::{#cor-}
Um polinômio $f(x)\in\R[x]$ de grau ímpar possui raiz em $\R$
:::


:::{.proof}
Se $\grau{f(x)}$ é impar, então a sua decomposição dada pelo teorema anterior possui pelo menos um fator na forma $x-\alpha$ com $\alpha\in\R$ e assim $\alpha$ é raiz de $f(x)$
:::

